### ISSUE TITLE
MobSpawnESP needs a light source in proximity to work effectively

### ISSUE THREAD

**Issue by FrancescoMagliocco** [Wurst-Imperium/Wurst7#10]
I actually use this mod all the time., however, the lines aren't really visible unless I am beside a light source such as a torch or lantern.  Even putting a torch on my head brightens up the lines so they are actually visible.  Even then, sometimes depending on the angle my view is, the lines won't show up.  Sometimes it takes a while for the lines to show up, I've tried changing the slider, but on that note, maybe a tooltip to describe what the slider does and if higher or lower will render faster.

**Comment by Alexander01998** [comment]
Do you use a shader pack? If so, try turning it off. Shaders can mess with Wurst's ESPs and make them nearly invisible, just like you are describing.

**Comment by FrancescoMagliocco** [comment]
When I get back on the game, I shall check this out.  On my laptop, I don't really use shaders other than the *Internal Shaders* offered by Optifine.  I'll disable that and use no shaders and report back the results.

**Comment by FrancescoMagliocco** [comment]
It seems to be the shaders that are doing it.
