### ISSUE TITLE
AltRenderer spams with errors when the Internet connection is disconnected

### ISSUE THREAD

**Issue by mdenials** [Wurst-Imperium/Wurst7#1000]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

In my opinion, it is necessary to simplify the Altmanager code by removing AltRenderer from it - the reason for its lags.

### Repro steps

1. Disable Internet connection
2. Open launcher
3. Open logger in launcher
4. Enter the game
5. Open AltManager
6. See errors in logger

### Wurst Client version

7.23

### Minecraft version

1.20.6, lower and highter

**Comment by Alexander01998** [comment]
I've fixed the issue in b634d047fdc484397bdf2acd6125984178452942. AltRenderer will not be removed.
