### ISSUE TITLE
Sensivity affects AimAssist speed

### ISSUE THREAD

**Issue by mdenials** [Wurst-Imperium/Wurst7#1001]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

The speed of the Aim Assist has become dependent on the sensitivity in the settings

### Repro steps

1. Enter the test world
2. Give creative
3. Check mouse sensivity
4. Give mob spawn egg
5. Spawn mob
6. Enable AimAssist
7. Watch results

### Wurst Client version

7.43pre2

### Minecraft version

1.20.6

**Comment by Alexander01998** [comment]
Hey @mdenials,

This change is intentional. Modern anticheat plugins check if a player's head movement packets would be possible with their current mouse sensitivity setting. The overall speed in degrees per tick is still limited by the Rotation Speed setting.

**Comment by LilyKensa** [comment]
I agree with @mdenials, I set the mouse sensitivity to 70%, and now the rotation speed is so slow that I can't even hit a moving target once

> Modern anti-cheat plugins check if a player's head movement packets would be possible with their current mouse sensitivity setting. The overall speed in degrees per tick is still limited by the Rotation Speed setting.

I didn't know the server can check the player's settings...  
But if that's the case, can't we just send fake sensitivity settings to the server?
