### ISSUE TITLE
Hitbox Expander

### ISSUE THREAD

**Issue by mdenials** [Wurst-Imperium/Wurst7#1004]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack.

### What type of player would find this improvement useful?

Griefers, PVPers, Anarchy/faction players

### Description

[HitboxHack.txt](https://github.com/user-attachments/files/15525065/HitboxHack.txt)

**Comment by coolnoob78** [comment]
this is cool
