### ISSUE TITLE
Wurst v7.43 MC1.21 name display

### ISSUE THREAD

**Issue by jurohn** [Wurst-Imperium/Wurst7#1009]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

Nametags for players are not showing up

![image](https://github.com/Wurst-Imperium/Wurst7/assets/137065095/fdf385da-73be-4486-93db-36b22249caa8)

### Repro steps

Fabric 0.15.11
fabric-api-0.100.1+1.21
Wurst-Client-v7.43-MC1.21

### Wurst Client version

7.43

### Minecraft version

1.21

### Crash report (if applicable)

```plaintext
None
```

**Comment by jurohn** [comment]
Its not a server issue. Tested on 7 different servers.

**Comment by TheH00dedDragon** [comment]
yea im also having the saving problem, minecraft 1.21, wurst 7.43

**Comment by Alexander01998** [comment]
Can confirm. Will be fixed in Wurst 7.43.1.

**Comment by Alexander01998** [comment]
Wurst 7.43.1 is now available. https://www.wurstclient.net/updates/wurst-7-43-1/
