### ISSUE TITLE
Taking damage while NoFall / AntiHunger is on

### ISSUE THREAD

**Issue by J0shua6753** [Wurst-Imperium/Wurst7#1036]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

I will be flying around using creative flight with no fall on and will take damage when falling.

### Repro steps

1.flying or falling from any height even while digging straight down.
2.randomly taking damage.

### Wurst Client version

version 7.44

### Minecraft version

1.21

**Comment by Alexander01998** [comment]
Hey @J0shua6753!

I tried reproducing the issue with the steps you've provided, but I wasn't able to take any fall damage with NoFall enabled. It seems to be something specific to your setup.

Can you share any other details or configurations that might be affecting this? Please note that as of Wurst 7.44, it's possible to pause NoFall when you are holding a mace. When this feature is active, it says "NoFall (paused)" in the HackList. Could you double-check that it doesn't say that when you are taking fall damage?

Also, does the server you're playing on have any kind of anticheat that might be blocking NoFall? Let me know so we can figure this out!
