### ISSUE TITLE
Ignore the menus

### ISSUE THREAD

**Issue by ga6rielsilva** [Wurst-Imperium/Wurst7#1038]
### Pre-suggestion checklist

- [ ] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [ ] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a different kind of feature.

### What type of player would find this improvement useful?

PVPers, Anarchy/faction players, Other (please explain in description)

### Description

My suggestion is to add an option in the Wurst settings to ignore the menus (ESC, Inventories, Wurst Menus and more?) of the client. 

I recently updated my Wurst (didn't happen before) and some hacks (AimAssist, TriggerBot) simply stop working when I open the Wurst Search Menu. Not to mention that now I activate TriggerBot, the hack acts as if you were holding down the LMB to break the block in front of the player instead of making quick clicks like a normal person does.

**Comment by ga6rielsilva** [comment]
The "Simulate mouse click" option in TriggerBot is activated, I think this option interferes with Wurst working the way I want it to, and my question is this: is it possible to "simulate the mouse click", and open a menu to do other things while TriggerBot is active?

**Comment by Alexander01998** [comment]
Hey @ga6rielsilva!

Thanks for the bug report, but this is actually a known issue that's already been fixed as of Wurst 7.44. Since you're still on v7.43, updating to the latest version should solve your problem.

Give it a try and let me know if you run into any other issues.
