### ISSUE TITLE
Optimize Chinese Translation。优化中文翻译。

### ISSUE THREAD

**Issue by OutHimic** [Wurst-Imperium/Wurst7#1042]
### Pre-suggestion checklist

- [ ] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [ ] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [ ] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Changing the settings of existing features.

### What type of player would find this improvement useful?

Anarchy/faction players

### Description

原有的中文翻译文件实在是不太符合中国人的习惯，我建议优化一下，方便理解。
这是我自己花一个下午制作的翻译文件，你们可以看一下，求被应用！
[zh_cn.json](https://github.com/user-attachments/files/16360939/zh_cn.json)

The current Chinese translation may not fully align with the natural language usage and preferences of native Chinese speakers. I would like to propose an optimized version to improve comprehensibility and user experience.
Enclosed is a translation file that I have personally prepared over the course of an afternoon. I kindly request that you review it and consider its implementation.
[zh_cn.json](https://github.com/user-attachments/files/16360943/zh_cn.json)

![image](https://github.com/user-attachments/assets/b3c91289-f239-4460-a216-2fb0751627a0)

**Comment by OutHimic** [comment]
If necessary, I can optimize my translation files at any time!
At present, there is at least one thing that can be optimized, but I can't seem to change it.

如果有需要，我随时可以优化我制作的翻译文件！
目前已知有至少一处可以优化的，但是我似乎是不能更改了。

**Comment by Alexander01998** [comment]
Hey @OutHimic, thanks for helping with the translations! Would you be able to submit your changes as a Pull Request instead of an Issue? This would make it easier to review the changes you've made.

嘿 @OutHimic，感谢您在翻译方面提供的帮助！您是否可以将您的更改以 “拉取请求 ”而不是 “问题 ”的形式提交？这样会更容易查看您所做的更改。

**Comment by OutHimic** [comment]
> Hey @OutHimic, thanks for helping with the translations! Would you be able to submit your changes as a Pull Request instead of an Issue? This would make it easier to review the changes you've made.
> 
> 嘿 @OutHimic，感谢您在翻译方面提供的帮助！您是否可以将您的更改以 “拉取请求 ”而不是 “问题 ”的形式提交？这样会更容易查看您所做的更改。

Emmmm……
![Screenshot_20240724_220948_com microsoft emmx](https://github.com/user-attachments/assets/1d490847-1634-408b-9020-5d11b591ebfa)
Probably I can't unserstand it rightly .

**Comment by OutHimic** [comment]
> Hey @OutHimic, thanks for helping with the translations! Would you be able to submit your changes as a Pull Request instead of an Issue? This would make it easier to review the changes you've made.
> 
> 嘿 @OutHimic，感谢您在翻译方面提供的帮助！您是否可以将您的更改以 “拉取请求 ”而不是 “问题 ”的形式提交？这样会更容易查看您所做的更改。

In fact, this is just a simple change to the user experience, and the real localization adaptation has not yet been, and I will try to update it when I have time。
Thank you for your attention！

实际上，这还只是简单的改动了一下使用体验，真正本土化适配还没有，我会争取有时间就更新。感谢您的重视！

**Comment by Alexander01998** [comment]
Closing this as the related PR has been deleted.
