### ISSUE TITLE
MaceDMG function does not work in Killaura and Triggerbot

### ISSUE THREAD

**Issue by CXY-one** [Wurst-Imperium/Wurst7#1046]
### Pre-reporting checklist

- [x] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

The MaceDMG function only works during manual attacks and does not work in features such as Killaura and Triggerbot etc.

### Repro steps

1. Open the MaceDMG function and use a mace to manually attack creatures, which can significantly increase damage.
2. After opening the MaceDMG function, using the Killaura or Triggerbot function to attack a creature with a mace only deals the original damage without increasing the damage.

### Wurst Client version

7.44

### Minecraft version

1.21

**Comment by Alexander01998** [comment]
Hey @CXY-one,

Thanks for the report! I actually just [fixed this bug](https://github.com/Wurst-Imperium/Wurst7/commit/f4fff8159438c199256d400c86eeec890329e5bd) yesterday.

The fix will be included in the next update, so keep an eye out for that.

Cheers
