### ISSUE TITLE
I hope the buttons in the modmenu will not be covered or replaced.

### ISSUE THREAD

**Issue by StarsShine11904** [Wurst-Imperium/Wurst7#1056]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Other (please explain in description)

### What type of player would find this improvement useful?

Other (please explain in description)

### Description

I hope Wurst's option button can be placed next to the modmenu or somewhere else, because I can't adjust my mod, so I have to exit the map or the server to adjust the options of other mods again.

![image](https://github.com/user-attachments/assets/9abf3df0-00ac-4e41-9100-c3c09dacab9f)

Can you make adjustments to address this issue?

**Comment by Alexander01998** [comment]
Hey @StarsShine11904,

You can actually adjust this in the ModMenu settings. ModMenu has three different modes you can choose from: Replace, Insert, and Icon.

It looks like you're currently in Replace mode, which places the ModMenu button underneath the Wurst Options button. If you switch to either Insert or Icon mode, that will make the ModMenu button show up next to the Wurst Options button like so:

Insert mode:
![screenshot of Minecraft game menu with Wurst and ModMenu in Insert mode](https://github.com/user-attachments/assets/10ff9ae4-026b-47bb-ae5c-6aa7266f5336)

Icon mode:
![screenshot of Minecraft game menu with Wurst and ModMenu in Icon mode](https://github.com/user-attachments/assets/9dfffd5c-ee3c-43ba-9cfd-a119b7da929e)

Here's how you can change it:
1. Open the ModMenu Options.
2. Look for the "Game Menu" setting.
3. Switch it from "Replace" to either "Insert" or "Icon."

![screenshot of ModMenu Options with a red circle around the Game Menu setting](https://github.com/user-attachments/assets/966d8ab2-f359-4551-a755-49866388ade7)

Hope this helps!
