### ISSUE TITLE
AutoFish in mcMMO mode doesn't finish rotating when riding a vehicle

### ISSUE THREAD

**Issue by cottnn** [Wurst-Imperium/Wurst7#1067]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

When using AutoFish mcMMO mode in a vehicle (e.g. boat), the camera doesn't finish rotating when switching fishing spots. It simply "locks" the angle on the fishing spot, but doesn't cast the rod again. See the attached clip.

https://github.com/user-attachments/assets/a12da1b1-c3fc-44d3-a665-292dc25731fc

### Repro steps

1. Enable mcMMO mode in AutoFish and set mcMMO limit to 2 for convenience
2. Get in any vehicle (e.g. boat)
3. Cast the rod
4. After catching, cast the rod again in a different spot as per the instructions
5. Observe the bug when mcMMO tries to change the fishing spot

### Wurst Client version

7.46

### Minecraft version

1.21.1

**Comment by cottnn** [comment]
Note: In mcMMO, fishing in a boat makes you catch fish faster, which makes this bug matter on servers with mcMMO fishing

**Comment by Alexander01998** [comment]
Hey @cottnn, thanks for the detailed report! I've figured out what's causing this bug and will release a fix in the next update.
