### ISSUE TITLE
ProfileKeys incorrectly being created for alts

### ISSUE THREAD

**Issue by ThisTestUser** [Wurst-Imperium/Wurst7#1068]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

Right now, ProfileKeys is created whenever an alt is selected, even if the alt is cracked (https://github.com/Wurst-Imperium/Wurst7/blob/master/src/main/java/net/wurstclient/mixin/MinecraftClientMixin.java#L220). This doesn't cause any issues in game, besides an error message that shows up every time a server is joined.

#1069 fixes this.

### Repro steps

1. Switch to a cracked alt via AltManager.
2. Login to any server.
3. See the below error message in logs:
```
Failed to retrieve profile key pair
com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-6.0.54.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.post(MinecraftClient.java:65) ~[authlib-6.0.54.jar:?]
```

### Wurst Client version

7.46

### Minecraft version

1.21.1

**Comment by Alexander01998** [comment]
Thanks for the explanation and repro steps! I'll look into it.
