### ISSUE TITLE
Lava showing as ... weird in Xray

### ISSUE THREAD

**Issue by jurohn** [Wurst-Imperium/Wurst7#1089]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

![image](https://github.com/user-attachments/assets/0335c62f-5ae5-4b6f-9c4d-132cbde5179f)

See for yourself. In spectator mode, it looks "normal". With Xray it looks like this.

I cant remember for how long this problem already excist. But it might have to do with Sodium, again ;-)

### Repro steps

Using wurst on any smp, in combination with Sodium, sodium extra and reeses sodium options.

### Wurst Client version

7.46.4

### Minecraft version

1.21.3

### Crash report (if applicable)

```plaintext
No crash
```

**Comment by jurohn** [comment]
> Yes, this normal with Sodium. I'm not sure why it happens, but I can't seem to stop it from doing that. The same thing happens with water too.

Alright....maybe in the future you will figure it out! Thank you

**Comment by jurohn** [comment]
@Alexander01998 Sodium fixed it in 0.6.3 theirselve, so its fixed :)

**Comment by Alexander01998** [comment]
Oh, nice!
