### ISSUE TITLE
Add crafter to ChestESP

### ISSUE THREAD

**Issue by axel103** [Wurst-Imperium/Wurst7#1090]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Changing the settings of existing features.

### What type of player would find this improvement useful?

Griefers

### Description

Hoppers, chests and any other block that can hold items is included in ChestESP, except for Crafters.

**Comment by Alexander01998** [comment]
Crafters are included in ChestESP. They were added in [Wurst 7.38](https://www.wurstclient.net/updates/wurst-7-38/).
