### ISSUE TITLE
[1.21.4/7.46.4] NoFall doesn't work at all

### ISSUE THREAD

**Issue by andrew121410** [Wurst-Imperium/Wurst7#1092]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [x] I have tried removing all other mods and the bug still happens.

### Description

NoFall doesn't work at all on 1.21.4

My current mods I have
![image](https://github.com/user-attachments/assets/94912cf4-0812-4a66-b837-b7f5b965e956)

### Repro steps

1. Go on 1.21.4
2. Join a survival server
3. Fall and damage still happens!

### Wurst Client version

7.46.4

### Minecraft version

1.21.4

**Comment by Alexander01998** [comment]
There is also a discussion about this on WurstForum: https://wurstforum.net/d/891

**Comment by andrew121410** [comment]
My server is on spigot 1.21.1 using ViaVersion I can connect on 1.21.4 and NoFall still doesn't work. So could this possible just be a client issue and not a server issue, meaning this can be fixed right?, since it's just a client issue? Idk lol

**Comment by Alexander01998** [comment]
I finally found what's causing this. Minecraft's client-side fall distance counter is now permanently stuck at zero. Simply ignoring that counter fixes the issue.
