### ISSUE TITLE
Freecam doesnt render the FakePlayerEntity when activating it the first time after joining a world

### ISSUE THREAD

**Issue by MrFrog222** [Wurst-Imperium/Wurst7#1096]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

When i join a world and enable Freecam the FakePlayerEntity that should be instantiated spawns but it has no texture. This issue is not resolved until i disable and re-enable Freecam at which point the issue is resolved for the rest of the session until i join a different world

### Repro steps

1. Go into a world(Singleplayer or Multiplayer)
2. Enable Freecam

### Wurst Client version

7.46.5

### Minecraft version

1.21.4

**Comment by Alexander01998** [comment]
Hey @MrFrog222,

I'm aware of this bug and I tried to fix a while ago, but I couldn't seem to figure out what exactly causes the fake player to be invisible and why spawning it a second time fixes the issue for that session.

It would seem that there is some kind of initialization logic that needs to run before spawning the entity, but I didn't find anything last time I looked into this.

Any help is much appreciated if anyone knows what is going on here.
