### ISSUE TITLE
Left Clicking when AutoMine is enabled crashes the game

### ISSUE THREAD

**Issue by FrancescoMagliocco** [Wurst-Imperium/Wurst7#11]
I tried twice to see if it was just a fluke, but enabling **AutoMine** and left clicking *(I had a pick in my hand, but I'm not sure if that is mandatory or not)* crashes the game.

**Comment by Alexander01998** [comment]
Thank you for your bug report. Since you are reporting a game crash, please also attach the crash report file that this crash has generated. You can find it in the `.minecraft/crash-reports` folder.

**Comment by FrancescoMagliocco** [comment]
I'll be sure to attach the crash file when I'm on my laptop next.
