### ISSUE TITLE
Nuker - Disconnected from sending to many packets

### ISSUE THREAD

**Issue by FrancescoMagliocco** [Wurst-Imperium/Wurst7#12]
If you're holding a pick and you have nuker enabled, if say a block that requires something else that isn't a pick to break is I'm the radius, nuker fails to work and you get disconnected from sending to many packets.  

This happens a lot when mining randomly underground, and you come near gravel or dirt.  Also, if you're beside bedrock (Not on it) the something happens.  A lot of the time to avoid getting disconnected, you need to stop mining and move back away from the blocks that aren't affected by a pick.

A couple solutions could be:
- Only break blocks that are affected by the tool in hand: If holding a pick, only break blocks in the radius that can be broke by a pick, ignoring all other blocks like grass, gravel etc.. 
- Allow a list of blocks to be chosen (Similar to **ID** mode but you can specify the blocks).  This could prove to be beneficial in some cases as you can't break bedrock in Survival, but can in Creative.

This last one is more of a feature request:  Right now you can specify a hotkey to enable and disable nuker, but I think adding an option where nuker is only *Activated* when holding Left Click could be more useful as well.  That way when Nuker is enabled, it will only activate as you press and hold left click, and if you're not holding left click, it won't activate.  Having nuker disabled would obviously have left click act as normally intended.

**Comment by Mhowser** [comment]
try setting Nuker to a block ID instead.

**Comment by huzpsb** [comment]
please switch the mode of your nuker
