### ISSUE TITLE
Navigator Search Bar Bug

### ISSUE THREAD

**Issue by ThisTestUser** [Wurst-Imperium/Wurst7#126]
When the navigator hack is binded to a keybind like "N", pressing the keybind will cause the key "N" to appear on the search bar. This does not happen with Wurst 6.

How to Replicate:
- Set the navigator keybind to "N"
- Press the keybind
- Navigator will pop up, but the letter n is already typed into the search field.

**Comment by lasnikprogram** [comment]
Known Bug which sadly happens with every letter
