### ISSUE TITLE
Added NoHurtcam

### ISSUE THREAD

**Issue by Mersid** [Wurst-Imperium/Wurst7#13]
Forked a copy and added the NoHurtcam mod to it. Mind taking a look? (sorry, didnt know where else to post this).

**Comment by FrancescoMagliocco** [comment]
You're suppose to open a **Pull Request**

**Comment by Mersid** [comment]
Sorry, I'm new to this code-contribution thing. How do I open a pull request? The "Pull Request > New Pull Request" buttons drop me into "Compare Changes"...

**Comment by Alexander01998** [comment]
[Your repository](https://github.com/Mersid/Wurst7) doesn't seem have a NoHurtcam hack added to it. It's just an exact copy of this one.

That might also be why it's not letting you create a pull request.
