### ISSUE TITLE
AntiCactus doesn't work

### ISSUE THREAD

**Issue by Mersid** [Wurst-Imperium/Wurst7#133]
## Description
AntiCactus doesn't work.

## Steps to reproduce
1. Go to a cactus
2. Touch the cactus

## (Optional) screenshots / videos
If applicable, add screenshots or videos to help explain your problem.

## Versions
Please complete the following information:
- Minecraft version: [e.g. 1.16.1]
- Wurst version: [e.g. 7.3]

## Crash report
```
(crash report goes here)

```
Please note: A log file or a picture of the launcher's "something went wrong" screen are _not_ the same as crash report. If the game didn't crash, please hold down F3+C for 10 seconds to generate a crash report.

**Comment by Alexander01998** [comment]
Fixed in fb32016c9d4d1676ed5797562a04d56a94d1997c.
