### ISSUE TITLE
AntiBlind doesn't work

### ISSUE THREAD

**Issue by Mersid** [Wurst-Imperium/Wurst7#134]
## Description
AntiBlind doesn't work - it appears to make the blindness white instead of black. Maybe a mixin injection problem with 1.16?

## Steps to reproduce
1. Apply blindness to self.

## (Optional) screenshots / videos
If applicable, add screenshots or videos to help explain your problem.

## Versions
Please complete the following information:
- Minecraft version: [e.g. 1.16.1]
- Wurst version: [e.g. 7.3]

## Crash report
```
(crash report goes here)

```
Please note: A log file or a picture of the launcher's "something went wrong" screen are _not_ the same as crash report. If the game didn't crash, please hold down F3+C for 10 seconds to generate a crash report.

**Comment by Alexander01998** [comment]
Closing as this was fixed in #180 ([Wurst 7.6](https://www.wurstclient.net/updates/wurst-7-6/)).
