### ISSUE TITLE
.damage Instakills you on single player Wurst 1.14.4

### ISSUE THREAD

**Issue by princefl** [Wurst-Imperium/Wurst7#136]
On Wurst for 1.14.4 doing .damage 1-7 will instakill you on a single player world. This is not the case on older and newer versions.
Wurst version 7.1.2 and 7.2.

**Comment by Alexander01998** [comment]
Closing this issue as Wurst for Minecraft 1.14.4 has reached end of support. I'm sorry this issue didn't get resolved, but at this point I'm afraid it won't be fixed anymore. Due to time constraints and the continuous development of Minecraft, I have to focus my attention on more recent versions.
