### ISSUE TITLE
Player tags using RGB colours show as white

### ISSUE THREAD

**Issue by lucyy-mc** [Wurst-Imperium/Wurst7#142]
## Description
Player name tags show as white when using RGB

## Steps to reproduce
1) Connect to a server running 1.16, using RGB in player names
2) Observe

If applicable, add screenshots or videos to help explain your problem.

1.16.1 Vanilla:
![image](https://user-images.githubusercontent.com/35287819/86458406-1ad3a280-bd1d-11ea-8ac6-76194a604ea6.png)

1.16.1 Wurst 7.3:
![image](https://user-images.githubusercontent.com/35287819/86458352-08f1ff80-bd1d-11ea-9769-68dae0991e86.png)

## Versions
Please complete the following information:
- Minecraft version: 1.16.1
- Wurst version: 7.3

## Crash report
N/A

**Comment by lucyy-mc** [comment]
Seems to be related to #135 .

**Comment by Mersid** [comment]
Try merging #137 into your build and run that on the server?

**Comment by lucyy-mc** [comment]
Any chance I'd be able to get a prebuilt jar? I'm away from home atm and this laptop isn't set up for java

**Comment by Mersid** [comment]
Sure! https://github.com/Mersid/Wurst7/releases/tag/1.16.1
It also has some other features, such as PlayerESP working off name tag colours (configurable), health tags showing max health, better autosteal and autotool, the .hacklist command, and some other odds and ends. If you really need the specific version with only the colour patch, lemme know and I'll build that specific version for ya.
Cheers!

**Comment by lucyy-mc** [comment]
Thanks for that, I can confirm that the colours are now displaying.
Including the IPs in the screenshots was a bad idea (should've seen it coming tbh) so I've taken them out the original post.
Thanks for your help.
