### ISSUE TITLE
Killaura does not consider teams.

### ISSUE THREAD

**Issue by Wfsneed2** [Wurst-Imperium/Wurst7#149]
## Description
When enabling killaura (KillAuraLegit, MultiAura, TriggerBot, ... also) on games like annihilation which have team battles it will attack teammates.

## Steps to reproduce
1. Run Wurst client 7.3 for Minecraft 1.16.1
2. Enable the KillAura (or any "AutoAttack" bot)
3. Approach your teammate.
4. Fail at attacking the other team.

## Versions
Please complete the following information:
- Minecraft version 1.16.1
- Wurst version: 7.3

**Comment by wurstisgood** [comment]
add your teammates as friends by middle click

**Comment by Wfsneed2** [comment]
@wurstisgood That's what I have been doing. But it's kinda annoying everytime a new game starts to run around clicking everyone of your teammates...

**Comment by Nikitka12XD** [comment]
In Impact, you can exclude teammates everywhere, I would like it to be in Wurst

**Comment by AMOGHPS123** [comment]
How do I even add teammates
