### ISSUE TITLE
Mining overlay not visible when automine and overlay are enabled together

### ISSUE THREAD

**Issue by TwoPointInfinity** [Wurst-Imperium/Wurst7#151]
## Description
Overlay not visible when automine and overlay are both enabled unless the gui menu is open

## Steps to reproduce
open gui, enable automine, enable overlay, close gui

## Versions
Please complete the following information:
- Minecraft version: 1.16.1
- Wurst version: 7.3

**Comment by TwoPointInfinity** [comment]
automine also restarts the process of breaking a block when the gui is opened or closed.

**Comment by Cyclopropinon** [comment]
the no overlay bug still exsists :(
