### ISSUE TITLE
AutoEat doesn't work when food is in left hand.

### ISSUE THREAD

**Issue by andrew121410** [Wurst-Imperium/Wurst7#152]
## Description
AutoEat doesn't work when food is in left hand but works when food is in the right hand.

## Versions
-Minecraft version: 1.16.1
-Wurst version: 7.3

**Comment by JamesTheAwesomeDude** [comment]
Would absolutely love this, for the offhand stack of saturating food

**Comment by JamesTheAwesomeDude** [comment]
This bug affects AutoFish, too

**Comment by andrew121410** [comment]
> 
> 
> Would absolutely love this, for the offhand stack of saturating food

Absolutely agree
