### ISSUE TITLE
AutoFish reels in too early, misses fish

### ISSUE THREAD

**Issue by leumasme** [Wurst-Imperium/Wurst7#156]
## Description
AutoFish seems to reel in the fishing rod too early, causing it to miss the fish. I believe that this is caused by a slightly laggy server.

## Steps to reproduce
- Play on a Server that has reduced TPS
- Use AutoFish
- Watch

## (Optional) screenshots / videos
Video of Wurst trying to Fish: https://www.youtube.com/watch?v=SzRY1ujU6yE
Video of Manual Fishing: https://www.youtube.com/watch?v=iLk8VhbbF58

## Versions
Please complete the following information:
- Minecraft version: 1.14.4
- Wurst version: v7.3

## Crash report
- (no crash)

## Additional Notes
A possible fix for this might be to wait for the fishing rod to actually get pulled down into the water, which also causes a sound.
Another idea would be a Delay Setting in the AutoFish Module.
On that note, Delay Settings for other parts of autofish, like the delay between reeling in and throwing the rod again, would be useful too, as it can happen that wurst throws out the rod too early, causing it to hit the item from the last catch that is flying towards the player.

**Comment by Alexander01998** [comment]
Closing as this was fixed in [Wurst 7.35](https://www.wurstclient.net/updates/wurst-7-35/).
