### ISSUE TITLE
Installation on MultiMC

### ISSUE THREAD

**Issue by superuser127** [Wurst-Imperium/Wurst7#157]
Due to the specific installation WORST cannot be installed on the MultiMC.  There may be a solution, but I could not find it.  I hope you can help me with the search

**Comment by Alexander01998** [comment]
The MultiMC installation procedure for Wurst is the same as for any other Fabric mod. https://fabricmc.net/wiki/player:tutorials:install_multimc:windows

**Comment by superuser127** [comment]
> Процедура установки MultiMC для Wurst такая же, как и для любого другого модма Fabric. https://fabricmc.net/wiki/player:tutorials:install_multimc:windows

Close early.  I tried installing in the standard way on 1.12.2.  Nothing came of it
