### ISSUE TITLE
Gradle build .jar just doesn't work.

### ISSUE THREAD

**Issue by Mikilis** [Wurst-Imperium/Wurst7#166]
Hey! I modified some of hacks, and built with `./gradlew.bat build`, after build copied `Wurst-Client-v7.4-MC1.16.1.jar` to `mods/`. But it's doesn't works. No crash, no error, just log: [Log on Pastebin](https://pastebin.com/fbj9jVcU)
Any other build command needed?

**Comment by Mikilis** [comment]
also -dev.jar don't work

**Comment by lasnikprogram** [comment]
There must be an error, even the Indigo Renderer is working... Where did you get the Log from and did you start the mod from your Minecraft Launcher and then nothing happend or what?

**Comment by Mikilis** [comment]
I got the log from my launcher. After gradlew clean my .jar just worked.
