### ISSUE TITLE
Search not working in amplified worlds

### ISSUE THREAD

**Issue by gurachan** [Wurst-Imperium/Wurst7#168]

**Comment by Alexander01998** [comment]
Sorry, what?

**Comment by Dj-jom2x** [comment]
ah this one is old xD when the server use amplified world.. the search is not working

**Comment by ThisTestUser** [comment]
#100 may fix this, because one side effect of the search bug is that worlds/servers with small chunk distances do not display properly.

**Comment by Alexander01998** [comment]
Closing this issue as it seems to be fixed.
