### ISSUE TITLE
Something about the AutoFarm

### ISSUE THREAD

**Issue by Cherrling** [Wurst-Imperium/Wurst7#169]

**Comment by Cherrling** [comment]
the bamboo has been added to the game for a while, i hope the developer can edit the autofarm to support the bamboo,
also,the"AutoTool" hasn't support the bamboo ,thanks

**Comment by MineYuanlu** [comment]
In my opinion, "AutoFarm" should be like "X-ray", which allows users to customize the ore list. By creating the mapping relationship between crop block and seed item, users can customize crops and make this feature support mod
At the same time, I think "AutoTool" should create custom lists in the same way.

我认为 “AutoFarm” 应该像“X-Ray”一样，让用户可以自定义列表，通过创建农作物方块与种子物品的映射关系，达到自定义农作物的目的，让此Feature支持mod

同时我认为“AutoTool”也应该如此创建自定义列表

**Comment by Cherrling** [comment]
我同意你的看法，但是让用户自定义列表的话，例如甘蔗和小麦的收割方式是不同的，我觉得应该让开发者加入大部分的农作物，同时创建一个列表决定收割哪些农作物，比如有时候我只想收割小麦但不收割胡萝卜

---
I agree with you, but if you let users customize the list, for example, the harvesting methods of sugarcane and wheat are different. I think developers should add most of the crops and create a list to decide which crops to harvest. For example, sometimes I only want to harvest wheat but not carrots

**Comment by Alexander01998** [comment]
Added in 591ec9d6b79a74e5301931c9e7ebbcbc35145e7b.
