### ISSUE TITLE
Scaffoldwalk not working properly

### ISSUE THREAD

**Issue by ParadoxModders** [Wurst-Imperium/Wurst7#178]
sCAFfoLD noT woRK pROpeRLY in servers aND keWEps bRingiNG me Back To thE place where I waS beFore plEz FixX

**Comment by procrafter820** [comment]
yes for me too i said it so many times on reddit and 95% users reply me that they also have same problem but @alexander01998 does not respond :(

**Comment by Mikilis** [comment]
anticheat :|

**Comment by Alexander01998** [comment]
Not sure if this is a joke, but ScaffoldWalk works fine for me.

**Comment by wurstisgood** [comment]
> Not sure if this is a joke, but ScaffoldWalk works fine for me.

but not for me

**Comment by XfedeX** [comment]
@wurstisgood That is probably caused by the anticheat. Please mark as solved.
