### ISSUE TITLE
please can anyone code so that killaura,triggerbot etc. also has settings of speed 

### ISSUE THREAD

**Issue by procrafter820** [Wurst-Imperium/Wurst7#179]
please can anyone code so that killaura,triggerbot etc. also has settings of speed .it is actually not a bug

**Comment by KGriss** [comment]
Actually not a bug but an enhancement

**Comment by svegon** [comment]
I don't know what's that good for but I'll do it.

**Comment by wurstisgood** [comment]
> I don't know what's that good for but I'll do it.

thank yo so much i know MC only registers around 4 clicks per second but the adavantage is that suppose you hit an entity for 0.2 seconds then it will hit 1 time in 5 CPS but 3 times in 15 CPS so we can deal more damage

**Comment by wurstisgood** [comment]
i am actually procrafter

**Comment by Alexander01998** [comment]
Added in fdd6812b2461c28a7f93933a603fe26285d38a0e.
