### ISSUE TITLE
NameTag Colour

### ISSUE THREAD

**Issue by Ekpoa** [Wurst-Imperium/Wurst7#186]
## Description
Coloured names for ranks and armour stands show as plain white text

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
Edit the team colour of an alt account and notice how their username is still white

## Screenshots / Videos (Optional)
https://gyazo.com/039e07fce892d05fa28e95024c161f27

![039e07fce892d05fa28e95024c161f27](https://user-images.githubusercontent.com/71354031/93269028-21af7480-f7a6-11ea-991f-ddbe0817e8da.png)

**Comment by Alexander01998** [comment]
This has been fixed in [Wurst 7.6.2](https://www.wurstclient.net/updates/wurst-7-6-2/).
