### ISSUE TITLE
Killauralegit sometimes does not attack entities and if it attacks then it automatically stops after some hits

### ISSUE THREAD

**Issue by wurstisgood** [Wurst-Imperium/Wurst7#188]
Killauralegit sometimes does not attack entities and if it attacks then it automatically stops after some hits

**Comment by KGriss** [comment]
Did you tried the classic Killaura ? And Multiaura ?

I had the same problem because I checked the "Filter named" and the server I was on used the name as a heath bar

**Comment by wurstisgood** [comment]
yes killaura and multiaura works but anticheat bans

> Did you tried the classic Killaura ? And Multiaura ?
> 
> I had the same problem because I checked the "Filter named" and the server I was on used the name as a heath bar

**Comment by wurstisgood** [comment]
Now it works but not full Bypass

**Comment by wurstisgood** [comment]
[https://github.com/Wurst-Imperium/Wurst7/issues/214](url)

**Comment by XfedeX** [comment]
I am having this issue sometimes too, to "fix" it just attack manually the entity.
