### ISSUE TITLE
Mixins and Mod Conflicts

### ISSUE THREAD

**Issue by Mersid** [Wurst-Imperium/Wurst7#19]
It took me four goddamn hours to narrow this down...

Anyways, it turns out Fabric throws a fit when two mods with the same mixin json file name is loaded, and will crash with a useless log. So, Wurst's mixin file name is modid.mixins.json. If anyone else made a mod and used the same json file name, this error will pop up. I recommend renaming this file - perhaps to wurst.mixins.json or something, and reflect that change in the fabric.mod.json file as well.

**Comment by Alexander01998** [comment]
Interesting. Can you name any mods that use the same file name? I would like to see for myself.

**Comment by Mersid** [comment]
Eh, I was making a custom mod for myself when this problem arose. Theoretically, any mod programmer that forgot or neglected to rename the mixin file that came with the template will raise this issue.
