### ISSUE TITLE
Feature request: World Edit

### ISSUE THREAD

**Issue by SirEnder125** [Wurst-Imperium/Wurst7#194]
Sorry, this is not a bug report, but I can't figure out where to request features.

I want to know if you can add a world edit hack, also, .rename still wont add colors...

**Comment by mthvrs** [comment]
What would a world edit hack even do?

**Comment by SirEnder125** [comment]
It would fill the area from point X to point Y with a block?

**Comment by MaslovKK** [comment]
impossible

**Comment by SirEnder125** [comment]
Uhh, why are you replying to this now?
You're late. Hahaha.
