### ISSUE TITLE
ForgeWurst shows up in server side mod list if they check

### ISSUE THREAD

**Issue by Ashley123477** [Wurst-Imperium/Wurst7#201]
## Description
What's wrong?

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1.  If caught hacking, admins can check through the server logs to see that you have forgewurst installed on client
2. 
3. 

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

(crash report goes here)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by Alexander01998** [comment]
AFAIK all Forge mods show up in the mod list. I'm not aware of any way to bypass this.

**Comment by ThisTestUser** [comment]
If you are still updating ForgeWurst, you can use ASM to visit "net.minecraftforge.fml.common.network.handshake.FMLHandshakeMessage.ModList" and remove the modid in the mod list that is sent to the server. (https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/network/handshake/FMLHandshakeMessage.java)

**Comment by MrYotic** [comment]
> Насколько я знаю, все моды Forge отображаются в списке модов. Я не знаю, как это обойти.

![image](https://user-images.githubusercontent.com/55879406/101279958-2b5ddc80-37d7-11eb-9200-0b80bb20ff71.png)

**Comment by MrYotic** [comment]
This is a workaround for one of the launcher servers
In this workaround I put Wurst and Wurst was not in the list but it worked, maybe this will help you
