### ISSUE TITLE
Cannot join server with particular plugin

### ISSUE THREAD

**Issue by RandomAccountt** [Wurst-Imperium/Wurst7#202]
## Description
Plugins like https://hackedserver.org prevent me from joining a server because it detects fabric.

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Have a sever with the plugin installed.
2. Join with a modified client.
3. Get kicked

## Screenshots / Videos (Optional)
![kicked](https://user-images.githubusercontent.com/30158779/97722013-113b2b00-1ac2-11eb-936a-62a7c36cb7fd.png)

**Comment by Alexander01998** [comment]
This should be fixed once #143 is merged.

**Comment by Alexander01998** [comment]
This has been fixed in 494d0cc8b8f5dd20c0f07dd10e6515797c5b3865 and will be released in Wurst 7.7.
