### ISSUE TITLE
F3 spoofer

### ISSUE THREAD

**Issue by RandomAccountt** [Wurst-Imperium/Wurst7#203]
## Describe the thing that you're suggesting
I play on a server which requires me to immediately send a screenshot on discord of my F3 screen if I am suspected of hacks. This is because they can see if I'm using a modified Fabric client in the top left of the screen. An F3 spoofer would be able to change the text to make it appear vanilla. I have seen this done successfully in other clients.

**Comment by wurstisgood** [comment]
ya other clients have it,good idea
