### ISSUE TITLE
[SUGGESTION] [SRC] Baritone System

### ISSUE THREAD

**Issue by Mikilis** [Wurst-Imperium/Wurst7#208]
Before posting, please make sure that this hasn't already been suggested by someone else.

SOURCE CODE: [Baritone](https://github.com/cabaletta/baritone)

## Describe the thing that you're suggesting
Baritone is the pathfinding system used in Impact since 4.4.

## Screenshots / Videos (Optional)
[Showcase video](https://youtu.be/CZkLXWo4Fg4)

I hope Alexander implement this :)

**Comment by Alexander01998** [comment]
We already have this. https://www.wurstclient.net/tutorials/wurst-7-baritone/

**Comment by wurstisgood** [comment]
> We already have this. https://www.wurstclient.net/tutorials/wurst-7-baritone/

but it would be good if it was prebuild @Alexander01998

**Comment by Mikilis** [comment]
yeah

**Comment by Mikilis** [comment]
sorry for confusion
