### ISSUE TITLE
[Suggestion]BowTriggerBot

### ISSUE THREAD

**Issue by AeroCarmel** [Wurst-Imperium/Wurst7#210]
A hack that auto shoots enemies (without moving the mouse) could be paired with bow-aim-bot for that. adjustable time for drawing the bow.

![2020-11-09_22 41 03](https://user-images.githubusercontent.com/74230919/98637040-c947af80-22dc-11eb-94ff-bb26a7628b91.png)
![2020-11-09_22 41 18](https://user-images.githubusercontent.com/74230919/98637046-cb117300-22dc-11eb-97e5-0a748c89f5b3.png)
I wanna be able to shoot theese mobs to increase mcmmo without having to sit here and do it manually XD.
I would program it myself but i havent programmed any mods for minecraft only plugins...

**Comment by ThisTestUser** [comment]
I did this a while ago, which should work here: https://github.com/ThisTestUser/Wurst7/blob/autoshoot/src/main/java/net/wurstclient/hacks/AutoShootHack.java
It doesn't work for crossbows though.

**Comment by wurstisgood** [comment]
> I did this a while ago, which should work here: https://github.com/ThisTestUser/Wurst7/blob/autoshoot/src/main/java/net/wurstclient/hacks/AutoShootHack.java
> It doesn't work for crossbows though.

create a pull request

**Comment by AeroCarmel** [comment]
> I did this a while ago, which should work here: https://github.com/ThisTestUser/Wurst7/blob/autoshoot/src/main/java/net/wurstclient/hacks/AutoShootHack.java
> It doesn't work for crossbows though.

If you could make a pull request with this feature I would be very grateful for your service.

**Comment by wurstisgood** [comment]
> > I did this a while ago, which should work here: https://github.com/ThisTestUser/Wurst7/blob/autoshoot/src/main/java/net/wurstclient/hacks/AutoShootHack.java
> > It doesn't work for crossbows though.
> 
> If you could make a pull request with this feature I would be very grateful for your service.

it would even help me a lot
