### ISSUE TITLE
killaura legit does not bypass completely as it makes sudden rotations to the enemy,it would be good if there was a slider for speed of head movement to bypass even better

### ISSUE THREAD

**Issue by wurstisgood** [Wurst-Imperium/Wurst7#214]
killaura legit does not bypass completely as it makes sudden rotations to the enemy,it would be good if there was a slider for speed of head movement to bypass even better

**Comment by wurstisgood** [comment]
and also random CPS for killaura legit for better bypass!

**Comment by TheAwesome98-Real** [comment]
Killaura legiter?
