### ISSUE TITLE
What is the code style guide for this repo

### ISSUE THREAD

**Issue by GreenScripter** [Wurst-Imperium/Wurst7#216]
I'm considering contributing, however I like to use Eclipse's automatic code formatting. If one was used for the rest of the repo, could I have a list of the settings or the export xml? If that isn't used than just a description of preferred formatting would be fine. As it currently stands, using my auto formatter will reformat the rest of the file differently, which makes finding the changes in git very difficult. I've currently made a lot of updates to my own fork of Wurst, some of which I think would fit nicely into the original.

**Comment by Alexander01998** [comment]
Sure, here you go: [Wurst7 code style settings.zip](https://github.com/Wurst-Imperium/Wurst7/files/5543756/Wurst7.code.style.settings.zip)

**Comment by GreenScripter** [comment]
Thanks!
