### ISSUE TITLE
About 7 Bugs and 2 Simple QoL Recommendations

### ISSUE THREAD

**Issue by TheWienerMaster** [Wurst-Imperium/Wurst7#219]
## Description

**All the bugs that I know of so far:**
1. Alt list manager will crash the game, when you decide to use the "Import Alts" button on fullscreen
2. "Block filter menu" is graphically bugged, the blocks in the background overlap the input box
3. Can't add some blocks to the block filter menu, because their id-s are too long (Example: cracked_polished_blackstone_bricks)
4. I know the Optifabric and xray bug has been reported before, but just in case I'll still remind that they still don't work together

**Bugs, that I'm not sure can be called bugs:**
1. Autoeat doesn't detect off-hand food
2. Random build doesn't detect off-hand blocks
3. When flying at high-speeds downwards and removing the flight hack then you will get fall damage mid-air and have your momentum stopped (don't know if this can be even fixed)

**And finally I'd like to recommend some really simple and worthwhile quality of life features:**

**1. Coordinates** (Having the f3 button on the entire time is quite ugly, but it's happened more then a few times when I've died and have had no idea where it happened. I mean death waypoints would also be a neat feature, but I can safely assume that they are harder to code than just some coordinates on screen.)
**2. Autoitem** (Automatically place a new stack of the same block in your hand from your inventory when you run out. Would be extremely useful and convenient in building)

## Videos 
Optifabric and Xray:
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/61437644/99154610-d0463780-26b9-11eb-84ec-839e890904b6.gif)

Alt List Crash:
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/61437644/99154756-d38df300-26ba-11eb-8373-01b1f9b0c996.gif)

Block Filter Graphical Bug:
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/61437644/99154644-274c0c80-26ba-11eb-9df3-f60a49418700.gif)

Block Filter Long Id:
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/61437644/99154682-53678d80-26ba-11eb-9f22-9f31702f5402.gif)

Autoeat off-hand:
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/61437644/99154696-69754e00-26ba-11eb-912e-af7d2941c210.gif)

Buildrandom off-hand:
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/61437644/99154716-8ad63a00-26ba-11eb-891c-bcdcfdaec47e.gif)

Flying downwards and getting damage:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/61437644/99154741-a8a39f00-26ba-11eb-868c-6b5462bfb101.gif)

## Crash Report -

**Didn't get a crash report when it crashed from the alt manager, so I crashed it manually**

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 14.11.20 20:15
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Keyboard.pollDebugCrash(Keyboard:663)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1574)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:996)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_128.handler$zdp000$fillSystemDetails(class_128.java:523)

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.3
	OptiFine jar version: OptiFine_1.16.3_HD_U_G4
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\Holger\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.3_HD_U_G4\Optifine-mapped.jar
	OptiFabric error: <None>
Stacktrace:
	at net.minecraft.class_128.handler$zdp000$fillSystemDetails(class_128.java:523)
	at net.minecraft.class_128.<init>(class_128.java:55)
	at net.minecraft.class_309.method_1474(class_309.java:663)
	at net.minecraft.class_310.method_1574(class_310.java:1574)
	at net.minecraft.class_310.method_1523(class_310.java:996)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- Affected level --
Details:
	All players: 1 total; [class_746['TheWienerMaster'/141, l='ClientLevel', x=-68.93, y=71.00, z=184.36]]
	Chunk stats: Client Chunk Cache: 1089, 782
	Level dimension: minecraft:overworld
	Level spawn location: World: (-94,74,256), Chunk: (at 2,4,0 in -6,16; contains blocks -96,0,256 to -81,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1186029 game time, 1175375 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 520124280 bytes (496 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.23.0+build.410-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c95
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.0+c270b09895
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.5.2+3c53fe3395
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.1+f8ac1db295
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.1+f8ac1db295
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.3+f8ac1db295
		fabricloader: Fabric Loader 0.10.3+build.211
		fabritone: Fabritone 1.6.2
		io_sentry_sentry: sentry 3.1.0
		minecraft: Minecraft 1.16.3
		mm: Manningham Mills 2.1
		optifabric: OptiFabric 1.7.0
		wurst: Wurst Client v7.7.1-MC1.16.3
	Launched Version: fabric-loader-0.10.3+build.211-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.30, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric/fabric-screen-handler-api-v1, fabric/fabric-renderer-api-v1, fabric/fabric-networking-blockentity-v0, fabric/fabric-keybindings-v0, fabric/fabricloader, fabric/fabric-tool-attribute-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-containers-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-item-api-v1, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-key-binding-api-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-resource-loader-v0, fabric/fabric-textures-v0, fabric/fabric-content-registries-v0, fabric/fabric-tag-extensions-v0, fabric/fabric-biome-api-v1, fabric/fabric-rendering-fluids-v1, fabric/fabric-registry-sync-v0, fabric/fabric-blockrenderlayer-v1, fabric/fabric-lifecycle-events-v1, fabric/fabric-mining-levels-v0, fabric/fabric-renderer-registries-v1, fabric/fabric-loot-tables-v1, fabric/fabric-events-lifecycle-v0, fabric/wurst, fabric/fabric, fabric/fabric-models-v0, fabric/fabric-item-groups-v0, fabric/fabric-object-builders-v0, fabric/fabric-networking-v0, fabric/mm, fabric/optifabric, file/Skies.zip
	Current Language: English (Canada)
	CPU: 6x Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz

**Comment by TheWienerMaster** [comment]
Scaffoldwalk also doesn't recognize off-hand blocks, nor does autobuild. 

Oh and talking about autobuild, it has the option to be legit or not-legit by checking line of sight. What it does is checks weather you are allowed to place blocks through walls or not. But for some reason autobuild still requires you to have the correct angle to place a block, otherwise it just wont place, don't know if it's bug or working as intended.

**Comment by TheWienerMaster** [comment]
And since I'm already in a ranting mood I remembered another simple QoL feature. Nukers should have an option that you can tick so that they don't mine the block from straight under you.

**Comment by mthvrs** [comment]
Regarding the optifabric and xray bug: it's because xray relies on the fabric rendering api which mods like sodium or optifine override. Curiously though other stuff like overlays for chests, the "search" feature, ... do not require the rendering api.

**Comment by mthvrs** [comment]
Regarding your 2 QoL features, given using Wurst requires using Fabric you're better off using Tweakeroo and MiniHud, two mods that provide what you're asking for and more.

**Comment by TheWienerMaster** [comment]
> Regarding your 2 QoL features, given using Wurst requires using Fabric you're better off using Tweakeroo and MiniHud, two mods that provide what you're asking for and more.

Yeah I know that I could easily be using other mods to compensate for my needs, but Wurst already being such a jack of all trades mod makes me think that adding these features wouldn't hurt it one bit. Also I'm certain that other people have also wanted them, but nobody has spoken up, because they used the easy route and just added other mods to compensate. 
And the "nuker not mining from straight under you" feature is something that I actually need and can't get anywhere else. Too often do I spleef myself because the closest blocks are the ones straight under me.

**Comment by wurstisgood** [comment]
> > Regarding your 2 QoL features, given using Wurst requires using Fabric you're better off using Tweakeroo and MiniHud, two mods that provide what you're asking for and more.
> 
> Yeah I know that I could easily be using other mods to compensate for my needs, but Wurst already being such a jack of all trades mod makes me think that adding these features wouldn't hurt it one bit. Also I'm certain that other people have also wanted them, but nobody has spoken up, because they used the easy route and just added other mods to compensate.
> 
> And the "nuker not mining from straight under you" feature is something that I actually need and can't get anywhere else. Too often do I spleef myself because the closest blocks are the ones straight under me.

yes it would help me

**Comment by wurstisgood** [comment]
and 1 more thing,it would be great if there was a hack that caused empty soup to drop out and the other soups to bring in that place.I know it is in AutoSoup but as AutoSoup always eats the Soup at a fixed health,so the Anticheat detects it
