### ISSUE TITLE
it would be great if there was a hack that caused empty soup to drop out and the other soups to bring in that place.I know it is in AutoSoup but as AutoSoup always eats the Soup at a fixed health,so the Anticheat detects it

### ISSUE THREAD

**Issue by wurstisgood** [Wurst-Imperium/Wurst7#221]
it would be great if there was a hack that caused empty soup to drop out and the other soups to bring in that place.I know it is in AutoSoup but as AutoSoup always eats the Soup at a fixed health,so the Anticheat detects it

**Comment by GaiaB0t** [comment]
please follow format as to not make huge titles for issues

**Comment by Alexander01998** [comment]
AutoDrop can already drop empty soup bowls and AutoEat can already eat soup based on hunger.  It even says in the AutoSoup description that you should use AutoEat for that.
