### ISSUE TITLE
SneakWalk-Sneaks at Block Ends

### ISSUE THREAD

**Issue by wurstisgood** [Wurst-Imperium/Wurst7#222]
SneakWalk-Sneaks at Block Ends

**Comment by XfedeX** [comment]
So that would be a sort of safeWalk legit... Interesting.

**Comment by Alexander01998** [comment]
We have this as a SafeWalk setting as of [Wurst 7.15](https://www.wurstclient.net/updates/wurst-7-15/), and as of [Wurst 7.34](https://www.wurstclient.net/updates/wurst-7-34/) the sneaking distance can be customized too.
