### ISSUE TITLE
Color Manager? to change colour of Player Esp,GUI,search etc......

### ISSUE THREAD

**Issue by wurstisgood** [Wurst-Imperium/Wurst7#227]
Color Manager? to change colour of Player Esp,GUI,search etc......

**Comment by Alexander01998** [comment]
We kind of have this as of [Wurst 7.17](https://www.wurstclient.net/updates/wurst-7-17/). Should this issue be closed?

**Comment by TheGrandCurator** [comment]
> We kind of have this as of [Wurst 7.17](https://www.wurstclient.net/updates/wurst-7-17/). Should this issue be closed?

Yes.
