### ISSUE TITLE
Coordinates overlay

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/Wurst7#231]
For adventuring, its very annoying having to open my f3 menu every couple seconds and have my hacklist overlay be removed. if there could be an overlay that shows your coordinates without having to open f3 that would be really nice. (1.12 should also be supported with this)

**Comment by HappyNerd1** [comment]
actually @Alexander01998 , just make it easy and pull this over from Wolfram (its called "info" in wolfram)
