### ISSUE TITLE
Add not one block in Search

### ISSUE THREAD

**Issue by Yoticc** [Wurst-Imperium/Wurst7#240]
I propose to add a list of blocks that will be highlighted in the Search cheat module, as well as make it possible to change the color of the Cube of a certain block

**Comment by wurstisgood** [comment]
Just like color manager

**Comment by MrYotic** [comment]
> Just like color manager to change colour

Yes, just a little clearer

**Comment by wurstisgood** [comment]
> > Just like color manager to change colour
> 
> Yes, just a little clearer

yes rainbow colour is harder to see and also multiblocks for search needs different colours
