### ISSUE TITLE
ESP highlight color

### ISSUE THREAD

**Issue by Yoticc** [Wurst-Imperium/Wurst7#241]
Change highlight color for lines in ESP
for instance
If close then Light Blue If far away then blue, only full ARGB Spectrum

**Comment by wurstisgood** [comment]
it changes like for far it is green for near it is red @MrYotic

**Comment by MrYotic** [comment]
> it changes like for far it is green for near it is red @MrYotic

Yes, i change color in code, but not comfortabled

**Comment by wurstisgood** [comment]
> > it changes like for far it is green for near it is red @MrYotic
> 
> Yes, i change color in code, but not comfortabled

ohk
