### ISSUE TITLE
Escape not work for exit of menu Wurst options

### ISSUE THREAD

**Issue by Yoticc** [Wurst-Imperium/Wurst7#243]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
Not work ESC in menu

## Steps To Reproduce
1. Click ESC
2. Click Wurst options
3. Click Zoom
4. NOT WORK ECP TO LEAVE MENU

**Comment by MrYotic** [comment]
@Alexander01998 , I using 1.12. OF Wurst

**Comment by MrYotic** [comment]
https://youtu.be/ngnhWteJ0BU
