### ISSUE TITLE
Issue with X-Ray - can't add blocks

### ISSUE THREAD

**Issue by Justforfun07** [Wurst-Imperium/Wurst7#255]
Hey, need help with adding some blocks.

Everytime i want to add an block by name or id, it adding an "air-block" which i don't want.

Do someone know how I can add Blocks. Would be awesome and I would be thankful for some help! :)

Regards :)

P.S.: I use Wurst 7.6.2 Version, hope it helps :)

**Comment by Alexander01998** [comment]
You are using an outdated Wurst version. Please always update Wurst before making a bug report.
