### ISSUE TITLE
sit all and stand all tamed animals around you (and some other useful stuff)

### ISSUE THREAD

**Issue by K1TTY-K4T** [Wurst-Imperium/Wurst7#258]
.sitall and .standall should sit and stand all entities tamed by the player within distance so its not such a pain with like 20 puppies :>

edit: also .feedall/.healall to avoid accidental breeding when ur trying to heal big groups of tamed animals, and accidental sitting (so the animal doesnt get left behind) essentially using any held meat to heal all tamed animals around u to max health :) (im aware of feedaura but it feels faster to have a command)

one more edit: maybe adding a health bar option to see tamed animals health under healthtags (health is currently shown for a wolf based on how far up its tail is pointing)

**Comment by TheAwesome98-Real** [comment]
sitaura? lmao

**Comment by AndrewBruhMoment** [comment]
I will open a pull request soon, got the code for logic down, just need to implement the aura. I have no idea how to do that, so It could take me a long time.

Currently done:
Command to select an action (sit/stand/feed) and entity
Command Errors
