### ISSUE TITLE
Wrust weird bug while using baritone

### ISSUE THREAD

**Issue by rengarmazen** [Wurst-Imperium/Wurst7#259]
1. installing baritone with wrust following wrust instructions
2. trying to use baritone clickable commands
3. get system respond that only happens with wrust 
![Screenshot_1](https://user-images.githubusercontent.com/76734825/103283649-d2522480-49e1-11eb-8207-2092f923e22f.png)

**Comment by TheAwesome98-Real** [comment]
Already reported
