### ISSUE TITLE
Crafting Tables can show recipes

### ISSUE THREAD

**Issue by n18s** [Wurst-Imperium/Wurst7#260]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
What does it do and how is it useful? Please assume that we have never heard of it before. Just mentioning a name won't work. If it's for an older version of Minecraft (like 1.8 or 1.12), please mention that too.

When using a crafting table, and lets just assume that this feature is turned on, it can automatically fill out the recipe of the item without one having to use another third party mod or having to look it up. (maybe called auto-craft). This would be highly convenient and perfect for new users to Minecraft or just anybody who doesn't remember a recipe. I suppose it could be a UI that has a search bar and returns the item you are trying to craft based of the string or input the user types. (possibly implement this with a trie algorithm) This could just be one of the conceptual possibilities ways this could work. 

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the suggestion.

**Comment by n18s** [comment]
I suspect we can implement this with the search feature also. meaning we can have a search bar with all the items in the game.

**Comment by Alexander01998** [comment]
This already exists in vanilla Minecraft. https://minecraft.gamepedia.com/Recipe_book
