### ISSUE TITLE
Exit Code 0 with certain mods including Wurst

### ISSUE THREAD

**Issue by epicgamerbigboy** [Wurst-Imperium/Wurst7#262]
## Description
im not sure if this is the right issue to post this on because its not necessarily a bug. I have Optifabric, Optifine, Wurst, and Fabric, and the Fabric API in my mods folder, and whenever i click play on the fabric version on the MC launcher, it says Exit Code 0. i've already downloaded the latest JDK (JDK 15) and i've reinstalled Java, and ran Jarfix and it still wont open minecraft. I have also tried changing the minecraft launcher to Windows Vista and it still doesnt work. can anybody help?

Note: My minecraft and Wurst client was working perfectly fine yesterday, but today when i add Optifabric and Optifine it doesnt work. i also have restarted my computer many times.

I removed the Optifine and Optifabric and it loads up minecraft perfectly fine but i would like to know how to use Wurst with optifine/optifabric.

## Screenshots / Videos (Optional)
![big mans crash](https://user-images.githubusercontent.com/76847212/103443642-4b39c200-4c16-11eb-8647-80869b3c428d.PNG)

i didnt have the crash report file before but here it is: 
[Wurst with Optifine+fabric crash exit code 0.txt](https://github.com/Wurst-Imperium/Wurst7/files/5762225/Wurst.with.Optifine%2Bfabric.crash.exit.code.0.txt)

**Comment by epicgamerbigboy** [comment]
Hi, i think this is the correct Crash Report. 
[Wurst with Optifine+fabric crash exit code 0.txt](https://github.com/Wurst-Imperium/Wurst7/files/5762221/Wurst.with.Optifine%2Bfabric.crash.exit.code.0.txt)

**Comment by dadudeme** [comment]
i have the same problem when attempting to boot fabric using Wurst and Tweakeroo (Masady)
[crash-2021-03-22_17.48.07-client.txt](https://github.com/Wurst-Imperium/Wurst7/files/6215944/crash-2021-03-22_17.48.07-client.txt)
