### ISSUE TITLE
Jesus lava bug

### ISSUE THREAD

**Issue by DaysOfPeace** [Wurst-Imperium/Wurst7#263]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?
When jumping down into lava with jesus on it glitches out and doesnt let you escape and kills you. I have died to this multiple times now.
## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Put on jesus
2. Jump off of a high ledge
3. die in lava

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

(crash report goes here)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by XfedeX** [comment]
I am experiencing this bug too.

**Comment by ccuser44** [comment]
It's because when you fall from high distances jesus will not activate immediatly to avoid fall damage. But because it does not immediatly activate on lava the lava will start to do damage which pulls you down and preventing the use of jesus
