### ISSUE TITLE
Using OptiFabric renders X-RAY useless

### ISSUE THREAD

**Issue by ShreyasAyyengar** [Wurst-Imperium/Wurst7#267]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
Installed Optifabric (Jar Linked Below) with the latest version of wurst and fabric API makes X-Ray useless. It doesn't show any highlighted blocks. 

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Install wurst and Optifabric (https://www.curseforge.com/minecraft/mc-mods/optifabric)
2. Make sure both mods are loaded.
3. Enable X-Ray (it should not work)

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

<img width="1546" alt="Screenshot 2021-01-10 at 6 55 03 PM" src="https://user-images.githubusercontent.com/65931801/104120916-71c5ce80-5375-11eb-9bc1-36d248440b9d.png">

<img width="1691" alt="Screenshot 2021-01-10 at 6 55 15 PM" src="https://user-images.githubusercontent.com/65931801/104120904-64104900-5375-11eb-8701-004af5caa5b6.png">

**Comment by wb1016** [comment]
conflict with other mod doesnt conut as bug.
also, duplicate of #287

**Comment by holysnipz** [comment]
>Before posting, please make sure that this hasn't already been reported by someone else.

[can't even read. smh](https://github.com/Wurst-Imperium/Wurst7/issues?q=optifabric+xray)

**Comment by JamesTheAwesomeDude** [comment]
Yes, this is a duplicate of #174.

The creator of OptiFine [is _explicitly_ against co-operation](https://github.com/sp614x/optifine/issues/3482#issuecomment-593921599), and, given that it's closed-source, there's little hope of it being fixed any time soon.

For now, keep your eyes on #287, which has at least some hope of being enacted given that Sodium's open-source.
