### ISSUE TITLE
Buttons cut-off/drawn off screen

### ISSUE THREAD

**Issue by PigLicker** [Wurst-Imperium/Wurst7#273]
## Description
In the "Play Multiplayer" screen of minecraft where you select a server, Wurst adds some buttons which appear cut-off by the edge of the screen. 

## Steps To Reproduce
1.  Open minecraft
2.  Click the "Multiplayer" button

## Screenshots / Videos (Optional)
![2021-01-15_13 42 56](https://user-images.githubusercontent.com/44544348/104784804-ec0f9d80-573d-11eb-89c3-0e9fb95dfdc5.png)

This is in Wurst 7.9 ( minecraft 1.16.4 ), I have re-created this on two machines;
 1.  Windows 10 , Res: 1366x768 
 2.  Windows  7  , Res: 1920x1080

**Comment by Alexander01998** [comment]
This is a known issue when running Minecraft in a small window (e.g. 854x480), or when the "GUI Scale" option is set to "Auto".

There doesn't seem to be a better place to put these buttons. "GUI Scale: Auto" makes everything so big that these buttons just can't fit anywhere.

Wurst works best when the "GUI Scale" option is set to "Large" and the Minecraft window is maximized.

**Comment by DietrichPaul** [comment]
LabyMod fixed this issue by making a drop-down menu.
You could simply make a button in the bottom right-hand corner "..." and link to a screen containing all the tools for server lists, or just make a drop-down menu xd
![image](https://user-images.githubusercontent.com/64332690/137599558-094469f7-adb0-4165-b61b-6f66744637ff.png)

**Comment by DietrichPaul** [comment]
still a thing
