### ISSUE TITLE
Tooltips cut-off/drawn off screen

### ISSUE THREAD

**Issue by PigLicker** [Wurst-Imperium/Wurst7#274]
## Description
The tooltips for the cheat descriptions are sometimes drawn off the screen and the full description can not be read.  With some of the Cheats ( such as "AutoSoup" ) , even adjusting the mouse placement over the button will still not cause the full message to be drawn on-screen.

## Steps To Reproduce
1.  In-game, press right shift to open the cheats menu
2.  Hover mouse over the button for "AutoSoup", "BaseFinder", "BonemealAura", etc
3.  The cheat description is drawn off the screen, and adjusting mouse position elsewhere over the button doesn't cause it to be re-drawn where all the text is visible on-screen.

## Screenshots / Videos (Optional)
![2021-01-15_13 40 25](https://user-images.githubusercontent.com/44544348/104786307-70175480-5741-11eb-9a97-5157126093d2.png)

This is in Wurst 7.9 ( minecraft 1.16.4 ), I have re-created this on two machines;

1. Windows 10 , Res: 1366x768
2. Windows 7 , Res: 1920x1080

**Comment by Alexander01998** [comment]
"GUI Scale: Auto" breaks a lot of things. Some older versions of Wurst even disabled the "Auto" option to prevent this kind of stuff from happening. Maybe it would be a good idea to bring this feature back.
