### ISSUE TITLE
Camera descending while using freecam with sneak[legit]

### ISSUE THREAD

**Issue by MaxDerDeveloper** [Wurst-Imperium/Wurst7#275]
## Intro
Hey,
I have found a bug. It has appeared over the last few versions and the newest (7.10) too. I decided to report the bug, because it appeared to have stayed unnoticed for quite a while.

## The bug
When freecaming and the activating the sneak function in legit mode the camera starts moving downwards really quickly.

This bug doesn't appear in package mode. I guess thats because the legit mode simulates the press of the corresponding 'sneak'-button and the client therefore thinks the player intends to decend. 

## Possible fix
A distribution of the simulated keys and input methods of features like freecam, noclip, extraElytra which use some kind of flight control, would surely solve the issue and perhaps even some more unknown ones.

## Something else
Dear developer of the WurstClient, 
I kindly note I have been banned from the official subreddit permanently, which is in my oppinion very unfortunate.
As you see I am very much able to give constructive feedback as well as user experience, which might help you in your developing.
If you are thinking about unbanning me, my reddit username is the same one as here on github.
I am looking forward to contributing to your project as well as improving it.
Regards,
Max

**Comment by Alexander01998** [comment]
...you've been unbanned over a month ago.

**Comment by MaxDerDeveloper** [comment]
Oh, well thank you very much then.
