### ISSUE TITLE
Brightness Slider Broken

### ISSUE THREAD

**Issue by Dalethium** [Wurst-Imperium/Wurst7#277]
## Description
The brightness slider seems to be locked at 50%, if you slide it up or down, it still says +50%

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Install Wurst 1.16.5 v7.10, do not enable cheats, use a fully fresh clean install.
2. Logon to any server
3. Use brightness slider

## Screenshots / Videos (Optional)
![image](https://user-images.githubusercontent.com/22735418/104846318-e3d37180-58a7-11eb-8d52-c971834bb2d6.png)
![image](https://user-images.githubusercontent.com/22735418/104846321-e6ce6200-58a7-11eb-9858-779381d0c772.png)
![image](https://user-images.githubusercontent.com/22735418/104846323-eafa7f80-58a7-11eb-96d4-a3b82c504fb9.png)

**Comment by Alexander01998** [comment]
Fixed in 4cdaa12f694b1d97a8e4138e570c5dae44b08d98.
