### ISSUE TITLE
AFK timer

### ISSUE THREAD

**Issue by RandomAccountt** [Wurst-Imperium/Wurst7#280]
## Description
Currently, the anti-AFK constantly moves the player randomly, however, some plugins can detect this, and a mod on a server would be able to see this happening, and kick me. 

A solution would be to add a timer to the anti-AFK which only causes the player to move after set intervals. (For example, a server I play on kicks the player after 15 minutes of AFK. This means the Anti-AFK only needs to move once every 14 minutes to prevent me from being kicked). Please add a customisable time for the Anti-AFK to work :) thanks!

**Comment by Alexander01998** [comment]
Still relevant.
