### ISSUE TITLE
Colored HackList entries based on category

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [Wurst-Imperium/Wurst7#282]
## Description
Would it be possible to allow the user to "Categorize"  the various hacks into color/bold codes?

e.g. it would be really nice to know at-a-glance / instantly whether anything "invasive" or "game-modifying" is on, without being distracted by the many excellent UI tweaks that have no reason to even be disabled.

## Screenshots / Videos (Optional)
A mockup:

![2021-01-20_19 42 27](https://user-images.githubusercontent.com/2776014/105274707-f6c19c80-5b5a-11eb-8a32-9c235a7686f2.png)

**Comment by KTibow** [comment]
You could also categorize these into the ClickGUI categories.
