### ISSUE TITLE
Project cannot be imported

### ISSUE THREAD

**Issue by Brosweer** [Wurst-Imperium/Wurst7#284]
If I import existing gradle project, it write:
Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.3-bin.zip'.
A problem occurred configuring root project 'Wurst7'.
Failed to generate remap classpath
C:\Users\******\Documents\GitHub\Wurst7\.gradle\loom-cache\remapClasspath.txt line 0	Gradle Error

**Comment by wb1016** [comment]
but it works fine on my pc. cleaning all gradle cache may solve this.

**Comment by Brosweer** [comment]
Thank you, it worked.
