### ISSUE TITLE
Spoof more than just "Vanilla" client

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [Wurst-Imperium/Wurst7#285]
## Description
I don't know what the exact statitistics are (estimates range from an [unsourced 3.43% in 2016](https://hypixel.net/threads/what-percentage-of-players-use-optifine.678461/#post-6121799) to [>90% among PMC users last year](https://www.planetminecraft.com/forums/discussions/gaming/how-many-of-you-use-optifine-596322/)) for what percent of clients use at least some mods… but I can't shake the feeling that “I'm running _Mojang's Vanilla_, officer, honest! 🥺” is going to look a LOT more sus than “uhh yeah, check the logs. I've got OptiFine and JEI; who doesn't?”

**Comment by JamesTheAwesomeDude** [comment]
This complements #203 — if the Debug screen says it's got <this> mod set, but the server logs say they're running <that> client, that'd be a red flag

**Comment by Cyclopropinon** [comment]
imo this feature is worth looking into
maybe even with custom user agent string
