### ISSUE TITLE
SeedCracker × Wurst

### ISSUE THREAD

**Issue by AndrewBruhMoment** [Wurst-Imperium/Wurst7#290]
## Description
SeedCracker is a standalone fabric mod with an MIT license that as the name suggests, cracks the seed of a given world. The mod has functionality for prior versions built in, and is compatable with versions up to 1.16.4. The mod uses bridgader to make a command that can select the version, game features to use in the cracking process, what overlays to render, and to enable the cracker. When the cracking process is completed the seed is sent to the player, and not stored There are different cracking methods and objects for different versions, so the version selecter must be kept in, or replaced with an automatic version.

This would optimaly be made as a command and gui hack. The version and object selecors should be in the gui, while the cracker enabling would be replaced by the enabling of the hack.

The command should be used to obtain the seed, even after it is originaly cracked and sent to the player.

**Comment by Alexander01998** [comment]
We seem to have multiple issues about this topic. Let's track it in https://github.com/Wurst-Imperium/Wurst7/issues/860 from now.
