### ISSUE TITLE
ColorSetting

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/Wurst7#292]
## Description
>What does it do and how is it useful? Please assume that we have never heard of it before. Just mentioning a name won't work. If it's for an older version of Minecraft (like 1.8 or 1.12), please mention that too.

Wurst needs a color selector in addition to the sliders, checkboxes, etc. that it already has. This would allow users to change ESP colors and would compact the ClickGUI settings (which currently has six sliders for all the RGB values).

## Screenshots / Videos (Optional)
>If applicable, add screenshots, videos or other files to help explain the suggestion.

Here is a sketch of what ColorSetting could look like:

![ColorSetting sketch](https://user-images.githubusercontent.com/10100202/106121874-566e0800-6158-11eb-8088-82e042afc5f0.png)

Clicking on the box with the color would open a screen that lets you edit the color (similar to ctrl-clicking on a slider). There would be a text field where you can type in the hex code, and maybe also three sliders for the red, green and blue values. There should also be another box displaying the color, so you can preview your changes before closing the screen.

**Comment by Alexander01998** [comment]
Does anybody want to make a Pull Request for this?

**Comment by hiddenalt-team** [comment]
I made the basic color selection setting in the upcoming pull request #455. 
Recently realized that one hex input field is a bit more convenient than three RGB fields. However, I've already opened the pull request. May be I'll try to add hex field next time.
