### ISSUE TITLE
Legit Nuker Fix, v7.12

### ISSUE THREAD

**Issue by mokinys98** [Wurst-Imperium/Wurst7#296]
## Description

Add smooth camera move to other block not teleport. Its clearly that you use hacks if you teleport

Add function check to finish mining the block before starting new one. (its very clear when mining hard blocks like obsidian, and new obsidian appears then legit nuker moves to new obsidian because its closer ) 

## Screenshots / Videos (Optional)

--

**Comment by XfedeX** [comment]
And add nukerlegit priority "angle" option, this would make it much more legit : looks suspect if you turn by 180 degrees every block break!
