### ISSUE TITLE
microsoft accounts support for the alt manager

### ISSUE THREAD

**Issue by MrGeorgen** [Wurst-Imperium/Wurst7#301]
With the upcoming conversion from mojang to microsoft accounts, it would be required to add microsoft account support to the alt manger. Otherwise the alt manager would be useless expect for cracked accounts

**Comment by SnooComics9452** [comment]
we need this

**Comment by Alexander01998** [comment]
What I don't understand is:
![image](https://user-images.githubusercontent.com/10100202/156623217-4dc965ee-da4c-41de-bb72-9d93030d50ab.png)

1. The wiki says `client_secret` is required but [every](https://github.com/MeteorDevelopment/meteor-client/commit/718b147b256eb08c29d9f14bb9567a95123e6577) [example](https://github.com/MiniDigger/MiniLauncher/blob/master/launcher/src/main/java/me/minidigger/minecraftlauncher/launcher/gui/MsaFragmentController.java) I've seen seems to get away without one.

2. Am I supposed to set up an entire server just so people can login to their Microsoft accounts? [This implementation](https://github.com/MeteorDevelopment/meteor-client/commit/718b147b256eb08c29d9f14bb9567a95123e6577) runs a local server (somehow without leaking secrets), while [this one](https://github.com/MiniDigger/MiniLauncher/blob/master/launcher/src/main/java/me/minidigger/minecraftlauncher/launcher/gui/MsaFragmentController.java) seems to bypass the server requirement entirely.

Is the wiki just wrong about this step?

**Comment by Cach30verfl0w** [comment]
If you can do it without the secret, then you could do it without the secret. So if it works there, then I don't see a problem.

**Comment by EliteUn17y** [comment]
> What I don't understand is: ![image](https://user-images.githubusercontent.com/10100202/156623217-4dc965ee-da4c-41de-bb72-9d93030d50ab.png)
> 
>     1. The wiki says `client_secret` is required but [every](https://github.com/MeteorDevelopment/meteor-client/commit/718b147b256eb08c29d9f14bb9567a95123e6577) [example](https://github.com/MiniDigger/MiniLauncher/blob/master/launcher/src/main/java/me/minidigger/minecraftlauncher/launcher/gui/MsaFragmentController.java) I've seen seems to get away without one.
> 
>     2. Am I supposed to set up an entire server just so people can login to their Microsoft accounts? [This implementation](https://github.com/MeteorDevelopment/meteor-client/commit/718b147b256eb08c29d9f14bb9567a95123e6577) runs a local server (somehow without leaking secrets), while [this one](https://github.com/MiniDigger/MiniLauncher/blob/master/launcher/src/main/java/me/minidigger/minecraftlauncher/launcher/gui/MsaFragmentController.java) seems to bypass the server requirement entirely.
> 
> 
> Is the wiki just wrong about this step?

1. The wiki is wrong, I think.
2. No.

**Comment by EliteUn17y** [comment]
I'll try and make a pull request. No promises though.

**Comment by EliteUn17y** [comment]
Update: got it working. Will refactor to make it selectable between mojang and microsoft.

**Comment by EliteUn17y** [comment]
Done. Check PR #590.

**Comment by Alexander01998** [comment]
Microsoft account support has been implemented and will be released in Wurst 7.22.
