### ISSUE TITLE
Add to ExtraElytra: Glide without elytra

### ISSUE THREAD

**Issue by throwaway-31415926535** [Wurst-Imperium/Wurst7#308]
I've only tested this in 1.16.4 on vanilla servers, so take this with a grain of salt.
If you tell the server to start an elytra glide, on some servers, even if you have no elytra equipped, it makes you start gliding!

I can do it with:
`MinecraftClient.getInstance().player.startFallFlying();`

That's literally it.

**Comment by nofh428** [comment]
Hey @throwaway-31415926535 May I ask where in the code we are meant to put this thanks in advance.
