### ISSUE TITLE
A different Freecam 

### ISSUE THREAD

**Issue by Markg546** [Wurst-Imperium/Wurst7#311]
## Description
A modification to the current freecam code to make it work with baritone commands.
The current issue is that it tries to move the freecam instead of the actual player.
basically suggesting freecam would create a new render view entity while leaving mc.player as the real player.

Possible useful doc: https://github.com/ImpactDevelopment/ImpactIssues/issues/912

## Screenshots / Videos (Optional)
https://www.youtube.com/watch?v=CBTePJzY5WM

**Comment by Cyclopropinon** [comment]
also when it ceates the render entity the movement would be probably like in spectatormode and not affected by terrain

also pls change the shaders (fog) while being in a liquid
