### ISSUE TITLE
Autoeat fails when using Autotool and excavator

### ISSUE THREAD

**Issue by tylerroost** [Wurst-Imperium/Wurst7#316]
Other posts indicate that offhand eating may help this problem, but there has not been any explicit indication of this specific problem

## Description
When using excavator and autotool in survival autoeat will trigger and force a back and forth switching between the suitable tool and the food, effectively diminishing the effect of the mining and causing food to not be eaten.

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1.  Enable excavator on a large enough area where you will get hungry while mining
2.  Enable autotool and autoeat with the appropriate tools and food in hotbar
3.  Let excavator run until food diminishes

**Comment by diaoes** [comment]
you can open right's shift Gui. than can work!
i don't how to work,but it can work!

**Comment by AndrewBruhMoment** [comment]
This could be fixed by putting a check in autotool to stop switching when autoeat is triggered or eating starts.

**Comment by Alexander01998** [comment]
> This could be fixed by putting a check in autotool to stop switching when autoeat is triggered or eating starts.

Not if Excavator is running at the same time, then it would try to mine with food...
