### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ShadowMob** [Wurst-Imperium/Wurst7#322]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?
Joining a world/server crashes immediately
## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Go into fullbright  
2.  Change gamma to night vision
3. It crashes and wont be able to rejoin any world or server

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

---- Minecraft Crash Report ----
// Don't do that.

Time: 2/23/21 1:24 PM
Description: Firing Wurst event

java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/networking/CustomPayloadC2SPacketAccessor
	at net.wurstclient.other_features.VanillaSpoofOtf.onSentConnectionPacket(VanillaSpoofOtf.java:48)
	at net.wurstclient.events.ConnectionPacketOutputListener$ConnectionPacketOutputEvent.fire(ConnectionPacketOutputListener.java:56)
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_2535.localvar$zea000$onSendPacket(class_2535.java:554)
	at net.minecraft.class_2535.method_10752(class_2535.java)
	at net.minecraft.class_2535.method_10743(class_2535.java:165)
	at net.minecraft.class_634.method_2883(class_634.java:834)
	at com.mamiyaotaru.voxelmap.VoxelMap.onTick(VoxelMap.java:219)
	at com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMap.clientTick(FabricModVoxelMap.java:66)
	at net.minecraft.class_310.handler$zio003$onTick(class_310.java:5363)
	at net.minecraft.class_310.method_1574(class_310.java:1612)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.wurstclient.other_features.VanillaSpoofOtf.onSentConnectionPacket(VanillaSpoofOtf.java:48)
	at net.wurstclient.events.ConnectionPacketOutputListener$ConnectionPacketOutputEvent.fire(ConnectionPacketOutputListener.java:56)

-- Affected event --
Details:
	Event class: net.wurstclient.events.ConnectionPacketOutputListener$ConnectionPacketOutputEvent
Stacktrace:
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_2535.localvar$zea000$onSendPacket(class_2535.java:554)
	at net.minecraft.class_2535.method_10752(class_2535.java)
	at net.minecraft.class_2535.method_10743(class_2535.java:165)
	at net.minecraft.class_634.method_2883(class_634.java:834)
	at com.mamiyaotaru.voxelmap.VoxelMap.onTick(VoxelMap.java:219)
	at com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMap.clientTick(FabricModVoxelMap.java:66)
	at net.minecraft.class_310.handler$zio003$onTick(class_310.java:5363)

-- Affected level --
Details:
	All players: 46 total; [class_746['JMob'/1733, l='ClientLevel', x=9.78, y=44.50, z=94.21], class_745['DNA_Robert'/1693, l='ClientLevel', x=-15.20, y=45.95, z=116.60], class_745['sadboyclub'/1483, l='ClientLevel', x=9.86, y=44.00, z=93.18], class_745['sakkura_'/1621, l='ClientLevel', x=9.64, y=44.00, z=92.63], class_745['Emily_The_Demon'/1521, l='ClientLevel', x=13.84, y=43.00, z=95.88], class_745['xoidtv'/1596, l='ClientLevel', x=9.89, y=44.00, z=91.82], class_745['EDSZA'/1689, l='ClientLevel', x=10.42, y=44.00, z=92.46], class_745['sad_doggo2008'/1668, l='ClientLevel', x=10.43, y=44.00, z=93.55], class_745['Kraken12112'/1620, l='ClientLevel', x=8.08, y=44.00, z=92.71], class_745['Dylonjuly4'/1641, l='ClientLevel', x=7.63, y=44.00, z=91.86], class_745['TryHardin69'/1624, l='ClientLevel', x=5.70, y=43.00, z=89.45], class_745['TheLostDragon14'/1632, l='ClientLevel', x=9.80, y=44.00, z=94.38], class_745['knorr_knol'/1654, l='ClientLevel', x=8.16, y=44.00, z=94.34], class_745['Noa_Lovegood'/1695, l='ClientLevel', x=10.48, y=44.00, z=92.35], class_745['DjDisaster'/1684, l='ClientLevel', x=9.64, y=44.00, z=93.52], class_745['BartSupreme'/1706, l='ClientLevel', x=8.83, y=44.50, z=93.23], class_745['NITAY07'/1707, l='ClientLevel', x=8.08, y=44.00, z=93.09], class_745['Powderday1'/1709, l='ClientLevel', x=10.42, y=44.33, z=93.16], class_745['TheCitrusDemon'/1710, l='ClientLevel', x=5.35, y=43.67, z=92.97], class_745['thebeesonly'/1712, l='ClientLevel', x=9.11, y=44.00, z=92.90], class_745['PlupMream'/1713, l='ClientLevel', x=10.47, y=44.00, z=96.33], class_745['AL13000'/1731, l='ClientLevel', x=7.62, y=44.50, z=91.56], class_745['Schlem09'/1715, l='ClientLevel', x=9.12, y=43.00, z=96.26], class_745['Sonicci_'/1716, l='ClientLevel', x=10.31, y=44.01, z=92.09], class_745['Wilhelm_609'/1723, l='ClientLevel', x=10.35, y=44.28, z=92.96], class_745['ilanjordan'/1718, l='ClientLevel', x=7.35, y=43.36, z=97.80], class_745['Himmi_xD'/1720, l='ClientLevel', x=8.17, y=44.50, z=94.20], class_745['Noxiken'/1721, l='ClientLevel', x=9.27, y=44.50, z=93.00], class_745['Dedewdz2'/1722, l='ClientLevel', x=8.23, y=44.33, z=93.70], class_745['Wojtyla101'/1725, l='ClientLevel', x=7.63, y=44.50, z=92.04], class_745['DonutSmurf2'/1726, l='ClientLevel', x=10.27, y=44.34, z=94.35], class_745['2945'/1727, l='ClientLevel', x=9.44, y=44.50, z=92.62], class_745['LemonsGirl'/1728, l='ClientLevel', x=8.99, y=44.33, z=92.72], class_745['Xunliz'/1729, l='ClientLevel', x=9.17, y=44.33, z=92.49], class_745['Antxsi'/1730, l='ClientLevel', x=9.08, y=44.33, z=94.03], class_745['RyanTheMaster16'/1732, l='ClientLevel', x=9.35, y=44.33, z=93.65], class_745['xXStarVoidXx'/1675, l='ClientLevel', x=9.13, y=43.00, z=98.69], class_745['T1mS__'/1708, l='ClientLevel', x=9.59, y=43.33, z=112.76], class_745['hamburger2506'/1717, l='ClientLevel', x=8.98, y=43.00, z=103.54], class_745['B4bles'/1678, l='ClientLevel', x=8.50, y=44.34, z=110.84], class_745['Astornawt'/1441, l='ClientLevel', x=55.38, y=43.00, z=100.05], class_745['softfries'/1734, l='ClientLevel', x=10.25, y=44.50, z=93.51], class_745['IncogniToby'/1735, l='ClientLevel', x=8.73, y=44.33, z=93.34], class_745['Gurkman1'/1736, l='ClientLevel', x=7.82, y=44.33, z=93.86], class_745['Quakey_TY'/1737, l='ClientLevel', x=9.06, y=44.50, z=94.13], class_745['Albertoooooo926'/1738, l='ClientLevel', x=8.35, y=44.50, z=92.91]]
	Chunk stats: Client Chunk Cache: 729, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (241,35,-53), Chunk: (at 1,2,11 in 15,-4; contains blocks 240,0,-64 to 255,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 25278 game time, 792000 day time
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:802a7c9:unknown) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2825850648 bytes (2694 MB) / 3758096384 bytes (3584 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.29.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		minecraft: Minecraft 1.16.4
		voxelmap: VoxelMap 1.10.14
		wurst: Wurst Client v7.12-MC1.16.4
	Launched Version: fabric-loader-0.10.8-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.23, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by ThisTestUser** [comment]
Turn off VanillaSpoof. I think Alexander should wrap a try-catch block around onSentConnectionPacket() as it sometimes throws errors like this.

**Comment by Alexander01998** [comment]
Try this: [Wurst-Client-v7.12.1-MC1.16.5.zip](https://github.com/Wurst-Imperium/Wurst7/files/6035781/Wurst-Client-v7.12.1-MC1.16.5.zip)

**Comment by Alexander01998** [comment]
Oh, I think I see what's going on here. There are two different `CustomPayloadC2SPacketAccessor`s depending on which Fabric API version you use.

Older versions use `net.fabricmc.fabric.impl.networking.CustomPayloadC2SPacketAccessor` while newer versions use `net.fabricmc.fabric.mixin.networking.accessor.CustomPayloadC2SPacketAccessor`.

**Comment by ShadowMob** [comment]
How can i turn off VanillaSpoof if i cannot join a game? Is there a way to
access the source in wurst to manually turn it off?

**Comment by ShadowMob** [comment]
I went and installed the latest fabric api version and it still crashes
Here is the Crash Report from with that new api

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2/24/21 9:18 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
at
com.mamiyaotaru.voxelmap.Map.calculateCurrentLightAndSkyColor(Map.java:961)
at com.mamiyaotaru.voxelmap.Map.onTickInGame(Map.java:703)
at com.mamiyaotaru.voxelmap.VoxelMap.onTickInGame(VoxelMap.java:189)
at
com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMap.renderOverlay(FabricModVoxelMap.java:74)
at
net.minecraft.class_329.handler$zja000$onRenderGameOverlay(class_329.java:2331)
at net.minecraft.class_329.method_1753(class_329.java:378)
at net.minecraft.class_757.method_3192(class_757.java:597)
at net.minecraft.class_310.method_1523(class_310.java:1048)
at net.minecraft.class_310.method_1514(class_310.java:681)
at net.minecraft.client.main.Main.main(Main.java:215)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is
as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
at
com.mamiyaotaru.voxelmap.Map.calculateCurrentLightAndSkyColor(Map.java:961)
at com.mamiyaotaru.voxelmap.Map.onTickInGame(Map.java:703)
at com.mamiyaotaru.voxelmap.VoxelMap.onTickInGame(VoxelMap.java:189)
at
com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMap.renderOverlay(FabricModVoxelMap.java:74)
at
net.minecraft.class_329.handler$zja000$onRenderGameOverlay(class_329.java:2331)
at net.minecraft.class_329.method_1753(class_329.java:378)

-- Affected level --
Details:
All players: 29 total; [class_746['JMob'/3396, l='ClientLevel', x=8.07,
y=44.00, z=93.81], class_745['VictorEfraimsson'/3277, l='ClientLevel',
x=-18.18, y=45.18, z=116.66], class_745['StallionG'/2458, l='ClientLevel',
x=10.14, y=44.00, z=92.65], class_745['D7LLAN'/1329, l='ClientLevel',
x=8.58, y=44.50, z=92.24], class_745['chaukau'/1334, l='ClientLevel',
x=7.87, y=44.00, z=92.18], class_745['Vast20'/1330, l='ClientLevel',
x=7.52, y=44.00, z=93.17], class_745['Bankeasy'/2466, l='ClientLevel',
x=9.07, y=44.00, z=93.26], class_745['nx_ana'/3251, l='ClientLevel',
x=10.12, y=44.00, z=94.09], class_745['ECLIPSEFOREST'/3344,
l='ClientLevel', x=10.18, y=44.00, z=94.23], class_745['Mrthedogg'/3360,
l='ClientLevel', x=9.02, y=44.00, z=91.57], class_745['plasmakid'/3385,
l='ClientLevel', x=8.81, y=44.50, z=91.98], class_745['T0X1X_FOX'/3392,
l='ClientLevel', x=8.04, y=44.00, z=92.29],
class_745['TertialWind3285'/3387, l='ClientLevel', x=13.97, y=43.00,
z=96.16], class_745['salmon_23'/3388, l='ClientLevel', x=11.00, y=43.00,
z=98.93], class_745['PeachyClouds151'/3389, l='ClientLevel', x=10.16,
y=44.00, z=93.97], class_745['ploncho'/3390, l='ClientLevel', x=9.79,
y=44.50, z=91.57], class_745['Barneyminer'/3391, l='ClientLevel', x=7.98,
y=44.00, z=91.91], class_745['artoo007'/3393, l='ClientLevel', x=8.90,
y=44.00, z=94.22], class_745['orgiboy1'/3394, l='ClientLevel', x=9.55,
y=43.00, z=99.08], class_745['itsjustpeter2'/3395, l='ClientLevel',
x=10.11, y=44.50, z=92.49], class_745['IdaBachNielsen'/2808,
l='ClientLevel', x=15.65, y=50.00, z=123.30],
class_745['Albagamer365'/3378, l='ClientLevel', x=-0.11, y=44.00,
z=121.70], class_745['xoHybridHxo'/3358, l='ClientLevel', x=27.11, y=44.00,
z=70.69], class_745['TeamErnst'/3397, l='ClientLevel', x=8.11, y=44.00,
z=91.85], class_745['CaptainCole789'/3398, l='ClientLevel', x=8.85,
y=44.00, z=94.69], class_745['Blacka_Soldier'/3399, l='ClientLevel',
x=7.56, y=44.50, z=91.83], class_745['IWOLFY7'/3400, l='ClientLevel',
x=7.18, y=44.00, z=94.99], class_745['Mine_Cast'/3401, l='ClientLevel',
x=9.35, y=44.50, z=93.06], class_745['StonksNR'/3402, l='ClientLevel',
x=7.60, y=44.50, z=91.68]]
Chunk stats: Client Chunk Cache: 729, 529
Level dimension: minecraft:overworld
Level spawn location: World: (241,35,-53), Chunk: (at 1,2,11 in 15,-4;
contains blocks 240,0,-64 to 255,255,-49), Region: (0,-1; contains chunks
0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Level time: 176384 game time, 792000 day time
Server brand: BungeeCord
(git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:802a7c9:unknown) <- Paper
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.class_638.method_8538(class_638.java:449)
at net.minecraft.class_310.method_1587(class_310.java:2239)
at net.minecraft.class_310.method_1514(class_310.java:704)
at net.minecraft.client.main.Main.main(Main.java:215)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
Minecraft Version: 1.16.5
Minecraft Version ID: 1.16.5
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
Corporation
Memory: 693642448 bytes (661 MB) / 1711276032 bytes (1632 MB) up to
2147483648 bytes (2048 MB)
CPUs: 8
JVM Flags: 9 total;
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC
-XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50
-XX:G1HeapRegionSize=32M
Fabric Mods:
fabric: Fabric API 0.29.3+1.16
fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1)
1.1.4+6a2618f53a
fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
fabric-content-registries-v0: Fabric Content Registries (v0)
0.2.0+e77439c73a
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
fabric-events-interaction-v0: Fabric Events Interaction (v0)
0.4.1+6a2618f53a
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0)
0.2.7+a03e98793a
fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
fabric-object-builder-api-v1: Fabric Object Builder API (v1)
1.9.2+6a2618f53a
fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
fabric-renderer-registries-v1: Fabric Renderer Registries (v1)
2.2.0+6a2618f53a
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1)
0.1.4+6a2618f53a
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1)
1.1.0+6a2618f53a
fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1)
1.2.5+6a2618f53a
fabricloader: Fabric Loader 0.11.1
java: Java HotSpot(TM) 64-Bit Server VM 8
minecraft: Minecraft 1.16.5
phosphor: Phosphor 0.6.0+build.7
voxelmap: VoxelMap 1.10.14
wurst: Wurst Client v7.12.1-MC1.16.5
Launched Version: fabric-loader-0.11.1-1.16.5
Backend library: LWJGL version 3.2.2 build 10
Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.23,
NVIDIA Corporation
GL Caps: Using framebuffer using OpenGL 3.0
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
Graphics mode: fancy
Resource Packs: Fabric Mods
Current Language: English (US)
CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

**Comment by Alexander01998** [comment]
> How can i turn off VanillaSpoof if i cannot join a game?

You can turn it off in a singleplayer world.

> Is there a way to access the source in wurst to manually turn it off?

Yes. You can edit the file at `%appdata%/.minecraft/wurst/settings.json`. However, turning it off in a singleplayer world should be easier.

> I went and installed the latest fabric api version and it still crashes Here is the Crash Report from with that new api

This seems to be a different issue that is caused by VoxelMap rather than Wurst.

It looks like you are still using VoxelMap for Minecraft 1.16.4, even though your Minecraft version is now set to 1.16.5. Try updating VoxelMap to version 1.10.15. If that doesn't help, try launching the game without VoxelMap.
