### ISSUE TITLE
FastBow hack?

### ISSUE THREAD

**Issue by SirEnder125** [Wurst-Imperium/Wurst7#324]
## Description
This would be very useful along with Trajectories to spam a bow quickly. :)

Please consider this suggestion.

(Sorry if this has already been suggested.)

**Comment by XfedeX** [comment]
Yes Wurst **really** needs fast bow!

**Comment by Alexander01998** [comment]
This only works in Minecraft 1.8.x. Wurst 6 already has this feature.
