### ISSUE TITLE
KillauraLegit faceEntityClient should check in Optional<> container, not nullity

### ISSUE THREAD

**Issue by PeriodicSeizures** [Wurst-Imperium/Wurst7#327]
## Description
The player will still hit the entity, even though they are behind them.

## Steps To Reproduce
1. Uncheck the correct filter for the entity being tested
2. Enable KillauraLegit, and have someone place an entity a few blocks behind player, or spawn an entity just outside of the aura range, and then face the opposite direction.
3. The entity will be hit although it is never aimed at.

## Fix
In KillauraLegit.java, in faceEntityClient() around ~line 272, the Object returned by bb.raycast will always be nonnull, since it is acting as a container for a possibly null Object. Replacing:
```
// if not facing center, check if facing anything in boundingBox
return bb.raycast(eyesPos,
      eyesPos.add(lookVec.multiply(range.getValue()))) != null;
```
with:
```
// if not facing center, check if facing anything in boundingBox
return bb.raycast(eyesPos,
      eyesPos.add(lookVec.multiply(range.getValue()))).isPresent(); // added isPresent()
```
should make the difference.

**Comment by Alexander01998** [comment]
Can confirm. This was likely broken by a Minecraft update at some point.
`Box.raycast()` used to return a nullable `RayTraceResult` in 1.12. Not sure when exactly this was changed to an `Optional`.
