### ISSUE TITLE
Mod Menu is missing

### ISSUE THREAD

**Issue by arso7** [Wurst-Imperium/Wurst7#328]
Mod Menu Button is missing and glitch out in Wurst

Mod Menu v1.16.8 for 1.16.5
Wurst 7.12.1

Screenshots

no wurst
https://imgur.com/rUB979m
wurst
https://imgur.com/QMXWrpE

no wurst
https://imgur.com/e9B0KV2
wurst
https://imgur.com/82pQjYl

**Comment by MobESP** [comment]
Maybe try re-dowloading wurst? You or something else might have deleted some JS code or a texture file.

**Comment by Alexander01998** [comment]
Fixed in ce4286e02c1b4a7ddc91ad9f438f263ddcf199dc and 9aff6c81bb33ac1555b5930c801aa62a1fac2b42.
