### ISSUE TITLE
Add "Ignore world barrier"

### ISSUE THREAD

**Issue by MaslovKK** [Wurst-Imperium/Wurst7#329]
**This function must be ignoring the barrier (placing blocks, use). Version 1.8 or above. 
honestly, idk does it work on the clientside.**

**Comment by JamesTheAwesomeDude** [comment]
What other clients, if any, have this feature?

**Comment by MaslovKK** [comment]
Idk

сб, 20 мар. 2021 г., 23:35 James ***@***.***>:
