### ISSUE TITLE
Excavator update?

### ISSUE THREAD

**Issue by mkymcg** [Wurst-Imperium/Wurst7#330]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
I was wondering if there is a way to have excavator mine layer by layer this would make it much smoother as my player just gets stuck in a hole it dug itself and stays there jumping and mining trying to get out

**Comment by Alexander01998** [comment]
> I was wondering if there is a way to have excavator mine layer by layer

Excavator already does that.
