### ISSUE TITLE
Slider Help?

### ISSUE THREAD

**Issue by XfedeX** [Wurst-Imperium/Wurst7#332]
`SliderSetting("ExampleSlider",
			"Example Slider.\n" + "Just an example!",
			exampleval1, exampleval2, exampleval3, exampleval4, <etc.>`
This is an example slider code.
I understood that exampleval3 is the max slider value.
What is exampleva1 and 2 and 4?
Thanks.

**Comment by faseri** [comment]
Daym dude just open SliderSetting class definition
wurstclient.settings.slidersetting.java
Why are you dumb?
