### ISSUE TITLE
[Feature request] AutoFish off-hand

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [Wurst-Imperium/Wurst7#340]
## Description
Could you allow AutoFish to use the off-hand? It would allow some serious multi-tasking, such as throwing fish on a campfire as they're caught, eating food, etc.

**Comment by AndrewBruhMoment** [comment]
Lines 304 - 312 of AutoFishHack might help with this.

**Comment by JamesTheAwesomeDude** [comment]
this + a "GrillAura" thaut automatically campfires any eligible food in the hotbar would be very cool

**Comment by Alexander01998** [comment]
Hey @JamesTheAwesomeDude! Great news - I've added off-hand support for AutoFish in commit 15ce5ab8c8d8b4434d8e38631d7cdeb5087ae7e8. It'll be included in the upcoming Wurst 7.35 release. 🎣

Please note that AutoFish will still have to move the fishing rod to your main hand before casting. This is necessary to avoid some weird edge cases when you have a different item in your main hand that takes priority over the fishing rod.
