### ISSUE TITLE
add surround

### ISSUE THREAD

**Issue by feliscatusmeows** [Wurst-Imperium/Wurst7#342]
## Description
Surround automatically surrounds your feet with obsidian or another blast-proof block. It is used to avoid getting killed by a end crystal because explosions are calculated using the player's lower hitbox. 

## Screenshots / Videos (Optional)

![image](https://user-images.githubusercontent.com/29553771/111734741-f03c6200-8837-11eb-9eeb-0b6a2f7de98a.png)
It should do something like this, but quickly and automatically.

**Comment by BleachDrinker420** [comment]
wurst crystal pvp moment

**Comment by feliscatusmeows** [comment]
> wurst crystal pvp moment

Wurst has .taco, which is the most overpowered part of the wurst client. Not even bleachhack can match the power of the .taco. :sunglasses:

**Comment by feliscatusmeows** [comment]
Bump.
Super duper important to not dying by end crystal
Maybe to save blocks it could try to auto-center the player. Also could replace blocks as opponent breaks your surrounding protection.
