### ISSUE TITLE
[Enhancement] AltManager: thealtening.com token support

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [Wurst-Imperium/Wurst7#344]
## Description
One of the biggest Minecraft alt websites, [The Altening](https://thealtening.com), has their own API for dispensing user account tokens for so-called "Non-Full Access" (NFA) accounts. It [looks like](https://github.com/TheAltening/TheAlteningAuth4j) it's pretty simple to implement (it seems their HTTP API is identical to Mojang's), and Impact has had this [since November 2019](https://github.com/ImpactDevelopment/ImpactIssues/issues/1832).

**Comment by Alexander01998** [comment]
There is an unofficial version that does this: https://github.com/Wurst-Imperium/Wurst7/pull/113

**Comment by ccuser44** [comment]
Thealtening dupport eould be great

**Comment by Alexander01998** [comment]
There seems to be a lot of demand for this feature on the forum: https://wurstforum.net/d/6-feature-that-allows-you-to-use-premium-accounts-from-the-altening

**Comment by ccuser44** [comment]
I would use this too rather than thealtening launcher directly

The impact client has had this for quite some time already.
