### ISSUE TITLE
Add InventoryMove

### ISSUE THREAD

**Issue by Pabsb** [Wurst-Imperium/Wurst7#346]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
What does it do and how is it useful? Please assume that we have never heard of it before. Just mentioning a name won't work. If it's for an older version of Minecraft (like 1.8 or 1.12), please mention that too.
InventoryMove. Move around while you have any type of inventory or clickgui open. For every version of Minecraft

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the suggestion.

**Comment by Alexander01998** [comment]
Already added. It's called InvWalk.

**Comment by Pabsb** [comment]
@Alexander01998 Then its not in the latest version of Wurst because Searching it doesn't show up and neither trying to toggle it
