### ISSUE TITLE
Entity speed and control hack

### ISSUE THREAD

**Issue by Dragonlord1005** [Wurst-Imperium/Wurst7#353]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
What does it do and how is it useful? Please assume that we have never heard of it before. Just mentioning a name won't work. If it's for an older version of Minecraft (like 1.8 or 1.12), please mention that too.
Entity control hacks, say if your riding a horse you don't own, you can still control it, while also being able to modify its speed
## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the suggestion.

**Comment by AndrewBruhMoment** [comment]
Do you mean riding a horse without a saddle, because you can ride horses that you don't own with a saddle?
