### ISSUE TITLE
FOV slider on Killaura

### ISSUE THREAD

**Issue by Lamby777** [Wurst-Imperium/Wurst7#355]
Also like my last issue, another small feature that I really miss on this mod is the FOV slider on Killaura.

The placeholder says that I need to explain it as if you don't know what it is, so:
Basically it limits your KA hits to the FOV you specified. 360 means default (a sphere around you), 180 means anyone in front of you, and 60 means a small cone pointing out from your camera. Anything in between is self-explanatory.

**Comment by XfedeX** [comment]
@Lamby777 I already made a thing like this for myself, I will maybe later make a pull request.

**Comment by AndrewBruhMoment** [comment]
@XfedeX Please do, it sounds wonderful!

**Comment by Lamby777** [comment]
Oh, I forgot to mention, the old Killaura also had a "through walls" checkbox that you could disable. Is there any way to do that in the current version that I don't know of?

**Comment by nofh428** [comment]
@XfedeX yes that would be amazing

**Comment by Alexander01998** [comment]
Added in b780aed1f030481ef571413c68984170055b7e81.
