### ISSUE TITLE
Okay so im just kinda dumb how do you wrap the source code

### ISSUE THREAD

**Issue by Blakechez** [Wurst-Imperium/Wurst7#356]
Im not smart at all but how do you wrap the source code into a jar file? i made a fork of this so i can make .enchant do a 32k instead of 127 because im power hungry but im not smart enough to wrap it into a jar file

**Comment by Blakechez** [comment]
figured it out

**Comment by AndrewBruhMoment** [comment]
I know this is solved, but I'm still putting it here anyway if anyone else doesn't know.

`./gradlew build`
if it doesn't work remove `./`

Then check build > libs
The mod should be the jar with a plain name.
