### ISSUE TITLE
New hack

### ISSUE THREAD

**Issue by NMPCVK** [Wurst-Imperium/Wurst7#358]
Add anti-hunger a hack from Ares client...thank you

**Comment by NMPCVK** [comment]
Also you can reply me on nikhilmanikandanp30@gmail.com

**Comment by faseri** [comment]
Cringe

**Comment by nofh428** [comment]
@NMPCVK can you make a pull request so I can implement this into my current files to test it out?

**Comment by NMPCVK** [comment]
How to do that as I don't use GitHub...I am new to it so I don't know

**Comment by nofh428** [comment]
@NMPCVK go to https://github.com/Wurst-Imperium/Wurst7/new/master/src/main/java/net/wurstclient/hacks and write out the name of the file you made (for example if it is named AntiHungerHack.java then name it that) and then copy and paste the code. Once you did that click propose new file. Once you did that click create pull request. If you have for example edited hacklist.java you can edit that in your pull request. I can send you the link to a youtube video tutorial if you want?

**Comment by nofh428** [comment]
@NMPCVK THIS should work i think https://www.youtube.com/watch?v=WSWnch-SyPM

**Comment by nofh428** [comment]
@nofh428 did you try it
