### ISSUE TITLE
Nuker shape setting

### ISSUE THREAD

**Issue by TheWienerMaster** [Wurst-Imperium/Wurst7#379]
## Description
Often times when I end up using id-nuker I end up spleefing myself because the ground isn't solid and I end up falling again and again. 

This feature seems like an easy add-on so i decided to try and mess with the code myself, only to be reminded that I don't know how to read or write in java after 2h of trial and error :D

If anyone could make a pull request it would be much appreciated. As much as I gathered then the line: "BlockPos belowPlayer = new BlockPos(MC.player.getPos()).down()", should be added.... somewhere.... in the NukerHack XD. Might even be wrong, but at least I tried my best.

**Comment by Alexander01998** [comment]
This is basically why Nuker's "Flat" mode exists. But Flat mode being incompatible with ID mode is a problem.

I am considering to remove Flat mode and instead add a separate setting that controls the area/shape of blocks that Nuker can break.

**Comment by TheWienerMaster** [comment]
> This is basically why Nuker's "Flat" mode exists. But Flat mode being incompatible with ID mode is a problem.
> 
> I am considering to remove Flat mode and instead add a separate setting that controls the area/shape of blocks that Nuker can break.

Yeah, but flat mode leaves the entire floor, what I'm talking about is that the nuker only leaves the singular block on which you are currently standing on.

Of course adding the floor option to ID-Nuker would also be great, and while I'm already getting greedy then I could also suggest a togglable option, whether Nuker starts breaking blocks closest to you or farthest from you first. That would also negate my problem because theoretically most of the time the last block to be broken in that case would be the one you're standing on
