### ISSUE TITLE
Autotool and Nuker don't like each other

### ISSUE THREAD

**Issue by TheWienerMaster** [Wurst-Imperium/Wurst7#381]
## Description
When using Nuker in survival (i'm using ID-Nuker, not that it matters), autotool doesn't actually equip the right tool for the whole duration of the Nuke, only the first block

## Steps To Reproduce
1. Autotool
2. Start off with the wrong tool
3. Survival Nuker
4. Experience the slowness

## Video

https://user-images.githubusercontent.com/61437644/116005261-e106bc00-a60e-11eb-983b-34947b808637.mp4

**Comment by GreenScripter** [comment]
It looks to me like this is a problem with the switch back feature of autotool. Nuker tells it to switch, and then it switches back before breaking the block.

**Comment by TheWienerMaster** [comment]
I did a quick and simple hotfix for this, I just added so that it doesn't switch back when nuker is enabled.
AutoToolHack.java 
line 96
if(switchBack.isChecked() && !WURST.getHax().nukerHack.isEnabled())

Don't know if it's pull worthy though. And I wouldn't even know how to create a pull in the first place

**Comment by Alexander01998** [comment]
> It looks to me like this is a problem with the switch back feature of autotool. Nuker tells it to switch, and then it switches back before breaking the block.

This is basically why the switch back feature is optional (and used to be removed entirely). It causes all kinds of issues like this when used together with other hacks.
