### ISSUE TITLE
Improve .say so that it doesn't bypass mods

### ISSUE THREAD

**Issue by TheWienerMaster** [Wurst-Imperium/Wurst7#382]
## Description
Since Wurst has moved over to Fabric I have been playing around with adding other mods. Most mods come with their UI or key binds, but some don't, like Baritone. I've been using Baritone @mine command and Wursts' Timer in combination for some incredible results. But at times I go too fast and end up in lava or somewhere similar. And to stop that I'd like to write @stop, but often what ends up happening is that I'm not ready for it, stumble and just die because of the timer speed.

## Suggestion
Right now .binds only focuses on Wurst commands and .say bypasses both Wurst and Baritone completely. The suggestion would be to improve .say or add another command that doesn't bypass chat based mod commands. For instance let's say that the new command is ".sayraw", so when you type for example: ".sayraw .t flight" it toggles flight, or ".sayraw @stop" would then stop the bartione script

**Comment by TheWienerMaster** [comment]
I changed the title and edited the suggestion to make it more understandable from a programmers POV, previously I had a lot of wrong assumptions

**Comment by GreenScripter** [comment]
Currently .say just sends a packet to the server with the message, which I've actually found useful a few times for also bypassing baritone's commands in messages. Probably to send it through the other mods something would need to be done as closely as possible to the way it happens when a command is entered in chat.

**Comment by TheWienerMaster** [comment]
Ohhh it seems a lot harder to implement than I thought. Another wrong assumption on my part, sorry.
So as it is right now, if I'm understanding this correctly, then the current .say bypasses the client entirely and sends the message straight to the server. In order for the commands to work the message has to come from the client, but implementing that to the cheat needs an entirely different approach than .say

**Comment by KTibow** [comment]
It sounds like improving `binds` would be a better version than implementing `sayraw`.
