### ISSUE TITLE
Chat Idea {Fun Category!}

### ISSUE THREAD

**Issue by Hyp3r10** [Wurst-Imperium/Wurst7#387]
[THIS WILL REMAIN OPEN FOR DISCUSSION!]

Like Fancy chat there should be an option to make your chat any color. for example Red, blue, green or black. Basically all colors Not only will the features just be colors, you should make it where you could make crazy font's like bolded text. You should also be able to add these crazy symbols. This idea was based on bedrocks chatting system. 

**Note:** _Java made it to where you cannot use the "§" special character. The only way to solve this is via custom keyboard or to add a Hack that can use the symbol._

Here were the commands:

**Fonts and styles:**
Obfuscated	          §k	                 \u00A7k
Bold                           §l	                 \u00A7l
Strikethrough	          §m	                 \u00A7m
Underline	          §n	                 \u00A7n
Italic	                  §o	                 \u00A7o
Reset 	                  §r	                 \u00A7r

**Colors:**
Dark Red(dark_red)                §4             \u00A74         11141120            AA0000
Red(red)                                 §c             \u00A7c          16733525            FF5555
Gold(gold)                             §6             \u00A76          16755200            FFAA00
Yellow(yellow)                       §e              \u00A7e          16777045            FFFF55
Dark Green(dark_green)       §2               \u00A72         43520                  00AA00
Green(green)                        §a               \u00A7a         5635925              55FF55
Aqua(aqua)                           §b               \u00A7b         5636095             55FFFF
Dark Aqua(dark_aqua)          §3               \u00A73         43690                 00AAAA
Dark Blue(dark_blue)             §1               \u00A71         170                    0000AA
Blue(blue)                              §9               \u00A79         5592575            5555FF
Light Purple(light_purple)     §d               \u00A7d         16733695          FF55FF
Dark Purple(dark_purple)      §5               \u00A75         11141290          AA00AA
White(white)                          §f               \u00A7f          16777215          FFFFFF
Gray(gray)                             §7              \u00A77          11184810          AAAAAA
Dark Gray(dark_gray)            §8               \u00A78         5592405            555555
Black(black)                            §0               \u00A70        0                        000000

Now, I have showed all symbols and colors, They way it'll work like most of the wurst hacks it'll have a menu of what color you want or should be able to enter in any color by hovering you mouse over it the color menu should have an option to enter in the color you looking for by code like FF# or 00#.

**the box should look kind of like:**

![image](https://user-images.githubusercontent.com/75603613/116274241-195de580-a748-11eb-82a4-40ea9dd8184a.png)

**or:**

![image](https://user-images.githubusercontent.com/75603613/116274335-30043c80-a748-11eb-97de-f0a6e75bdd17.png)

These should have a search menu on top but only by color code!

The symbols would have a normal box to Click on the options of want font you want it to be. Now, This should be a hack on all Wurst client hack 1.8 - 12.2 - 1.16.5 Including 1.17 snapshots!

**Comment by AndrewBruhMoment** [comment]
In 1.16+, the color system was reworked to work with hexadecimal (I believe) so this might also be able to use those colors. No idea how to code them in, though.

**Comment by Hyp3r10** [comment]
> In 1.16+, the color system was reworked to work with hexadecimal (I believe) so this might also be able to use those colors. No idea how to code them in, though.

The first thing you would have to code in is The special characters if you decide you want the client to use "§".  you could take that approach or Create some custom thing that would allow to you do all of these options like a separate keyboard.

The main thing behind this idea is to allow owners of the sever / world To use it on anything like using this in chats & signs and anvils!

The hack will not require any permission or creative mode!

**Comment by GreenScripter** [comment]
If you post the § in chat the server will immediately kick you with the message "Illegal characters in chat" even in vanilla. Pretty sure the anvil strips them out, haven't checked signs.

**Comment by Hyp3r10** [comment]
> If you post the § in chat the server will immediately kick you with the message "Illegal characters in chat" even in vanilla. Pretty sure the anvil strips them out, haven't checked signs.

_That's the issue. I've made a script in java Learning on how I can paste or use the "§" sign and have gotten kicked several times. The only Way I can see this working is by making a chat feature_

_That can adjust colors and fonts with a special side keyboard I also don't know why java hates the "§" sign so much._

**Comment by GreenScripter** [comment]
Not sure what you mean by making it a chat feature. Java doesn't care about §, but the minecraft server recognizes its own formatting character and kicks you for it immediately. This feature is to prevent players abusing colors in chat like you are suggesting. When you attempt to send formatted text as a message to the server it kicks you specifically to prevent you from sending formatted text, it doesn't matter how the text got formatted. I can test this by changing the .say command to replace & with § to format messages at the packet level, and then posting a message such as &4Hello. The result is the server kicking you. There are some newer formatting features, but those are not accessible as a client to server chat message, the server must decide to format it.

**Comment by Hyp3r10** [comment]
> When you attempt to send formatted text as a message to the server it kicks you specifically to prevent you from sending formatted text, it doesn't matter how the text got formatted. I can test this by changing the .say command to replace &

_That is true. The only ways I have seen it work is by some custom keyboard to choose a font or color. OR like you said by Replacing the "§" sign with "$" or "&". That's the only work around that seems to work._

**Comment by GreenScripter** [comment]
You can write formatting in books (including via paste), chat kicks you, anvils strip out formatting and signs also strip formatting.

**Comment by Hyp3r10** [comment]
> You can write formatting in books (including via paste), chat kicks you, anvils strip out formatting and signs also strip formatting.

This Is where the custom keyboard idea could come in.
