### ISSUE TITLE
autoSpawnProof

### ISSUE THREAD

**Issue by Th3L1nk** [Wurst-Imperium/Wurst7#399]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
whenever its on it will place slabs on top of spawnable blocks within whatever radius you can. it would be very useful on many server for big farms requiring a lot of spawn proofing. If left on it should continue to place slabs everywhere as you move.

**Comment by davthenub** [comment]
this might be better suited for something like baritone because of the sheer amount of programming that would go into it for pathfinding, determining what blocks can be spawned on, figuring out what blocks can be used to spawnproof, etc

**Comment by Th3L1nk** [comment]
not really, all it would require is like a modified version of crystal aura, where it would just place slabs on the surface of every block in block range.

**Comment by AndrewBruhMoment** [comment]
It would be cool to have a way to automatically walk while placing them though, something like excavate.

**Comment by Th3L1nk** [comment]
yeah thats what I was suggesting

**Comment by Sylvezar** [comment]
If we combine this with the mobspawnesp it could work?
maybe we could remove the light level requirements and then it just starts placing slabs/buttons/carpet/whatever on the spots it finds in the earlier process of the mobspawnesp (it finds blocks that let mobs spawn, then checks their lighting conditions. add a selection menu like the multi id nuker block selection to choose what blocks to use for the spawn proofing. alternatively we could make it highlight where mobs can spawn. that would help too
