### ISSUE TITLE
[AutoTouch] and [Smelt]                                             {Undetermined Category}

### ISSUE THREAD

**Issue by Hyp3r10** [Wurst-Imperium/Wurst7#400]
**At this point I have thousands of ideas for Wurst.**

**[AutoTouch]** - allows you to mine any block like you have silk touch.

you don't need A tool with silk touch, You can mine a block with any tool including your hands! for example if you mine glow stone with your hand it drops as glow stone dust. In this case when you mine it with your hands it will drop as a glow stone block.

_This is so you can mine an enderchest or any kind of silk touchable block without the enchantment on your tool!_

**Exception:**
_you cannot mine spawners with this hack. Like vanilla Minecraft it will just break._

**&&**

**[Smelt]** - allows you to mine any ore and it will automatically smelt the ore and turn it into it's smelted form.

You can mine iron and it will drop raw ore if you are playing in the snapshots if not it will drop iron ore blocks. With this hack It will smelt that are and turn it into it's ingot form. This is also intended to work on all blocks that can be smelted in game.

**Example:** 
iron ore --- iron ingots
gold ore -- gold ingots
ancient debree -- Netherite scraps
cobblestone -- stone
stone -- smooth stone
etc.

the negative affect of [Smelt] is you cannot mine ice or leaves until you turn off the hack.

I think this would be an interesting hack to see implemented since mojang doesn't really listen to ideas much 
(from what I've seen.)

if this isn't possible to code then this will just be a random idea floating around.

**Comment by AndrewBruhMoment** [comment]
If only this was possible

but how?

**Comment by Hyp3r10** [comment]
> If only this was possible
> 
> but how?

Don't know 

https://github.com/UltrusBot/AutosmeltEnchant  <------ This guy works on the mob origins mod> he also made a smelting touch enchantment for 1.17+  you could take a look at it  if you want to.


https://www.curseforge.com/minecraft/mc-mods/auto-smelt-enchantment/files/3275189 try taking a look at this.

**Comment by faseri** [comment]
> Don't know
> 
> https://github.com/UltrusBot/AutosmeltEnchant <------ This guy works on the mob origins mod> he also made a smelting touch enchantment for 1.17+ you could take a look at it if you want to.
It's not possible because hacks are clientside-only but mods must be installed on the server as well. In other words you can't replace server's logic on your client because client has no control of drops and other shit.
//Close

**Comment by carlop3333** [comment]
@Hyp3r10 there is a hack called automine that when you have silk touch (or whatever enchantment) it automatically undermines it, if you want it without enchantments you cannot do anything since it is client-only
