### ISSUE TITLE
Chat Time Stamps

### ISSUE THREAD

**Issue by oommaster** [Wurst-Imperium/Wurst7#403]
## Description
It would be cool to have a time that tells you when something was said. Things like server events that were announced in chat would show you when it started if you didn't see it first. 

ex.
On a server that I play a special mob spawns every 6 minutes and is announced in chat. something like chat time stamps would be nice to time the next spawn and not have to look at a clock.

![jerry](https://user-images.githubusercontent.com/56748751/118895857-f5b83600-b8d4-11eb-88d7-e5e78631cbea.png)

There are other mods that do this but most I found don't work with wurst or are forge mods. It would be more convenient to just have it on there.

![AdvancedChat](https://user-images.githubusercontent.com/56748751/118897347-0cac5780-b8d8-11eb-9835-8a352a170366.png)
*A mod called AdvancedChat*
https://www.curseforge.com/minecraft/mc-mods/advancedchat

**Comment by oommaster** [comment]
AdvancedChat is a fabric mod but it doesn't let you type or see chat when wurst is with it

**Comment by AndrewBruhMoment** [comment]
It should be possible by taking a large quantity of inspiration from AdvancedChat and making it compatible with the way wurst handles chat.

**Comment by KTibow** [comment]
> On a server that I play a special mob spawns every 6 minutes and is announced in chat. 

Is that Hypixel...
