### ISSUE TITLE
UI overhaul

### ISSUE THREAD

**Issue by Th3L1nk** [Wurst-Imperium/Wurst7#406]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
What does it do and how is it useful? Please assume that we have never heard of it before. Just mentioning a name won't work. If it's for an older version of Minecraft (like 1.8 or 1.12), please mention that too.
wursts ui looks like it was made in the 90s, it should look more appealing and also have more info
## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the suggestion.

**Comment by GodSaveTheDoge** [comment]
\>the ui sucks
\>leaves

**Comment by KTibow** [comment]
@Th3L1nk would you like to elaborate? You're speaking very vaguely right now.
