### ISSUE TITLE
Yet another Gradle issue

### ISSUE THREAD

**Issue by Lamby777** [Wurst-Imperium/Wurst7#407]
This hasn't been posted, I checked a bunch of issues and they were for different gradle errors.

## Description
I can't build anything after v7.15.1. Check screenshots for more.

## Steps To Reproduce
Open PowerShell in the folder.
Type any gradle command into the window such as genSources or build.

## Screenshots / Videos (Optional)
![image](https://user-images.githubusercontent.com/35111165/120057083-84802d80-c00e-11eb-8bf6-1525c1bcc7d1.png)
![image](https://user-images.githubusercontent.com/35111165/120057021-13407a80-c00e-11eb-9eb6-5e70480d264d.png)

**Comment by Alexander01998** [comment]
> Type any gradle command into the window such as genSources or build.

Is it really any Gradle command? Try running `./gradlew tasks`, AFAIK that command doesn't need any Fabric stuff to work.

Seeing whether or not the `tasks` command works should tell us whether this issue is caused by Gradle or caused by Fabric.

**Comment by Lamby777** [comment]
It's not EVERY command, but I wrote that late at night so I didn't pay much attention to detail.

Gonna try that later when I'm not busy

**Comment by Lamby777** [comment]
Still fails. :/
![image](https://user-images.githubusercontent.com/35111165/120878919-ad17a280-c58d-11eb-89b7-bbbe208b5b23.png)

**Comment by Lamby777** [comment]
Closing the issue because I haven't had this problem ever since I redownloaded the source and reran the setup commands a long time ago. (idk why this is still open when it's for 1.16.5 build errors, I guess reopen it if other people have this same error for the new builds?)
