### ISSUE TITLE
Cannot add long-id blocks

### ISSUE THREAD

**Issue by N0Eul** [Wurst-Imperium/Wurst7#413]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
Adding long id blocks (like "minecraft:polished_blackstone_pressure_plate") to x-ray block list not working.

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Enter wrust option screen and click "Xray blocks"
2. copy "polished_blackstone_pressure_plate" and paste block adding text box
3. It is input only up to "polished_blackstone_pressure_pla"

**Comment by TheWienerMaster** [comment]
A budget workaround is to manually add blocks to .minecraft/wurst/settings.json, find whatever module you want to add it to, albeit xray, basefinder, autodrop or something similar

**Comment by TheWienerMaster** [comment]
Right now the letter(including spaces) max count is 32, meanwhile the longest block would be 34 characters. 1.17 changes the max length to 41 with: waxed_lightly_weathered_cut_copper_stairs
