### ISSUE TITLE
[BYPASS] LegitScaffold (Silent client side scaffold)

### ISSUE THREAD

**Issue by ENDER1355** [Wurst-Imperium/Wurst7#423]
LegitScaffold is a feature where scaffold is silent client-side but looks like legit bridging in server side, Liquidbounce has this feature, So wurst should have it too, it can bypass AAC, Hypixel and CubeCraft, nearly every client that bypasses Hypixel have this feature, wurst doesn't bypass Hypixel scaffold checks. Adding LegitScaffold will bypass it

## Description
For all supported versions

## Screenshots / Videos (Optional)
https://www.youtube.com/watch?v=h5ZkrNj0SMs
https://www.youtube.com/watch?v=mKKbAv2XRp8&t=30s

**Comment by carlop3333** [comment]
Exists, its safewalk but you need to click it when bridging.

**Comment by TheAwesome98-Real** [comment]
can you stop being on cheat client githubs

**Comment by ENDER1355** [comment]
> can you stop being on cheat client githubs

no.

**Comment by Lamby777** [comment]
um I already did this lmao also there's safewalk if you don't care about safety sliders

**Comment by Waveium** [comment]
safewalk + fastplace is basically legit scaffold lol
