### ISSUE TITLE
AutoWalk

### ISSUE THREAD

**Issue by Z2Up1UwcaYOyZq** [Wurst-Imperium/Wurst7#431]
## Description
A hack that allows for constant moving in one direction. Useful for long travels (if made to also work with flying hacks) and most importantly: could be easily chained with other hacks (automine, killaura, autofarm) to automate boring stuff

### Screenshots / Videos (Optional)
You want a video of me holding W for 10 minutes?

**Comment by TheWienerMaster** [comment]
Dude, there literally is a hack called AutoWalk, which does exactly what you're requesting. How did you not manage to find it in the list if you're suggesting a hack with the exact same name. Generally curious :D

Or if you want to travel and automatically maneuver around obstacles you can use the .goto command

**Comment by Z2Up1UwcaYOyZq** [comment]
>How did you not manage to find it

it was 4 am, I forgot. Let me now open a new issue where I explain my whole idea
