### ISSUE TITLE
ModMenu no longer compatible with wurst's altmanager

### ISSUE THREAD

**Issue by TheAwesome98-Real** [Wurst-Imperium/Wurst7#434]
## Description
The Alt Manager button clips with the Mods button (provided by ModMenu) when it didn't used to

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Install ModMenu
2. Go to title screen
3. Alt manager clips with mods, but it used to not

## Screenshots / Videos (Optional)
![The Wurst Alt Manager button clipping with the ModMenu Mods button](https://user-images.githubusercontent.com/59254971/123675822-10b68800-d83b-11eb-9045-8ca4e6aba0b9.png)

**Comment by Cyberspace999** [comment]
Just press tab to cycle through the buttons. it happens to me a lot

**Comment by Franck-Nein** [comment]
Until it gets fixed, you can manually move it using the FancyMenu mod.

**Comment by sudofox** [comment]
ModMenu provides an option to replace the Realms button. If you're like me and have never touched Realms, this is the option for you until this gets fixed.

**Comment by KTibow** [comment]
Agree with sudofox, you can change where it is in ModMenu's settings, and for the default setting it doesn't clip for me anymore. Consider closing?

**Comment by TheAwesome98-Real** [comment]
> ModMenu provides an option to replace the Realms button. If you're like me and have never touched Realms, this is the option for you until this gets fixed.

I didn't know that was a feature. Thanks!

**Comment by KTibow** [comment]
@TheAwesome98-Real if that works for you, can you click the "close issue" button to the left of the comment button?

**Comment by sudofox** [comment]
Still affects the in game pause menu. I think it should be a bit less intrusive to how it interacts with the pause menu.

I fixed it in mine, maybe I'll submit a PR but I would need to figure out some GitHub magic first

**Comment by KTibow** [comment]
@sudofox other issues exist separately already for the in-game menu.

**Comment by TheAwesome98-Real** [comment]
> @TheAwesome98-Real if that works for you, can you click the "close issue" button to the left of the comment button?

No, since this issue isn’t solved. That’s only a workaround.

**Comment by KTibow** [comment]
Well, with the default settings (no changing it at all), I no longer experience it.

**Comment by KTibow** [comment]
FYI here's how it looks with the default "Below Realms" option:
![image](https://user-images.githubusercontent.com/10727862/147800737-e47bdf56-56a1-40ee-b87f-6ca5b6a2b255.png)

**Comment by TheAwesome98-Real** [comment]
I've just tested and it doesn't happen for me either, so I think it's fixed.
