### ISSUE TITLE
Wurst kept crashing after I use tunneler 3 times

### ISSUE THREAD

**Issue by hachimanhiki12** [Wurst-Imperium/Wurst7#437]
I use wurst on fabric 1.17 and the game kept crashing when I use tunneler 3 times

**Comment by kakolisgay** [comment]
@hachimanhiki12
![lol](https://user-images.githubusercontent.com/16590431/124410404-462f0a00-dd42-11eb-93c6-8177f5ab1bfb.png)

**Comment by hachimanhiki12** [comment]
> @hachimanhiki12
> ![lol](https://user-images.githubusercontent.com/16590431/124410404-462f0a00-dd42-11eb-93c6-8177f5ab1bfb.png)

excuse me?

**Comment by NeroStilts** [comment]
I'm unable to reproduce a crash when using Tunneler three times. If you (or someone else) still has this issue, then posting how it happened and any crash log would be useful.

**Comment by KTibow** [comment]
Agreed. Consider closing if you can't reproduce.
