### ISSUE TITLE
PropHuntESP doesn't detect fake mobs only fake blocks

### ISSUE THREAD

**Issue by XTeamXeno** [Wurst-Imperium/Wurst7#444]
Before posting, please make sure that this hasn't already been reported by someone else.

PropHuntESP doesn't detect fake mobs only fake blocks. If iirc this used to work fine.

To reproduce just turn on prophunt and get into a game

**Comment by KTibow** [comment]
> If iirc this used to work fine.

The tooltip for prophunt says nothing about fake mobs, though.
![image](https://user-images.githubusercontent.com/10727862/147390176-097aa266-7375-4dd5-9208-a475483851ac.png)
