### ISSUE TITLE
Shulker Hack

### ISSUE THREAD

**Issue by TheSammyJam1** [Wurst-Imperium/Wurst7#448]
A hack that you can open a Shulker box while in your inventory and move stuff over and when you exit out of your inventory it would place, steal and break said Shulker box automatically. Also as an option you could pause the sending of packets while breaking and stealing to prevent other people from stealing stuff from your box. 

this mod here is kinda an example - https://www.curseforge.com/minecraft/mc-mods/quick-shulker

Thanks

**Comment by TheWienerMaster** [comment]
It's an interesting idea but I don't think it will save much time tbh, might as well just do it manually. Something like an advanced steal, where you could select and save the items you actually want to steal might come a little more in handy.

> Also as an option you could pause the sending of packets while breaking and stealing to prevent other people from stealing stuff from your box.

What do you mean by this? Are you somehow planning to cancel other peoples packets so they couldn't open containers? :D

**Comment by TheSammyJam1** [comment]
> > Also as an option you could pause the sending of packets while breaking and stealing to prevent other people from stealing stuff from your box.
> 
> What do you mean by this? Are you somehow planning to cancel other peoples packets so they couldn't open containers? :D
if you blink, place, steal, break, stop blink then it all happens at once

**Comment by TheWienerMaster** [comment]
> > if you blink, place, steal, break, stop blink then it all happens at once

No it doesn't? Even when you blink then block placements are server-sided. It doesn't matter if you're blinking or not, the block will still get placed and others could still steal from it.
Same goes for block breaking, you can't magically make it instantaneous while blinking, nor can you even pick it up afterwards without disabling blink first

**Comment by TheSammyJam1** [comment]
ok
