### ISSUE TITLE
Cant change brightness in video settings, is stucked on 50%

### ISSUE THREAD

**Issue by sket0714** [Wurst-Imperium/Wurst7#45]
Whenever I try to slide the bar, after I clicked done and click video settings, the brightness is unchanged, still 50% shown

**Comment by Awakened-Redstone** [comment]
This may be caused from Fulbright
It is anoying, since I want to use bright, but don't want full bright to make my base decoration , and mobproof it without torch spam
50% is too dark to me

**Comment by sket0714** [comment]
I change the code in Fullbright & Xray, change the brightness(gamma in code) to 100%(1.0), but still tedious could change in game

**Comment by Awakened-Redstone** [comment]
I'll try to make a pr with a patch later

**Comment by DoreK333** [comment]
Issue still exists... :/

**Comment by Awakened-Redstone** [comment]
Pull request #88 patches it, but never was applied

**Comment by XfedeX** [comment]
@sket0714 This has been fixed in latest wurst release, please close the issue.

**Comment by Alexander01998** [comment]
Fixed in v7.11.
