### ISSUE TITLE
Wurst 1.8 OF not launching

### ISSUE THREAD

**Issue by RealFX-Code** [Wurst-Imperium/Wurst7#451]
## Description
I cannot open wurst 1.8 OF, I do not know why.

## Steps To Reproduce
1. open wurst
2. crash wurst

## Screenshots / Videos (Optional)
![image](https://user-images.githubusercontent.com/25106569/126778988-971f9153-07be-4706-8b50-e0c84ccc3da3.png)

https://youtu.be/gnbjPWfrOW8

## Crash Report

```

Game doesen't log anything

```

**Comment by carlop3333** [comment]
Thats Wurst6 not 7, sadly is not supported (pd in wurst 6 OF some hacks doesn't work for an "anti cheat" that optifine team implemented)
