### ISSUE TITLE
Add damage check in crystal aura

### ISSUE THREAD

**Issue by AnkerFung** [Wurst-Imperium/Wurst7#454]
add damage check to see if it is worth placing and breaking the crystal, also check if the damage would pop the player himself

**Comment by KTibow** [comment]
> add damage check to see if it is worth placing and breaking the crystal,

What do you mean? What would be "worth it"?

> also check if the damage would pop the player himself

This isn't a bad idea, but if it would pop them, how would it prevent it?

**Comment by AnkerFung** [comment]
for example, only place the crystal and break it if it will do more than specified damage, and not break any crystal that would pop the user

**Comment by KTibow** [comment]
So to put this into different terms, you want CrystalAura to only run place a crystal in a spot where:
- it would actually damage anybody not on your friends list
- it wouldn't damage you enough to die
