### ISSUE TITLE
Parkour Module, Allow an option for jumping if player is crouch-walking.

### ISSUE THREAD

**Issue by burning-eggs** [Wurst-Imperium/Wurst7#456]
## Description
There should be an option to select if the player should jump at the edge while sneaking when using parkour.
Instead of only being able to "jump" when not sneaking using the parkour module, we should be able to jump when sneaking too.
If possible make it have a checkbox to select if they want to jump while sneaking.

**Comment by KTibow** [comment]
Why would you want this exactly? When you sneak while jumping, you barely move at all.

**Comment by Alexander01998** [comment]
Still relevant.
