### ISSUE TITLE
Please get in contact

### ISSUE THREAD

**Issue by Sirllamaa** [Wurst-Imperium/Wurst7#459]
Hi alexander! I have used your client for a while now and I want to make my own! I have looked EVERYWARE for a tutorial but cant find one! this is my last option, going to a fellow coder and asking for your help! I would love for you to teach me how to make a client! Thanks in advanced, Matthew

**Comment by FlorianMichael** [comment]
This is the very wrong place for this, email him and don't open a github issue

**Comment by V3ntus** [comment]
> This is the very wrong place for this, email him and don't open a github issue

Don't even bother the devs by emailing them. Do your own research. That is why search engines like Google exists. You'll find people on StackOverflow, Reddit, Discord, etc. that will help
