### ISSUE TITLE
MultiAura (and maybe others) don't filter piglins (and others?) under "pigmen"

### ISSUE THREAD

**Issue by sudofox** [Wurst-Imperium/Wurst7#466]
## Description
What it says on the tin. 

This dude gets hit by MultiAura even with pigmen filtered out.
![image](https://user-images.githubusercontent.com/3847441/132926486-39621476-dae0-4ad2-b276-b401a0397e62.png)

**Comment by NeroStilts** [comment]
This is easy to fix (whether adding a new filter or including them under zombie pigmen), though it does raise a question of whether to have a general filtering method for auras. There are several auras that seem to essentially have the same filter checkboxes duplicated several times and their filtering repeated. Moving those to a general class would make that code simpler.  
They don't have to share values, though an option for that could be useful as well.

**Comment by KTibow** [comment]
This just sounds like changing the same code a couple of times. Does it sound good to have a general filter to not aggro mobs, such as:
- iron golems
- dolphins
- zombie pigmen
- piglins
- wolves
?
