### ISSUE TITLE
Bring back book dupe command

### ISSUE THREAD

**Issue by Byblik1337** [Wurst-Imperium/Wurst7#468]
Book dupe works fine... Trust me...

**Comment by Byblik1337** [comment]
Bring back .dupe command please...

**Comment by Lamby777** [comment]
honestly

**Comment by Byblik1337** [comment]
It sounds funny, but I use another method which works with that command.

**Comment by carlop3333** [comment]
this got patched on many servers so will be not added again :/ (pd: this was fixed in 1.17)

**Comment by InfinitePower563** [comment]
Most dupes are patched...
