### ISSUE TITLE
High precision ESPs for players far away from spawn

### ISSUE THREAD

**Issue by Jirubizu** [Wurst-Imperium/Wurst7#47]
I am about -430k, 5, 3mil away from spawn and this is the result of chest esp. 
[IMAGE](https://i.imgur.com/S2g5UOF.png)

**Comment by Jirubizu** [comment]
any update on this?

**Comment by Dalethium** [comment]
https://drive.google.com/uc?id=1_yQshCBcU0qUkU_6SJajx0FkGnHyUwYn
I can confirm this, video above. I have done my best to fix this on my fork but I am not a graphical developer at all, as best I can tell though, this could be an issue with floating point precision. I am reasonably certain this has to do with the calculations in net.wurstclient.util.RenderUtils.applyRenderOffset as it affects everything from mobesp to chestesp. Notably it does not affect trajectories.

**Comment by Alexander01998** [comment]
I have found this to be a side-effect of using OpenGL's `translate3d()` command to calculate the final position instead of doing it all on the CPU.

Removing this optimization altogether would negatively affect performance for everyone, even players who are close to spawn.

I might add this as an optional "high precision mode" or something like that.

**Comment by ThisTestUser** [comment]
The problem with GL11.glTranslated() is that you can't translate by too much, or the number will be trimmed down and you'll get precision errors. You can fix this by ensuring the translation amount is never more than a fixed value (like 100).

**Comment by TheGrandCurator** [comment]
@Alexander01998 This is fixed.

**Comment by Alexander01998** [comment]
Right. For reference, this has been fixed in [Wurst 7.12](https://www.wurstclient.net/updates/wurst-7-12/) and [Wurst 6.35](https://www.wurstclient.net/updates/wurst-6-35/).
