### ISSUE TITLE
All PlayerESP lines are the same color (only on Wurst for MC 1.17.x)

### ISSUE THREAD

**Issue by DamianMaz** [Wurst-Imperium/Wurst7#472]
## Description
All PlayerESP lines are the same color (only on Wurst for MC 1.17.x). The same problem is with MobESP.

![2021-09-26_22 12 22](https://user-images.githubusercontent.com/34820479/134823183-7c18793a-b526-4e10-aaf6-d03b5a9bdd19.png)
![2021-09-26_22 25 49](https://user-images.githubusercontent.com/34820479/134823187-92f2f1ef-0b1e-4ec0-b9fc-3a7c46d511f5.png)

**Comment by InfinitePower563** [comment]
Have you checked your settings?

**Comment by DamianMaz** [comment]
I have restored default settings by deleting wurst directory and options.txt from .minecraft and nothing has changed.

**Comment by Alexander01998** [comment]
Fixed.

Before:
![2021-09-28_03 00 35](https://user-images.githubusercontent.com/10100202/135006918-7b47e18a-83d4-449e-a24f-99f80a0eb6fd.png)

After:
![2021-09-28_03 20 54](https://user-images.githubusercontent.com/10100202/135006928-fc919c2f-4165-4165-a7ba-1091680c8524.png)

Also, I couldn't reproduce this bug with MobESP. It seems to be working fine:
![2021-09-28_03 22 13](https://user-images.githubusercontent.com/10100202/135007089-e89622ad-199d-4227-bf47-7516a049eae7.png)

**Comment by DamianMaz** [comment]
That's great you fixed it. Thank you. Anyway, I checked MobESP again and actually there isn't any problem with it. Just when I reported the issue, I assumed it was also true for MobESP and when I checked it I did't look closely.
