### ISSUE TITLE
Bonemeal aura bug

### ISSUE THREAD

**Issue by TheCrazyLion** [Wurst-Imperium/Wurst7#473]
Bonemeal is being used on ready plants for some reason.

**Comment by thyraxx** [comment]
Which Wurst version/MC version?

I could only reproduce this without losing bonemeal with the "other" setting on in Wurst 1.17.1.
Are you sure you don't have "other" enabled in the BonemealAura settings?
Also are you actually losing bonemeal or does it only looks like it's trying to place bonemeal?

**Comment by TheCrazyLion** [comment]
it's placing bonemeal onto full growth wheat. it wasted bonemeal and also makes wheat go at the first stage of growth
