### ISSUE TITLE
AutoFish feature enhancement request

### ISSUE THREAD

**Issue by Lyther** [Wurst-Imperium/Wurst7#487]
## Description

The AutoFish function currently doesn't have an option to set the interval for drawing the fishing rod if there's no fish. In some conditions, the fishing rod would catch items on the water and fail to pull fish. Currently, the default draw time is too long for a Lure III fishing rod.

## Suggestion

If you think this idea is fine to merge into the next version, I can work on it.

**Comment by faseri** [comment]
Cant really get what you mean, I've tested out Lure III fishing rods but didnt get nearly of what you described...
Can you make a video explanation of your problem?

**Comment by Lyther** [comment]
Sorry for the ambiguity of my description. Here's the detailed one:

## Expected Behavior

AutoFish uses a fishing rod to drop on the water and pull it back when a fish bites.

![1](https://i.ibb.co/JrSPZmt/1.png)

![2](https://i.ibb.co/XJ2q0ft/2.png)

The previous pictures show that AutoFish while running properly.

## Problem

When using AutoFish with a fishing rod in the hand, if the buoy is hooked to the floating items on the water. The natural fishing of Minecraft won't be triggered.

![3](https://i.ibb.co/GpKsKSN/3.png)

The buoy is "tucked" with the item and there won't be any fish.

A similar scenario happens when a block is in the way.

![4](https://i.ibb.co/G2rXK3w/4.png)

## Required Enhancement

Automatic pullback happens about 30 seconds after no fish biting. However, for a Lune III fishing rod, maybe 10 seconds is long enough.

Thus, I want some function to provide a time adjustment for AutoFish. This may change the time to pull back the fishing rod if there's no fish. In my test, using a 10 seconds time interval would make the fishing efficiency improve by about 25% when there are a lot of items on the water.

## Solution

If you think this function is necessary for the next version of the Wurst client, I want to get it done and raise a pull request to merge the added codes.

**Comment by KTibow** [comment]
This sounds like it shouldn't be very hard to add, and would be a good improvement. Go ahead, make a PR.

**Comment by Alexander01998** [comment]
Hey @Lyther, thanks for the suggestion! I've added this in commit dd39d597cee99b510b624a546043ff5c047f1731. All of AutoFish's delays are now fully customizable. This will be included in the next release, Wurst 7.35. Keep an eye out for it!
