### ISSUE TITLE
KillAuraLegit Unable to Bypass

### ISSUE THREAD

**Issue by Mehul343** [Wurst-Imperium/Wurst7#492]
## Description
KillAuraLegit can't even bypass simple anti-cheats. 

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Turn on KillAuraLegit
2. Have multiple players around
3. Wait a few seconds to get kicked out of the server!

**Comment by KTibow** [comment]
Can you elaborate? What do you get kicked for? What is your KillAuraLegit config?
