### ISSUE TITLE
Gradle could not resolve dependencies

### ISSUE THREAD

**Issue by Lamby777** [Wurst-Imperium/Wurst7#493]
This is like the 90th time I've been trying to code things for Wurst and Gradle just says "nope" to all my plans. I'm still running an outdated 1.16.5 build from summer.

## Description
Gradle can't find dependencies when doing
./gradlew.bat eclipse

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1.  ./gradlew.bat genSources
2.  ./gradlew.bat eclipse
3.  See a ton of errors in the console.

## Screenshots / Videos (Optional)
This stuff. :(
![image](https://user-images.githubusercontent.com/35111165/141868679-426b2c4c-bbd4-4210-a45c-96ced3946568.png)

**Comment by Lamby777** [comment]
I know it says BUILD SUCCESSFUL but then when I go into Eclipse it tells me I need to fix the problems, which I can't (or don't know how to).

**Comment by InfinitePower563** [comment]
Which Java version are you ulusing? Minecraft 1.16 is only compatible with Java 1.8.

**Comment by Lamby777** [comment]
I downloaded JDK 1.8 and I'm not sure what you mean...
Now genSources doesn't even work because my Java is outdated.

![image](https://user-images.githubusercontent.com/35111165/142327485-5ab42551-632f-4ce1-aa3b-9e5415420948.png)

**Comment by Lamby777** [comment]
I meant to say JRE, it's the only version of Java I have that isn't the JDK
![image](https://user-images.githubusercontent.com/35111165/142329445-ce3eebd7-0f5f-4ec2-984f-0390445ed74f.png)

**Comment by Lamby777** [comment]
It's been over a week since I posted this issue. Nobody else has this problem? :/

**Comment by Alexander01998** [comment]
From the first screenshot it looks like you're on the 1.17.1 branch rather than 1.16.5.
Minecraft 1.16.x needs JDK 8, 1.17.x needs JDK 16, and 1.18.x needs JDK 17.

From what I understand, using a Java version that's "too new" is supposed to be fine. But in practice Gradle almost always crashes when you don't give it the exact Java version that it wants.

**Comment by Lamby777** [comment]
Alright, I got it to work thanks to your recent commit + changing my Eclipse JDK version to 17 in settings.

Java isn't really one of my main languages, so I'm not sure, but I just wanted to mention that SecurityManager might be removed in future versions, and this part of the code could be simpler. Didn't want to make a pull request, since I could be wrong about this. Might as well tell you here, while I'm closing the issue.

![image](https://user-images.githubusercontent.com/35111165/143729932-6d051194-17a9-40ff-9dd6-5e7e8510b044.png)
