### ISSUE TITLE
Errors in eclipse?

### ISSUE THREAD

**Issue by Zynph** [Wurst-Imperium/Wurst7#495]
After importing the source code for Wurst into Eclipse, i'm greeted with errors? why is this?

![image](https://user-images.githubusercontent.com/24725065/142421144-cf3e2fa3-c0a8-4478-aa84-4f79f83cf364.png)

**Comment by NeroStilts** [comment]
Have you ran the `./gradlew.bat genSources` and `./gradlew.bat eclipse`? And did they succeed properly without any errors/warnings?  
For VSCode, I had to upgrade the gradle to get the compilation working (copy `gradle`/`gradlew.bat` from the official fabric example project, then change the `gradle-wrapper.properties` to 7.3), but haven't tested to see if that is needed for Eclipse. I didn't get similar errors, so this probably isn't your issue.
