### ISSUE TITLE
On Inventory Full

### ISSUE THREAD

**Issue by PeteMep** [Wurst-Imperium/Wurst7#499]
## Description
What does it do and how is it useful? 
Okay so at the moment you can bind keys to / commands. now it could be very beneficial if there was an event that would be bound to a command. For example, if the inventory is full will trigger the user inputted command like /sellall. These events could also trigger haxs.

**Comment by Lamby777** [comment]
I like the idea. Made a pull request ^^^

**Comment by KTibow** [comment]
Doable with JSMacros.
