### ISSUE TITLE
Problems on Linux

### ISSUE THREAD

**Issue by truenerthus** [Wurst-Imperium/Wurst7#506]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?
Cannot find 1.12.jar, but I already made a 1.12 installation and ran it.

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Make an installation of 1.12 on Linux
2. Open the wurst installer
3. Point it to /home/name/.minecraft/versions/1.12

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

(crash report goes here)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by KTibow** [comment]
Are there any crash reports?

**Comment by InfinitePower563** [comment]
You also need to install Fabric on your machine and Fabric API in your mods. Fabric can be installed at [https://fabricmc.net/](https://fabricmc.net/) and Fabric API at [https://www.curseforge.com/minecraft/mc-mods/fabric-api](https://www.curseforge.com/minecraft/mc-mods/fabric-api).

**Comment by chuckcarne** [comment]
How do i install on linux?

**Comment by KTibow** [comment]
@chuckcarne just install Fabric and add it to your mods folder as normal, the use of Linux is irrelevant

**Comment by chuckcarne** [comment]
I'm pretty new to linux. Is the mod folder "versions" do I paste it in
there? What commands do I use?

**Comment by KTibow** [comment]
@chuckcarne please familiarize yourself with Minecraft modding. This is not related to Linux at all, this is the same experience you would have on Windows.
