### ISSUE TITLE
Some ideas about bypassing anti-X-ray

### ISSUE THREAD

**Issue by MineYuanlu** [Wurst-Imperium/Wurst7#510]
I have some ideas about bypassing the server anti X-ray. I think it can be realized in theory, but I encounter difficulties in practical operation (insufficient ability):
First, through some seed reverse engineering, we can get the seeds of the world. When the world generation algorithm of the server is consistent with that of the client (that is, no additional plug-ins disturbing the distribution of minerals are added), we can simulate a world locally, and then display minerals in the world by using a function similar to search.
I modified the **`ChunkSearcher`** to be inheritable and created a new class: **`SeedChunkSearcher`**. I think you can add options in search, select the searcher type, and use commands like "**.seed XXX**" to set the world seed.
At present, I encounter difficulties: I am not very familiar with some APIs of fabric. I try to construct a **`ServerWorld`**, but I can't gather the required parameters.

### The above content comes from the translator, and the following is the original Chinese text:

我有一些关于绕过服务器反X-ray的想法，我认为这从理论上可以实现，但在我实际操作中遇到了困难（能力不足）：
首先，通过一些seed逆向工程，可以获得世界的种子。当服务器的世界生成算法与客户端一致时（即，没有添加额外的扰乱矿物分布的插件），我们可以在本地模拟一个世界，然后利用类似Search的功能，将矿物显示在世界上。

我将 **`ChunkSearcher`** 修改为可继承的，并创建了一个新的class: **`SeedChunkSearcher`**。我认为可以在Search中添加选项，选择Searcher类型，并使用类似"**.seed xxx**"的命令来设置世界种子。

目前我遇到的困难：我并不是很熟悉fabric的一些API，我试图构造一个**`ServerWorld`**，但我无法凑齐其需要的参数。

**Comment by buiawpkgew1** [comment]
ChunkSearcher 有没有1.18的？

**Comment by MineYuanlu** [comment]
> 
net.wurstclient.util.ChunkSearcher

**Comment by buiawpkgew1** [comment]
> > 
> 
> net.wurstclient.util.ChunkSearcher

这是？

**Comment by MineYuanlu** [comment]
> > > 
> > 
> > 
> > net.wurstclient.util.ChunkSearcher
> 
> 这是？

ChunkSearcher的路径啊，他只是一个class，不是一个Hack，Search和CaveFinder用了这个。。

**Comment by buiawpkgew1** [comment]
你拉取请求

**Comment by isjerryxiao** [comment]
@MineYuanlu I did achieve the mentioned functionality with a integrated server but the performance is not ideal.
https://github.com/isjerryxiao/Wurst7/commit/45aa330e1bbc630015f97ebd2c02b5c8677d7ced

**Comment by MineYuanlu** [comment]
@isjerryxiao I looked through your code and I think it's very good. As for performance, I do see some places that can be optimized, but I'm busy recently. I'll give you an optimized version after a while

**Comment by Alexander01998** [comment]
We seem to have multiple issues about this topic. Let's track it in https://github.com/Wurst-Imperium/Wurst7/issues/860 from now.
