### ISSUE TITLE
[Bug]Wurst option icon let the Mod menu setings icon go vanished

### ISSUE THREAD

**Issue by tankyap** [Wurst-Imperium/Wurst7#517]
## Description
So I find out that the Mod Menu settings/option icon`(if you wonder what is Mod Menu,is just a mod that adds In-game config to Minecraft)` would disappear while Wurst client is in the mod folder(installed).

## Steps To Reproduce
**1.** Dowload and Install both [Mod menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) and Wurst Client.
**2.** Open a random world.
**3.** Pause the game.
**4.** Profit(the final result)

## Screenshots / Videos (Optional)
The image when the Wurst client or both of them is installed:
![2021-12-16_17 40 21](https://user-images.githubusercontent.com/87649059/146356002-183087f1-b0d4-4586-a0b1-748216efd17f.png)

The image when the Mod menu is installed(only):
![Inked2021-12-16_17 49 58 - 副本_LI](https://user-images.githubusercontent.com/87649059/146355209-c8dab50d-e0c2-4140-a5ff-13367d87f311.jpg)

**Comment by KTibow** [comment]
Duplicate of #291
