### ISSUE TITLE
A new feature: organize the warehouse

### ISSUE THREAD

**Issue by MineYuanlu** [Wurst-Imperium/Wurst7#518]
Name: Warehouse

I have developed a new function, but I'm not sure what you think of this function. At present, the code is not perfect, but it has taken shape.
我开发了一个新功能，但我不确定大家对这个功能的看法，目前代码并未完善，但已有雏形。

[https://github.com/MineYuanlu/Wurst7/tree/1.18](https://github.com/MineYuanlu/Wurst7/tree/1.18)

## Description
This feature can automatically organize the containers in the world. For any container, I divide it into three categories:
Input container (i.e. the container that needs to be taken out, input)
Output container (i.e. warehouse for storing articles, output)
Temporary containers (i.e. sundries that are not in the sorting list and redundant items that have no place to store, temp).
Features can specify how many items each container can store (output) / retain (input) at most.
Through automatic routing, container scanning and automatic access, the automatic warehouse sorting function is realized.

这个功能可以自动地整理世界中的容器。对于任意容器，我将其分为三类：
输入容器（即需要取出物品的容器,input）
输出容器（即存放物品的仓库,output）
临时容器（即存放不在整理列表中的杂物与没有地方存储的多余物品，temp）。

功能可以指定每个容器最多存储（output）/最少保留（input）多少个物品。

通过自动寻路，容器扫描，自动存取，实现自动化的仓库整理功能。

## Screenshots / Videos (Optional)
https://youtu.be/o8EPO1G5udc

**Comment by KTibow** [comment]
This sounds really cool, and is something I've been thinking about for a while. I didn't find any duplicate issues, too.

**Comment by MineYuanlu** [comment]
> This sounds really cool, and is something I've been thinking about for a while. I didn't find any duplicate issues, too.

Finally someone responded to me. I'm very happy. At present, I am testing this function on a survival server. There are still some small bugs. I will solve these problems after 2022-1-10 (before that, I have more important things to do.)
At the same time, I don't know how the GIT branch works. At present, it seems that my pull request contains some incorrect contents. If you understand, please tell me what I should do.

**Comment by KTibow** [comment]
> Finally someone responded to me. I'm very happy. At present, I am testing this function on a survival server. There are still some small bugs. I will solve these problems after 2022-1-10 (before that, I have more important things to do.)

Sounds good.

> contains some incorrect contents

What do you mean by that?

**Comment by MineYuanlu** [comment]
I initiated a pull request #521 , but it contains some updates from the main branch. I hope my pull request only contains my code.
![图片](https://user-images.githubusercontent.com/38997444/147398419-ee0a1537-dbb6-4f91-9470-55312ffd0740.png)

**Comment by KTibow** [comment]
Oh. I looked at it, and suggested some changes. Just click on them to change the code.
