### ISSUE TITLE
Add Ukraine language ( uk-UA )

### ISSUE THREAD

**Issue by MrYotic** [Wurst-Imperium/Wurst7#520]
[uk-UA.txt](https://github.com/Wurst-Imperium/Wurst7/files/7833799/uk-UA.txt)
The translation was done by xVirum, a good friend of mine who lives in Hohland (Ucraine)
I fixed what was said in #526

**Comment by MrYotic** [comment]
I will be grateful if you add to the contributors, my contribution will be visible to my friends!

**Comment by KTibow** [comment]
Please make a pull request instead of an issue, because a pull request lets them add your language with one click.

**Comment by MrYotic** [comment]
> Please make a pull request instead of an issue, because a pull request lets them add your language with one click.
Idk how ... I tried, but nothing came of it

**Comment by MaslovKK** [comment]
why is it needed, because in CIS countries main language is Russian (no nazism)
