### ISSUE TITLE
Lag hack

### ISSUE THREAD

**Issue by Maratons4** [Wurst-Imperium/Wurst7#523]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
This hack would increase your ping. It could be useful to (sometimes) reduces knockback, and also some dupes (That are possible because of specific plugins) could be made easier.

**Comment by KTibow** [comment]
> It could be useful to (sometimes) reduces knockback

Anti-knockback already exists. Also, I think some of these things could be done with Blink.

**Comment by Cyclopropinon** [comment]
yea but if u dont want to make it too obvious, you could just delay the knockback

**Comment by Cyclopropinon** [comment]
or delay blocks getting deleted to have a short time of ghost blocks
