### ISSUE TITLE
Disable all hacks with a command

### ISSUE THREAD

**Issue by KTibow** [Wurst-Imperium/Wurst7#525]
## Description
The Panic button already exists in the UI. It would be good if it was also a command (eg `.panic`). That way I can make a mod to automatically turn hacks on/off depending what server I'm on.

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the suggestion.

**Comment by MrYotic** [comment]
Yea, it`s easy make. If find hack.class.getname.replace({combine classes(Example: "net.wurstclient.hacks.")}) in hacks list

**Comment by pcm1k** [comment]
I think you might want to take a look at `.enabledhax` and `.settings`.

**Comment by Alexander01998** [comment]
Already exists: `.t panic`

**Comment by KTibow** [comment]
Oh, I didn't see that, Alexander. Thanks.
