### ISSUE TITLE
Wurst and Fabritone

### ISSUE THREAD

**Issue by p3iurhgmc98h** [Wurst-Imperium/Wurst7#53]
## Description
When Fabritone is installed, Wurst's overlays (e.g. ESP and BaseFinder) lose all transparency and color.

## Steps to reproduce
1. Install any of the latest Fabritone versions alongside Wurst for 1.15.1 or 1.15.2.
2. Run Wurst, and turn on any ESP module, or BaseFinder.
3. ESP outlines and BaseFinder shadings are solid white.

## Screenshot
![WurstFabritoneBug](https://user-images.githubusercontent.com/60664298/73769886-76d3d400-4749-11ea-80c4-aefe896d0218.png)

## Versions
Please complete the following information:
- Minecraft version: 1.15.2
- Wurst version: 7.0pre25
- Fabritone version: 1.4.5

## Crash report
User-induced crash:
https://pastebin.com/1XE66t7w
This error also occurs when using the vanilla launcher (MultiMC was used for the above crash report).

**Comment by Alexander01998** [comment]
Which OptiFine version are you using?

**Comment by p3iurhgmc98h** [comment]
Not using OptiFine (AFAIK).

FYI (and this may be irrelevant), I have tried going into `indigo-renderer.properties` and setting:
`always-tesselate-blocks=false`
`ambient-occlusion-mode=vanilla`
It doesn't seem to help with the issue.

**Comment by Alexander01998** [comment]
Oh, sorry. I got OptiFabric and Fabritone confused.

**Comment by p3iurhgmc98h** [comment]
As of 7pre27, this issue doesn't seem to be happening anymore for me.
Thanks!

**Comment by p3iurhgmc98h** [comment]
Sorry, I was mistaken. It seems the issue happens intermittently, and it's back for the moment.

**Comment by p3iurhgmc98h** [comment]
Same issue still occurs for Fabritone 1.5.1., Wurst 7.0, and Minecraft 1.15.2.
FYI, at least one other person has had this issue at some point:
https://gitlab.com/CDAGaming/fabritone/issues/4

**Comment by breadbyte** [comment]
I've done some experiments on this issue and i have repro steps that might help shed some light on the situation.

**Repro steps:**
Looking at entities / having entities in render range are what triggers the colors to disappear.
Tile Entities that ChestESP detect seem to also be triggering the colors to disappear, regardless of whether or not ChestESP is enabled or not.
> To test this, start a new flatworld,
> enable MobSpawnESP,
> MobSpawnESP will start without color.
> do `/gamerule doMobSpawning false`,
> do `/kill @e[type=!minecraft:player]` until there are no more entities
> Color should appear.
> `/summon`ing an entity, placing a chest or dropping an item will cause the colors to disappear.


ItemESP is not affected, it's color stays on regardless.

**I've found a quick fix:**
1. Disable your ESP-related hacks.
2. Enable ItemESP.
3. Enable your desired ESP.
4. Drop an item.

Color should appear for the enabled ESPs, until the item disappears or ItemESP is disabled.
This behavior persists over client restarts.
It does not work if you enable your ESP hack before ItemESP.

**Info:**
Minecraft 1.15.2
Fabritone 1.4.5
Wurst Client 7.0-1.15.2

**Manually triggered crash:**
https://gist.github.com/breadbyte/ee4d498f477cf2e61786d6148a3c88f8

**Comment by p3iurhgmc98h** [comment]
Thanks for the excellent documentation. I noticed a similar thing with ItemESP, but hadn't figured out the bit about dropping an item.

**Comment by Jirubizu** [comment]
This isn't wurst related, it's an issue with fabric. CDA did a rebuild with fixes so I recommend you go download that I will get a link in a moment

**Comment by Jirubizu** [comment]
https://gitlab.com/CDAGaming/fabritone/-/jobs/445018929/artifacts/browse/build/libs/ go to that link and download the jar without Dev, your issues will be solved enjoy :)

**Comment by p3iurhgmc98h** [comment]
Thanks for the link, @Jirubizu. I just tested this, and unfortunately everything that @breadbyte said seems to hold for the latest versions.

**Versions:**
LWJGL 3.2.2
Minecraft 1.15.2
Intermediary Mappings 1.15.2
Fabric Loader 0.7.8+build.184

Mods:
Fabric API 0.4.32+build.292-1.15
Fabritone 1.5.1
Wurst v7.0-MC1.15.2

**Comment by p3iurhgmc98h** [comment]
Thanks so much!
