### ISSUE TITLE
Hide hacks from hacklist

### ISSUE THREAD

**Issue by SnakyExotic** [Wurst-Imperium/Wurst7#533]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
What does it do and how is it useful? Please assume that we have never heard of it before. Just mentioning a name won't work. If it's for an older version of Minecraft (like 1.8 or 1.12), please mention that too.
It's so you can hide certain hacks from the hacklist because having too many hacks on can fill up your screen without having to disable hacklist.
## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the suggestion.

**Comment by rastvorovds** [comment]
HackList can be useful if you need to take a clean screenshot or record without having to turn off Wurst or all hacks.
