### ISSUE TITLE
Version Bypass

### ISSUE THREAD

**Issue by rastvorovds** [Wurst-Imperium/Wurst7#534]
## Description
I suggested adding a hack that allows you to send information to the server about which version of the client is being used.
At the same time, add the option to select a version that allows you to log in to the server bypassing the restriction.

**Comment by InfinitePower563** [comment]
Are you talking about the Wurst version or the Minecraft Client version?

**Comment by rastvorovds** [comment]
> Are you talking about the Wurst version or the Minecraft Client version?

I'm talking about the Minecraft version

**Comment by InfinitePower563** [comment]
I think you could just use ViaFabric to implement this.

**Comment by rastvorovds** [comment]
That's what I needed. Thanks!
