### ISSUE TITLE
ForceOP Click the Browse button and nothing happens

### ISSUE THREAD

**Issue by AdminHcat** [Wurst-Imperium/Wurst7#537]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description

Click the Browse button and nothing happens

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. 
2. 
3. 

## Screenshots / Videos (Optional)
![image](https://user-images.githubusercontent.com/50044729/148145983-3791f6de-393d-4c90-9505-6aba9a345f68.png)

**Comment by Alexander01998** [comment]
Can't repro. May have been fixed since the issue was opened.
