### ISSUE TITLE
mod menu incompatibility

### ISSUE THREAD

**Issue by unmellow** [Wurst-Imperium/Wurst7#54]
## Description
when [mod menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) and wurst are installed the alt manager and 
minecraft realms button overlap on the main menu(you can't click on both buttons)
and on the pause menu the wurst options button and, 
the java feedback button overlap  (you can click on both buttons)

## Steps to reproduce
1. Go to 'main menu or in game pause menu'
2. Click on 'nothing'
3. Scroll down to 'nothing'

## (Optional) screenshots / videos
![screenshot_2020-02-08-00:19:15](https://user-images.githubusercontent.com/30985587/74079679-ceec2e00-4a08-11ea-8220-356b36a797a5.png)
![screenshot_2020-02-08-00:19:45](https://user-images.githubusercontent.com/30985587/74079681-d3184b80-4a08-11ea-9bb2-fe37ffa00dba.png)

## Versions
Please complete the following information:
- Minecraft version: [e.g. 1.15]
- Wurst version: [e.g. 7.0pre26,7.0pre2.5]

## Crash report
[crash-2020-02-06_22.15.43-client.txt](https://github.com/Wurst-Imperium/Wurst7/files/4168816/crash-2020-02-06_22.15.43-client.txt)

**Comment by unmellow** [comment]
if possible can you move these menu's to a wurst config menu that i can get to in modmenu when it's installed?

**Comment by GiantNuker** [comment]
"good"

**Comment by unmellow** [comment]
i know lol guess he's not gonna help fix it

**Comment by Alexander01998** [comment]
Fixed in 7a08d008c99a00c1c84272b293a4288c7e8a0ffe

**Comment by unmellow** [comment]
thanks can confirm this is fixed for me

**Comment by RDKRACZ** [comment]
Could you reopen this as it's broken again?
![image](https://user-images.githubusercontent.com/43277609/118397053-87644100-b652-11eb-986d-530a3d843984.png)

Please take a look at https://github.com/TerraformersMC/ModMenu/issues/256

**Comment by Franck-Nein** [comment]
Until it gets fixed, you can manually move it using the FancyMenu mod, if you can't access the mods menu, create a button, set the action type to opengui and the Menu identifier to com.terraformersmc.modmenu.gui.ModsScreen
It's not perfect, butt it does the job.

**Comment by Alexander01998** [comment]
Fixed again. Let's how long it takes them to break it this time... 🙃

**Comment by Cookie-Kurokami** [comment]
![Screenshot (133)](https://user-images.githubusercontent.com/66750372/159446751-d4c424a0-567f-4266-a921-5c86b5eb0008.png)
Lol
