### ISSUE TITLE
Add fast-crafting functionality/hack

### ISSUE THREAD

**Issue by Cheatoid** [Wurst-Imperium/Wurst7#540]
## Description
Feature/hack request for "FastCraft":
I would expect this to be **tremendously helpful and time-saving feature** to have while playing on older version of Minecraft server.
For example when playing on **1.8 server** with **1.18 client**, recipes GUI is present but it does *not* work (probably because it requires some networking on the server side, which is lacking in older Minecraft server version such as 1.8).
The goal is to make that fast-crafting experience work regardless of that functionality missing in older server implementations, so **we could craft items much faster** by using the existing recipes GUI while playing on 1.8 server, which is otherwise not working and very time consuming if you wanted to **craft a lot of something**.
One possible approach that comes to mind, assuming you have crafting bench and recipe GUIs opened, would be to simulate mouse move+clicks or something along those lines, for dragging the required items from the inventory into crafting grid GUI.
Hopefully I have explained this good enough.

**Comment by MineYuanlu** [comment]
https://github.com/mezz/JustEnoughItems
I think you may need this mod. This is very mature.

**Comment by Cheatoid** [comment]
@MineYuanlu Is that not just a recipe viewer? Does that actually have ability to craft items with a single click ("FastCraft")?

**Comment by koliwbr** [comment]
Item scroller have similar future

**Comment by Cheatoid** [comment]
> Item scroller have similar future

In fact, that works great! Thanks for letting me know.
