### ISSUE TITLE
Wurst options (messily?) conflicting with Mod Menu

### ISSUE THREAD

**Issue by Theroumag** [Wurst-Imperium/Wurst7#546]
### Description
In-game Wurst options block the "Mods" option in settings with ModMenu 

Is there some workaround, such as adding another button?

### Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Install Wurst
2. Install Mod Menu (https://www.curseforge.com/minecraft/mc-mods/modmenu)
3. Press Esc in-game

### Screenshots

With Wurst:
![2022-01-17_14 40 06](https://user-images.githubusercontent.com/40362456/149844794-d68a72f5-5afc-4f0c-b3a9-8e14e32f2918.png)

Without Wurst
![2022-01-17_14 42 44](https://user-images.githubusercontent.com/40362456/149844801-48829146-b525-4dc3-a2e9-5648d37c33c9.png)

**Comment by Kadeluxe** [comment]
Is there an .editorconfig for this project?
I've fixed it in my fork so Wurst button injects correctly with all other mods but I can't PR here because this project code style is something special.

**Comment by Kadeluxe** [comment]
I've opened a PR to fix this, although my fix may be not the best.

Meanwhile you can download my [repository](https://github.com/Kadeluxe/Wurst7), open its folder and do `./gradlew build` in command line to compile Wurst with my fix.
