### ISSUE TITLE
Add a bash like scripting language

### ISSUE THREAD

**Issue by lnee94** [Wurst-Imperium/Wurst7#551]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
A simple and I mean simple script language I like bash so pretty much you load a file, and it types stuff into chat like commands or text.
Also commands like alias, if, while, functions etc. would need to added

**Comment by b1ek** [comment]
That's weird no one suggested this before, i just wanted to post here the same.
I think i will do something like this in a while
