### ISSUE TITLE
Inventory/hotbar autosorter

### ISSUE THREAD

**Issue by sitapea1337** [Wurst-Imperium/Wurst7#561]
Hello!

It would be really good to have inventory/hotbar autosorter.
Already have autoarmor which is GREAT for SkyWars, but now inventory/hotbar autosorter could be added as well.
For example, one could configure which slot has which item:
1-sword/axe (whichever better)
2-bow
3-blocks (highest stack)
4-golden apple / best food
5-second-best-food
etc...

**Comment by sudofox** [comment]
If you're using Wurst as a Fabric mod, then there's lots of other mods out there that can supply that functionality. For sorting-related things, I use MouseWheelie, which is highly configurable. https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie

**Comment by sitapea1337** [comment]
> If you're using Wurst as a Fabric mod, then there's lots of other mods out there that can supply that functionality. For sorting-related things, I use MouseWheelie, which is highly configurable. https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie

Thanks for info. However, I'm looking for **fully automated** sorting, really useful for SkyWars games.

I'm not sure, but maybe Wurst has some events I could use (inventory open event) and make my own sorting function. Shouldn't be that hard to implement, because Wurst already has all necessary functions to move items around inventory.
