### ISSUE TITLE
Wurst Log4j fix conflicts with MultiMC fix

### ISSUE THREAD

**Issue by Smartich0ke** [Wurst-Imperium/Wurst7#570]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
When I install a wurst client version that has the log4j fix in MultiMC, the wurst loading screen shows up briefly but then crashes. I think this is because wurst's log4j fix is conflicting with MultiMC's fix. You can check the output log here: https://paste.ee/p/X1tba

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Download and extract wurst 6.35.2
2. Create a new 1.12.2 vanilla instance in MultiMC
3. Click 'Edit instance' and then click 'Add to Minecraft.jar' in the Version tab.
4. Add the extracted wurst jar.
5. Launch the instance

## Crash Report

```

[(crash report goes here)](https://paste.ee/p/X1tba)

```

**Comment by Alexander01998** [comment]
This has been fixed in Wurst 6.35.3. https://www.wurstclient.net/updates/wurst-6-35-3/
