### ISSUE TITLE
Wurst  conflicting with Glassential

### ISSUE THREAD

**Issue by fishace012** [Wurst-Imperium/Wurst7#573]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
When I was playing AOF5, I couldn't start after adding Wurst
## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Install AOF5(https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5)
2. Install Wurst
3. Launch the game

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.
![image](https://user-images.githubusercontent.com/69463190/153124051-189aad12-6f76-479e-be71-e57b012337fd.png)

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

(crash report goes here)
[错误报告-2022-2-9_12.51.19.zip](https://github.com/Wurst-Imperium/Wurst7/files/8029489/-2022-2-9_12.51.19.zip)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by warmbroke** [comment]
Same as #605 #607, https://github.com/Draylar/gate-of-babylon/blob/f74abf529b96f19e05789bd9c5ce8590690a2549/src/main/java/draylar/gateofbabylon/mixin/ClientPlayerEntityYoyoUsageMixin.java#L12
