### ISSUE TITLE
Wurst 7.21 ForceOP dont want to load txt file

### ISSUE THREAD

**Issue by EdwardTime** [Wurst-Imperium/Wurst7#577]
## Description
ForceOP Dont load .txt file

## Steps To Reproduce

1. When i try to load he just use standar 50 passwords

## Screenshots / Videos (Optional)

https://youtu.be/2LwHBXxPazc

## Crash Report

```

```

**Comment by ThebestkillerTBK** [comment]
#537

**Comment by Alexander01998** [comment]
Can't repro. May have been fixed since the issue was opened.
