### ISSUE TITLE
CrystalAura toggle keybind doesn't disable

### ISSUE THREAD

**Issue by sitapea1337** [Wurst-Imperium/Wurst7#578]
CrystalAura toggle keybind doesn't disable

**Comment by Alexander01998** [comment]
Cannot reproduce the issue. Works fine for me.

**Comment by sitapea1337** [comment]
It seems that issue is, when there are several keybinds under same key, for example, CrystalAura does NOT deactivate, when there are also:
AutoSword ; KillauraLegit ; AutoTool ; CrystalAura

It does **activate**, but does **NOT** deactivate.

![image](https://user-images.githubusercontent.com/65604719/153758595-7df09f0e-2e7b-4bc4-81e1-33aec7eee6d3.png)

**Comment by pcm1k** [comment]
It's because KillauraLegit and CrystalAura are not designed to be enabled at the same time and disable each other. This seems to be intentional.

**Comment by sitapea1337** [comment]
Though they do work at the same time and it's illogical that they both can be enabled, but cannot be disabled with same keybind. By that logic, then it would be impossible to enable either one with same keybind, not disable.
