### ISSUE TITLE
problem with Voxelmap

### ISSUE THREAD

**Issue by unrealmanchen** [Wurst-Imperium/Wurst7#579]
<img width="778" alt="截屏2022-02-13 上午12 17 27" src="https://user-images.githubusercontent.com/67812862/153719137-a1def0e5-9fa7-4458-9dd1-95a3bdd9ae88.png">
when using command  /newWaypoint x:<number> y:<number> z:<number> , it says Unknown command
the number in the command 
delete wurst can fix i
[crash-2022-02-13_00.20.41-client.txt](https://github.com/Wurst-Imperium/Wurst7/files/8053996/crash-2022-02-13_00.20.41-client.txt)
t

**Comment by warmbroke** [comment]
#370
