### ISSUE TITLE
Add MineBot

### ISSUE THREAD

**Issue by 0Ariel0** [Wurst-Imperium/Wurst7#586]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
It will be a module like TreeBot, it will try to get to the block that was chosen by the user and try to get there using the AI and thus mining, jumping, walking until reaching the specific block (of course it will calculate first) and so arriving and mining that specific block then calculating and going to another one closer too

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the suggestion.
https://streamable.com/a2wnyd
(Link)

**Comment by warmbroke** [comment]
what you are describing is baritone.

**Comment by Qizhen-Yang** [comment]
You can use tunneler and autodrop together.
