### ISSUE TITLE
Error on gradlew build

### ISSUE THREAD

**Issue by SecretUser001** [Wurst-Imperium/Wurst7#59]
I run `gradlew genSources` and `gradlew eclipse` before I run `gradlew build` and get that error log: 

> gradlew build
> 
> > Configure project :
> Fabric Loom: 0.2.6-SNAPSHOT Build(jenkins #32)
> :setting up loom dependencies
> :setting up mappings (yarn 1.15.2+build.12)
> 
> > Task :compileJava
> :setting java compiler args
> Could not find refmap definition, will be using default name: Wurst-Client-refmap.json
> /net/fileserv/home/beda/WurstEclipse/Wurst7/src/main/java/net/wurstclient/hacks/ForceOpHack.java:451: error: unmappable character (0xE8) for encoding UTF-8
>                         || message.toLowerCase().contains("succ�s")// French
>                                                                ^
> /net/fileserv/home/beda/WurstEclipse/Wurst7/src/main/java/net/wurstclient/hacks/ForceOpHack.java:452: error: unmappable character (0xE9) for encoding UTF-8
>                         || message.toLowerCase().contains("�xito")// Spanish
>                                                            ^
> Note: SpongePowered MIXIN Annotation Processor Version=0.8
> Note: ObfuscationServiceFabric supports type: "official:intermediary"
> Note: ObfuscationServiceFabric supports type: "official:named"
> Note: ObfuscationServiceFabric supports type: "intermediary:official"
> Note: ObfuscationServiceFabric supports type: "intermediary:named"
> Note: ObfuscationServiceFabric supports type: "named:official"
> Note: ObfuscationServiceFabric supports type: "named:intermediary"
> Note: ObfuscationServiceMCP supports type: "searge"
> Note: ObfuscationServiceMCP supports type: "notch"
> Note: Loading named:intermediary mappings from /net/fileserv/home/beda/.gradle/caches/fabric-loom/mappings/yarn-1.15.2+build.12-v2.tiny
> Note: Writing refmap to /net/fileserv/home/beda/WurstEclipse/Wurst7/build/classes/java/main/Wurst-Client-refmap.json
> Note: Writing refmap to /net/fileserv/home/beda/WurstEclipse/Wurst7/build/classes/java/main/Wurst-Client-refmap.json
> Note: Writing named:intermediary output TinyMappings to /net/fileserv/home/beda/WurstEclipse/Wurst7/build/loom-cache/mixin-map-1.15.2-1.15.2+build.12-v2.tiny
> /net/fileserv/home/beda/WurstEclipse/Wurst7/src/main/java/net/wurstclient/hacks/BlinkPlusHack.java:12: error: package net.minecraft.server.network.packet does not exist
> import net.minecraft.server.network.packet.PlayerMoveC2SPacket;
>                                           ^
> /net/fileserv/home/beda/WurstEclipse/Wurst7/src/main/java/net/wurstclient/hacks/BlinkPlusHack.java:34: error: cannot find symbol
>         private final ArrayDeque<PlayerMoveC2SPacket> packets = new ArrayDeque<>();
>                                  ^
>   symbol:   class PlayerMoveC2SPacket
>   location: class BlinkPlusHack
> Note: Writing refmap to /net/fileserv/home/beda/WurstEclipse/Wurst7/build/classes/java/main/Wurst-Client-refmap.json
> Note: Writing refmap to /net/fileserv/home/beda/WurstEclipse/Wurst7/build/classes/java/main/Wurst-Client-refmap.json
> Note: Writing named:intermediary output TinyMappings to /net/fileserv/home/beda/WurstEclipse/Wurst7/build/loom-cache/mixin-map-1.15.2-1.15.2+build.12-v2.tiny
> 2 errors
> 
> > Task :compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileJava'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 8s
> 1 actionable task: 1 executed

**Comment by Alexander01998** [comment]
> /net/fileserv/home/beda/WurstEclipse/Wurst7/src/main/java/net/wurstclient/hacks/BlinkPlusHack.java:34: error: cannot find symbol

You have added things that are causing the build to fail. This is a bug on your end.
