### ISSUE TITLE
Kicks after do use autocraft on craft table 

### ISSUE THREAD

**Issue by Yoticc** [Wurst-Imperium/Wurst7#597]
I was sitting on 2b2t.org and i do use autocraft "coal block" and I was kiked
After do use autocraft on craft table 

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1.  Join to server
2.  Open craft table
3.  To use auto craft in craft table inventory
4. To get 
![image](https://user-images.githubusercontent.com/55879406/158032868-abcdfb8c-c357-49dc-8c2c-645db39e068d.png)

**Comment by MrYotic** [comment]
sorry for my _French_, khm, English
