### ISSUE TITLE
Add ability to choose different "command starter key" 

### ISSUE THREAD

**Issue by Chris6ix** [Wurst-Imperium/Wurst7#600]
## Description
It would be great if you could change the character which is used to start Wurst commands (Currently the `.` (Dot))
Currently, when using Wurst you cannot write something in chat that starts with a dot, as Wurst think you're trying to use a command...

This could for example be set to `-` (Dash), `_` (Underscore) or `;` (Semicolon) as these keys are less likely to be used to start a message than the dot in my opinion

An example is that currently I cannot explain to other users what a command for something is for example (When someone asks for a command, ppl answer with `./"CommandName"` to show the person the command, but I have to use `-/"CommandName"`, which one admin found weird and got a bit suspicious on me...because I didn't use the dot like everyone else...)

Also, currently you cannot send stuff like `...` in chat to reply to someone, for example.

I know that the `.say` exists, but it gets a bit annoying over time to always use it and I sometimes forget it or just want to quickly answer, so the ability to use another key such as the underscore for Wurst commands would really help :)

**Comment by Chris6ix** [comment]
Bump.

**Comment by TheGrandCurator** [comment]
Seems straight forward. I'll make this.

**Comment by Chris6ix** [comment]
@TheGrandCurator Hey just wondering if there are any updates on this?

**Comment by Chris6ix** [comment]
Bump again...

**Comment by Chris6ix** [comment]
Fuck off bot
