### ISSUE TITLE
Boatfly affects horses

### ISSUE THREAD

**Issue by energy11a** [Wurst-Imperium/Wurst7#623]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?
With boatfly active horses do not land
## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. turn on boatfly
2.  ride horse
3.  jump

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```
[crash-2022-04-10_17.12.21-client.txt](https://github.com/Wurst-Imperium/Wurst7/files/8459175/crash-2022-04-10_17.12.21-client.txt)
manual crash using f3+c
(crash report goes here)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by oz5d** [comment]
the horse is (i think) considered a vehicle 
```
// check if riding
		if(!MC.player.hasVehicle())
			return;
		
		Entity vehicle = MC.player.getVehicle();
```
probably works with minecarts and alike
its not a bug its a feature
