### ISSUE TITLE
Can't see chat with AdvancedChat

### ISSUE THREAD

**Issue by LevganSaxen** [Wurst-Imperium/Wurst7#629]
Can't see chat with AdvancedChat

## How to do

1.Download Wurst, [AdvancedChatCore](https://www.curseforge.com/minecraft/mc-mods/advancedchatcore) and [AdvancedChatBox](https://www.curseforge.com/minecraft/mc-mods/advancedchatbox) and [AdvancedChatHud](https://www.curseforge.com/minecraft/mc-mods/advancedchathud)
2. Open new tab in chat.
3. Try to write

https://imgur.com/7IPsF4l
https://pastebin.com/w3kMMu0G

**Comment by xiaozhuo256** [comment]
The same issue occurs in version 1.19.4
