### ISSUE TITLE
NoFall Bug

### ISSUE THREAD

**Issue by ActuallyGsman** [Wurst-Imperium/Wurst7#634]
Elytra with NoFall enabled causes server to report movements as to fast pushing you back zeroing your speed and causing you to fall out out of the sky.

**Comment by Doogie13** [comment]
This isnt false movements, when you spoof onground state when elytraflying, vanilla server will close your elytra wings. NoFall needs an elytra check basically.

**Comment by Alexander01998** [comment]
This issue has been addressed in [Wurst 7.35.2](https://www.wurstclient.net/updates/wurst-7-35-2/).
