### ISSUE TITLE
Features ( Rewritten to make it clearer)

### ISSUE THREAD

**Issue by i5wear** [Wurst-Imperium/Wurst7#635]
Enhancements of existing Hacks{
ChestESP: Add Barral Tracking.

TriggerBot: Add an option to prevent attacking when using items on offhand, such as eating and holding a shield.

New Hacks{
BetterMount: Showing [Hunger] Value while riding.

BetterViewBobbing: Making View Bobbing only affact hand, so the camera will not shake.

TNTime: Showing the remaining time for a TNT or Creeper to explode.

AntiGhostblock: The Ghost block is what is air considered by client but solid block by server. This hack should keep sending packets to server to get the real states of blocks nearby ( the frequency to send should also be optional).

MobAttackIndicator: A bar which shows the current cool-down of a mob's attack (if its cool-down is significant) , such as Skeleton's shot, Blaze's fireballs, and Warden's ranged sound attack. [ This may not be possible, but it's too cool].

AutoMLG (Someone has suggested).

ViewPetOwner (Someone has suggested).

**Comment by Cyclopropinon** [comment]
its sad that this still hasent been added

my addition: [Portal ESP](https://github.com/Wurst-Imperium/Wurst7/issues/776)
