### ISSUE TITLE
Would like to put the specific enabling translation tutorial in the README instead of replacing it with "works the same way as the mod"

### ISSUE THREAD

**Issue by niuyuhao0818** [Wurst-Imperium/Wurst7#640]
I dragged json into the mods folder, and Wurst is still in English. Do you plan to add a tutorial to localize Wurst in the README or official website?

**Comment by Alexander01998** [comment]
Is this resolved? We now have a note on the download page that tells you how to enable translations.

![enabling translations note](https://user-images.githubusercontent.com/10100202/193548392-3b47d00a-4a5c-4c43-ba7e-1a9032480e1a.png)
