### ISSUE TITLE
Undetectabe crystal aura/anchor aura

### ISSUE THREAD

**Issue by Universaldevote** [Wurst-Imperium/Wurst7#644]
Make a slider for anchor aura that makes a 10-1000 milisecond delay explosion when placing an anchor with you holding out the glowstone when putting it in, because right now the anchor aura looks like as soon as you place an anchor is just explodes which makes it sus

Also same thing as crystal aura but when you place a crystal it takes 10 -1000 milisecond delay for it to explode

**Comment by Alexander01998** [comment]
Hang on, let me get this straight. You're playing on a server that
1. doesn't mind you duping tons of crystals and anchors, but
2. finds it sus if your attack delay is off by a few milliseconds??

**Comment by Universaldevote** [comment]
in the server your not even allowed to hack and also i dont know any dupes so i just make a farm

**Comment by Universaldevote** [comment]
Well it just looks very sus for people who know how to anchor/crystal pvp

**Comment by Sxmurai** [comment]
I hate to be that guy, but this doesn't make it "undetectable." For example, even fast rotations will flag on some anti-cheats. Why are you using wurst on a vanilla crystal PvP server anyway? There's multiple servers that allow you to hack that are crystal pvp oriented. 

However, even if you have a slight delay between attacks/placing you still have jittery rotations... Anyone with more than 3 braincells could probably pick up you're hacking.
