### ISSUE TITLE
Steal Skin can't work

### ISSUE THREAD

**Issue by realcirno** [Wurst-Imperium/Wurst7#65]
Steal Skin can't work,J hope that you will fis it.

## Versions
Please complete the following information:
- Minecraft version: 1.15.2
- Wurst version: 7.0

**Comment by Alexander01998** [comment]
Ah yes, it's because `http://skins.minecraft.net/MinecraftSkins/username.png` no longer works.

I haven't been able to figure out the new system yet.

**Comment by realcirno** [comment]
> Ah yes, it's because `http://skins.minecraft.net/MinecraftSkins/username.png` no longer works.
> 
> I haven't been able to figure out the new system yet.

Maybe you can have a try by this mod.I think it is useful for you,
https://www.curseforge.com/minecraft/mc-mods/customskinloader

**Comment by realcirno** [comment]
It may be difficult to solve, but thank you anyway

**Comment by Cryotheus** [comment]
[Mojang API](https://wiki.vg/Mojang_API)
` GET https://api.mojang.com/users/profiles/minecraft/<username>?at=<timestamp>`
The JSON you get from the response has a array called properties, and inside that array there is an object with two fields that are `name` and `value`. The `value` field is a Base64 encoded JSON with an object called `textures`. Inside this object, you can get a link to the player's skin as well as their cape (if they have one).

<img width="1078" alt="Screen Shot 2020-02-25 at 4 28 34 PM" src="https://user-images.githubusercontent.com/14439112/75289266-e8082380-57eb-11ea-9072-528f99ba5e4c.png">
_The response without decoding the `value` field..._
<img width="1078" alt="Screen Shot 2020-02-25 at 4 28 14 PM" src="https://user-images.githubusercontent.com/14439112/75289267-e8a0ba00-57eb-11ea-8985-750ebc440b9c.png">
_and with decoding it._

**Comment by BenCat07** [comment]
For backtracking/Potentially easier method:
`https://api.mojang.com/users/profiles/minecraft/<name>`

Get id field (UUID)

`GET https://api.mojang.com/user/profile/<id>/skins`

Returns a JSON Object which contains an array, in which there is a url field for a direct skin URL

**Comment by BenCat07** [comment]
Nevermind, this is only for the local user

**Comment by BenCat07** [comment]
@Cryotheus Your Solution does not return a Properties object, Only name and UUID.

To get the properties object you need to
`GET https://sessionserver.mojang.com/session/minecraft/profile/<UUID>`


So you basically

`GET https://api.mojang.com/users/profiles/minecraft/<name>`
to get their UUID, then
`GET https://sessionserver.mojang.com/session/minecraft/profile/<UUID>`
to get their account data.
then you grab the Properties, access the array entry with the name "textures" and base64 decode the value, then download that


If you ask me that's a bit of a complicated process and since i have no prior knowledge with JSON/base64 stuff in Java i am afraid i will have to leave this to someone else

**Comment by BenCat07** [comment]
```
		URI UUID_url = URI.create("https://api.mojang.com/users/profiles/minecraft/")
			.resolve(name);
		
		

		try(InputStream in = UUID_url.toURL().openStream())
		{
			JsonParser parser = new JsonParser();
			JsonObject UUID_obj = parser.parse(in.toString()).getAsJsonObject();
			String UUID = UUID_obj.get("id").getAsString();
		}catch(IOException e)
		{
			e.printStackTrace();
			return "\u00a74\u00a7lSkin could not be saved.";
		}
```

This is the only code i have so far, i have no idea on how to approach the JSON array here, and it only gets UUID so far.

**Comment by Cryotheus** [comment]
@BenCat07 My solution does, make sure you read it all the way through.

**Comment by BenCat07** [comment]
I see no mention of the UUID api call in your Solution...

**Comment by Cryotheus** [comment]
Look at the images

**Comment by Cryotheus** [comment]
Frick, I forgot to include this > `https://sessionserver.mojang.com/session/minecraft/profile/` in my post from the API. You were right, whoops.

**Comment by NightcoreRYT** [comment]
It has to use the UUID Now.

**Comment by NightcoreRYT** [comment]
There's a new way of doing it. 
https://textures.minecraft.net/texture/UUIDHere/
