### ISSUE TITLE
ItemPicker and Swim

### ISSUE THREAD

**Issue by xXCooBloyXx** [Wurst-Imperium/Wurst7#657]
1. ItemPicker - when someone drop an item on the ground and many people want to collect it, you will not always collect it, its posbbiel to do a cheat that does so that you will ALWAYS pick this item?
2. swim - swimming where there is no water, so you can go through 1 block

**Comment by ren-yc** [comment]
It is practical to use ItemPicker with FightBot.

I certainly expect it.
