### ISSUE TITLE
(1.14.4)Minecraft crashes with Wurst 7 and OptiFabric

### ISSUE THREAD

**Issue by alphal0gy** [Wurst-Imperium/Wurst7#66]
## Description
Minecraft crashes with Wurst 7 and OptiFabric

## Steps to reproduce
1. Install Wurst 7 (and Fabric API)
2. Install OptiFabric (any 1.14.4 compatibility version)
3. Install OptiFine (any 1.14.4 compatibility version)
4. Start Minecraft
5. See error

## (Optional) screenshots / videos
If applicable, add screenshots or videos to help explain your problem.

## Versions:
- Minecraft version: 1.14.4
- Wurst version: v7.0-MC1.14.4
- OptiFabric version: 0.7.1
- OptiFine version: F5
- TL 1.114.3 [Legacy] (launcher)

## Crash report and log file

[Logger.log](https://github.com/Wurst-Imperium/Wurst7/files/4243655/Logger.log)
[crash-2020-02-24_11.49.28-client.txt](https://github.com/Wurst-Imperium/Wurst7/files/4243664/crash-2020-02-24_11.49.28-client.txt)

Please note: A log file or a picture of the launcher's "something went wrong" screen are _not_ the same as crash report. If the game didn't crash, please hold down F3+C for 10 seconds to generate a crash report.

**Comment by Alexander01998** [comment]
Gist'd for easier reading: https://gist.github.com/Alexander01998/3a3f78d8369d922ba26994d626d440b2

**Comment by Alexander01998** [comment]
You are using TLauncher. https://gist.github.com/Alexander01998/3a3f78d8369d922ba26994d626d440b2#file-logger-log-L1

Sorry, but I can't help with pirated versions. Please just buy the game.

**Comment by m13253** [comment]
Hello,

I have captured another crash log with my paid Minecraft account + MultiMC launcher.

https://gist.github.com/m13253/f4af94cdb2ce36f622f9ffbd22632afd

This crash only happen with Wurst v7.0 + Optifabric + OptiFine.
Wurst v7.0pre26 does not crash.
Other mods are disabled prior to testing.
