### ISSUE TITLE
Excavator gets stuck on bedrock blocks

### ISSUE THREAD

**Issue by nothub** [Wurst-Imperium/Wurst7#675]
## Description
I am experiencing a problem with the excavator. Whenever close to bedrock, the excavator seems to get stuck, switches to a hotbar slot with a placeable solid block in it and stops all visible excavation tasks.

## Video
[wurst.webm](https://user-images.githubusercontent.com/48992448/176207644-0223df10-348b-47cb-97ec-695694c34f19.webm)

[crash report](https://pastebin.com/raw/298Awp6b)

**Comment by Alexander01998** [comment]
Still relevant.

**Comment by Alexander01998** [comment]
Yep, still happens.

**Comment by nothub** [comment]
https://drewdevault.com/2021/10/26/stalebot.html

**Comment by Alexander01998** [comment]
Hey @nothub, thanks for the article!

I agree that stalebot is a flawed system, but IMO it's just a flawed solution to the much more flawed system of GitHub issues.

It would be nice if everyone could just agree that the issue tracker isn't the maintainer's todo-list and that submitting a pull request doesn't entitle them to get their code fixed or even reviewed by the maintainer.

Unfortunately that's not the case. GitHub always makes it look like I have these responsibilities, so most people just assume that I do. And they keep posting issues/PRs and complaining that nothing happens to them.

Then they look at the meaningless number that counts open issues and unreviewed PRs, and they complain that it's "too high", whatever that means.

Despite all of stalebot's flaws, people complain a lot less with stalebot than they do without it. It makes the meaningless numbers go down and makes the not-a-todo-list look a lot cleaner. It's stupid, but unfortunately it works.
