### ISSUE TITLE
Click Tp and SeedRay

### ISSUE THREAD

**Issue by datiq9999** [Wurst-Imperium/Wurst7#680]
1.ClickTP:When you click on a block, you will be teleported to that block
2.SeedRay:19MisterX98 many servers have added a feature that is anti xray and 19MisterX98 figured out how to bypass it [https://www.youtube.com/watch?v=O7nQP5VW3RM&ab_channel=19MisterX98] hope you add that feature to wurst

**Comment by Alexander01998** [comment]
We seem to have multiple issues about this topic. Let's track it in #860 from now.
