### ISSUE TITLE
It can't inject normal!

### ISSUE THREAD

**Issue by xuzhichang** [Wurst-Imperium/Wurst7#697]
When I tried to get into the game, the game crashed, and the prompt the launcher gave me was that the wurst injection failed, and then I repeated it a few times, still useless，What can I do?

**Comment by xuzhichang** [comment]
[错误报告-2022-8-16_14.10.57.zip](https://github.com/Wurst-Imperium/Wurst7/files/9348286/-2022-8-16_14.10.57.zip)

**Comment by buiawpkgew1** [comment]
不可能

**Comment by xuzhichang** [comment]
xplus 1.18.2 fabic 不带optifabric

**Comment by xuzhichang** [comment]
[modlist.txt](https://github.com/Wurst-Imperium/Wurst7/files/9348360/modlist.txt)
