### ISSUE TITLE
Anti Orebfuscator

### ISSUE THREAD

**Issue by z7087** [Wurst-Imperium/Wurst7#699]
## Description
Clicking on a block causes the server to return the actual block at that location. Send lots of packets to get real blocks within an area.
It should have a block filter and an adjustment bar for the number of packets.

**Comment by MetricsLite** [comment]
Extremely sensible, definitely needs to be added

**Comment by Alexander01998** [comment]
We seem to have multiple issues about this topic. Let's track it in #860 from now.
