### ISSUE TITLE
Crash in pause menu when World Downloader Mod is installed

### ISSUE THREAD

**Issue by NewCrazyLeon** [Wurst-Imperium/Wurst7#70]
hello i always  get a crash if i press escape

log: https://pastebin.com/ai89rt6K

**Comment by Alexander01998** [comment]
Thank you for the crash report!

**Comment by NewCrazyLeon** [comment]
when will it be fixed?

**Comment by Alexander01998** [comment]
> when will it be fixed?

I can't predict the future, but v7.2 seems likely.

**Comment by Alexander01998** [comment]
I couldn't reproduce your issue, but it should be fixed now. please let me know if this test build works for you.

[Wurst-Client-v7.1.2-MC1.15.2.zip](https://github.com/Wurst-Imperium/Wurst7/files/4307462/Wurst-Client-v7.1.2-MC1.15.2.zip)

**Comment by NewCrazyLeon** [comment]
yes it doesnt crash, but it only gave me the wurst options and when i click on it the downloading works, thank you

**Comment by NewCrazyLeon** [comment]
doesnt have anything to do with that but, is there a option to make me invisible?
