### ISSUE TITLE
jail

### ISSUE THREAD

**Issue by EIweiser** [Wurst-Imperium/Wurst7#704]
Hello everyone, they jailed me on a server does anyone know how to go out using wurst?
i tried with .vclip up but it doesn't let me do it.

**Comment by BotiPro2007** [comment]
Which Wurst version did you used? Is this server vanilla? How many blocks above you?

**Comment by EIweiser** [comment]
ho usato la versione "Wurst-Client-v7.27.2-MC1.19", si il server e vanilla, e sono a 15 blocchi sotto terra non so quanti c'è ne sono sopra di me
Per favore aiutatemi

**Comment by EIweiser** [comment]
I used the version "Wurst-Client-v7.27.2-MC1.19", yes the server is vanilla, and I'm at level 15 I don't know how many blocks there are above me
Please help me

**Comment by BotiPro2007** [comment]
If you want clip more than ~10 blocks the server drops you back. To check how many blocks above/below you I recommend ``Freecam`` hack. I also recommend ``.tp`` command to get out from the jail.

**Comment by EIweiser** [comment]
Thank you very much for the tips then the .tp command does not work, while with freecam hack I managed to understand that there are 50 blocks under the ground

**Comment by EIweiser** [comment]
T
here is no way to cross the blocks or move one block to the right / left?

**Comment by BotiPro2007** [comment]
Yes, with  ``.tp`` command. Use ``.help tp`` for more information.

**Comment by EIweiser** [comment]
i tried but the server brings me down, isn't there a hack that makes me move one block left or right?

**Comment by EIweiser** [comment]
i tried but the server brings me down, isn't there a hack that makes me move one block left or right?

**Comment by BotiPro2007** [comment]
Use ``.tp ~1 ~ ~`` if you want move in x axis by one.
Use ``.tp ~ ~ ~1`` if you want move in z axis by one.
Use ``.tp ~ ~1 ~`` if you want to move in y axis by one.

**Comment by EIweiser** [comment]
i tried the server brings me back

**Comment by BotiPro2007** [comment]
Then remove some blocks in your nearby that are breakable in ``Freecam`` than use ``.tp``.

**Comment by EIweiser** [comment]
it doesn't break me, do you want to enter the server and let's see if you can help me?

**Comment by BotiPro2007** [comment]
Yes, I want.

**Comment by EIweiser** [comment]
The server ip is "mc.whengamerfail.it" my name is EIweiser on minecraft

**Comment by EIweiser** [comment]
write me on telegram @Imsavio

**Comment by BotiPro2007** [comment]
I don't have telegram. Can we use discord instead?

**Comment by EIweiser** [comment]
yes, "Tibe#6021"

**Comment by BotiPro2007** [comment]
I can not invite you. Please change your discord settings to receive friend requests.

**Comment by EIweiser** [comment]
go

**Comment by bluaxd** [comment]
do u get out? lol

**Comment by BotiPro2007** [comment]
No, he did not becouse there was a plugin that does not let him out from the jail.
