### ISSUE TITLE
Update to 20w09a

### ISSUE THREAD

**Issue by masterries** [Wurst-Imperium/Wurst7#71]
There is a new Minecraft Update 20w08a Version is not working

**Comment by masterries** [comment]
Habe mich jetzt selber damit beschäftigt und muss ja eigentlich nur die gradle.properties updaten mit 
https://modmuss50.me/fabric.html
und fabric.mod.json

Nur bekomme ich das Projekt dann nicht compiliert

**Comment by Alexander01998** [comment]
It's done when it's done. Please don't abuse the issue tracker like that.
