### ISSUE TITLE
patch for fightBot

### ISSUE THREAD

**Issue by Mayank-1234-cmd** [Wurst-Imperium/Wurst7#713]
Some servers have made a patch for fightBot by adding a player that constantly teleports behind the player but that "player" isn't a player and is only sent to the fightbot user.

To fix this we could ignore players behind players or not allow a certain name that's the name of the player behind balbalba but then servers could just randomize the person-behind-the-person's names

**Comment by Alexander01998** [comment]
Typically you can filter out such bots with the "Filter invisible" (if it's an invisible bot) or "Filter flying" settings.

**Comment by Mayank-1234-cmd** [comment]
Neither of those worked (it's not invisible or flying). I think it'd be better if we added something like whitelist or blacklist certain players by clicking on it or making regexes match names, as this could be used to blacklist the "bot" player

**Comment by The0nePlayer** [comment]
Using names to prevent the fightbot from targeting non-existing player(s) would not be ideal, as the server can just generate random player names to counteract this feature (if this is added).  There must be another way to fix this.

**Comment by ren-yc** [comment]
Another reason for adding the whitelist of players' names is that mob may not be a real "mob", but a customized non real player.
