### ISSUE TITLE
Alt Manager: Microsoft Login

### ISSUE THREAD

**Issue by shikukuya** [Wurst-Imperium/Wurst7#714]
## Description
i started the game with a microsoft account
then i switch to an offline account via alt manager
I CANT SWITCH TO MY MICROSOFT ACCOUNT!!!

## Screenshots / Videos (Optional)
![image](https://user-images.githubusercontent.com/89395757/193977031-5a4e9edc-5703-4c63-9dbd-784fb82e1e32.png)

**Comment by Alexander01998** [comment]
Microsoft accounts are already supported. There is no separate button. You just need to login with your Microsoft email and password.

Note that Microsoft accounts with 2FA are currently not supported, because there is no UI in Wurst for displaying the 2FA prompt.

**Comment by shikukuya** [comment]
thanks ：）

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shikukuya** [comment]
@Alexander01998 wrong password?
