### ISSUE TITLE
BarrierESP hack

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/Wurst7#715]
A simple hack that reveals [barrier blocks](https://minecraft.fandom.com/wiki/Barrier) when enabled, without having to be in Creative Mode or holding a barrier item.

**Comment by Cyclopropinon** [comment]
maybe also useful for structure void and block 36 (moving_piston)

**Comment by GreenScripter** [comment]
It is possible to make the barrier not invisible by modifying the BarrierBlock and RenderLayers classes with mixins, and then textures can be included to texture it like a normal block.

**Comment by RealmKebab** [comment]
https://modrinth.com/mod/visiblebarriers <- smth like this mod would be cool

**Comment by GreenScripter** [comment]
That's what I did for my fork, but since this project doesn't seem super active about merging pull requests I haven't bothered to make it into one.

**Comment by Alexander01998** [comment]
Hey @GreenScripter! I understand your frustration, but let's keep the conversation friendly and constructive. It's normal for open-source projects to have a backlog of pull requests and suggestions, especially when it's maintained by a single developer like me.

I appreciate your effort in creating your own fork with modifications to the BarrierBlock and RenderLayers classes. That's a great way to customize the behavior and appearance of the barrier blocks. However, merging pull requests while maintaining a high standard of quality is a time-consuming task, so it might take some time to review and incorporate such changes.

Also, keep in mind that we already have two pending pull requests implementing a BarrierESP feature. You might want to look into those existing PRs before adding a third one.

Thanks for your understanding and contributions! Let's keep the development spirit alive.
