### ISSUE TITLE
OreSim based on seed

### ISSUE THREAD

**Issue by sitapea1337** [Wurst-Imperium/Wurst7#724]
Please add a feature called OreSim, where you can enter a pre-found seed and it simulates different ore locations.

This has been added to Atomic client and also Meteor client addon called Meteor Rejects
There is also older version Fabric mod called SeedMapper.

https://github.com/AntiCope/meteor-rejects
https://github.com/xpple/SeedMapper

https://www.youtube.com/watch?v=nv3wevLjiwo

**Comment by Mayank-1234-cmd** [comment]
I think a seed finder coupled with this feature could patch the anti-xray plugins in most if not all servers, and there'd be really no way to bypass this (or not that I could think of). +1 (pls add)

**Comment by The0nePlayer** [comment]
If this is implemented, this might be Minecraft's very first method to reverse-engineer the seed (except /seed of course).

**Comment by Cyclopropinon** [comment]
> I think a seed finder coupled with this feature could patch the anti-xray plugins in most if not all servers, and there'd be really no way to bypass this (or not that I could think of). +1 (pls add)

well technically they could use a mod changing the ore generation different to vanilla, but i think most serverowners are way too lazy XD

**Comment by Alexander01998** [comment]
We seem to have multiple issues about this topic. Let's track it in #860 from now.
