### ISSUE TITLE
Flying kicks with "Flying is not enabled on this server"

### ISSUE THREAD

**Issue by iamspeed199** [Wurst-Imperium/Wurst7#73]
## Description
While using flight on a Notchian server you get kicked with a message "flying is not enabled on this server". Older Wurst for 1.12 used to have a kick bypass feature and some proprietary hacked clients have it on 1.15 as well.

## Steps to reproduce
1. Connect to a pure vanilla server
2. Enable flight hack
3. Fly around for a few seconds

## Versions
Please complete the following information:
- Minecraft version: 1.15.2
- Wurst version: 7.1

**Comment by Alexander01998** [comment]
This is normal, though a new Flight kick bypass may still be added in the future.

**Comment by TheWienerMaster** [comment]
If your goal is to fly long distances then a manual way of bypassing getting kicked is to first gain altitude fast an then kind of glide down. You can fly for 2/3 sec, then double-tap your fly key so you lose a bit of altitude and then rinse and repeat. I've flown like this for 10 000 blocks without touching the ground once. Only works in vanilla though

**Comment by iamyou** [comment]
> If your goal is to fly long distances then a manual way of bypassing getting kicked is to first gain altitude fast an then kind of glide down. You can fly for 2/3 sec, then double-tap your fly key so you lose a bit of altitude and then rinse and repeat. I've flown like this for 10 000 blocks without touching the ground once. Only works in vanilla though

Or flying while using blink?

**Comment by BenCat07** [comment]
If the game simply checks if you are on a specific height for too long one could just fly down a very tiny bit every like 2 seconds

**Comment by BenCat07** [comment]
Seems the minimum to reset is 0.02 blocks per tick, this can be easily implemented into flyhack and i may make a pull request

**Comment by BenCat07** [comment]
#78 is now the pending pull request

**Comment by CrazyByDefault** [comment]
On a Spigot 1.15.2 server w/ no AntiCheat, we found Jetpack to be the most effective mode of flight. You can boost in and out of water (to reduce food consumed), and along with glide it can really take you quite far.

Flight kicks us every other second thanks to Spigot, so this might be a viable alternative for others too.

**Comment by Alexander01998** [comment]
Closing this as a Flight kick bypass was added in [Wurst 7.29](https://www.wurstclient.net/updates/wurst-7-29/).
