### ISSUE TITLE
Not an issue -- a question about license

### ISSUE THREAD

**Issue by SirEnder125** [Wurst-Imperium/Wurst7#734]
Hey! I am making a mod of my own, and I am having trouble figuring out events. Does your license allow for me to use your EventManager class or individual Event/Listener classes?

**Comment by Alexander01998** [comment]
Basically, the rules are the same whether you use a part of the code or all of it. You can use the EventManager in an open-source project that is released under the GPL 3.0 license. You can also use it in a private project that you only use yourself and never release.

But that's just a very short summary that leaves out a lot of details. I would highly recommend that you read the original license document to get the full picture: https://choosealicense.com/licenses/gpl-3.0/

**Comment by SirEnder125** [comment]
Alright, cool. Thanks! I'll look into that. If my mod gets to a decent place, I'll publish it along with the source code. :) For now I'll just keep it to myself
