### ISSUE TITLE
Weird client behavior when using Sneak [legit mode] with Freecam

### ISSUE THREAD

**Issue by The0nePlayer** [Wurst-Imperium/Wurst7#741]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
When turning on freecam, if sneak has been enabled, then the freecam only goes down and the player (The one seen by other players on server) stops crouching.
What I recommend to patch this is that freecam remains unaffected weather or not sneak [legit] is enabled or not.

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Type ".binds remove y" in chat
2. Type ".binds remove z" in chat
3. Type ".binds add y sneak" in chat
4. Type ".binds add z freecam" in chat
5. Press y
6. Wait for a moment
7. Press z

## Screenshots / Videos (Optional)
I would attach a screenshot, but I'm not using my main computer (the one with Minecraft installed) for writing this bug report.

## Crash Report
I will attach a crash report as soon as I can (I currently don't have access to my computer, I'm making this report from a mobile device)
```

(crash report goes here)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by dolphin-cat** [comment]
at the moment freecam works on the player and not on the camera which causes those issues and breaks other mods, the correct fix would be for freecam to modify the camera and not the player itself
