### ISSUE TITLE
Scaffoldwalk with Airplace

### ISSUE THREAD

**Issue by The0nePlayer** [Wurst-Imperium/Wurst7#742]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
What it does: The scaffoldwalk will work with airplace (toggleable) to place blocks below player even if there is no block placed anywhere near the player
How it is helpful: (Assuming that flight is not allowed on a server but other hacks are) If a player is falling into the void, or a player has been hit with huge knockback, the player can fall to an area with no blocks already placed next to the player, so scaffoldwalk is unable to place blocks below the player and the player falls into the void. If scaffoldwalk would work with airplace, then the player can be safe from falling into the void even if there are no blocks near the player. This is possible to do with just airplace, but the player has to manually aim the mouse and right click at the perfect time to place blocks under the player (which is not easy).

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the suggestion.

**Comment by Cyclopropinon** [comment]
the blockplacing under the player could be automated probably (or with keybind, so no need to aim and click)
