### ISSUE TITLE
Not an issue -- A question about next update on 1.16.5

### ISSUE THREAD

**Issue by marlester-dev** [Wurst-Imperium/Wurst7#745]
Hello, it looks like Wurst 7.28-7.30 updates added some cool features that I really need in 1.16.5 (Flight Anti-Kick, AntiHunger, AirPlace, NoLevitation). As you understand, I can not just update to 1.19.2 because some of my mods are stuck on 1.16.5 and they will stop working on 1.19. So, when will the Wurst update on 1.16.5 be? Please do not delay it.

**Comment by kisrr** [comment]
im pretty sure when a new mc version gets dropped every previous version becomes a legacy version

**Comment by Alexander01998** [comment]
> im pretty sure when a new mc version gets dropped every previous version becomes a legacy version

No, not all of them. There is a list of Minecraft versions at https://www.wurstclient.net/download/ where legacy versions are labelled as "OLD". 1.16.5 does not currently have this label.

Of course, not every Wurst update gets released for every Minecraft version, as that would slow down development, but I agree that another 1.16.5 port would make a lot of sense at this point.

**Comment by marlester-dev** [comment]
> > im pretty sure when a new mc version gets dropped every previous version becomes a legacy version
> 
> No, not all of them. There is a list of Minecraft versions at https://www.wurstclient.net/download/ where legacy versions are labelled as "OLD". 1.16.5 does not currently have this label.
> 
> Of course, not every Wurst update gets released for every Minecraft version, as that would slow down development, but I agree that another 1.16.5 port would make a lot of sense at this point.

Big thanks for [new update on 1.16.5]([url](https://www.wurstclient.net/updates/wurst-7-31/)), I am closing this thread
