### ISSUE TITLE
BoatFly fall damages

### ISSUE THREAD

**Issue by gnikwo** [Wurst-Imperium/Wurst7#75]
## Description
When i land using BoatFly, if i flew too high, i take fall damages when i touch the ground and move.
It doesn't happen on local games, only on server, even on a local server.

## Steps to reproduce
1. Connect to a server
2. Ride a boat
3. Go high enough to die from fall damages
4. Wait for the boat to fly down to the ground
5. Press forward
6. After a small lag, you die

## Screenshot/Video
I'll post a GIF in comments

## Versions
Please complete the following information:
- Minecraft version: 1.15.2
- Wurst version: 7.1

## Profile used
BoatFly
NoFall

**Comment by gnikwo** [comment]
![animation](https://user-images.githubusercontent.com/61657000/75630724-6ea67180-5bed-11ea-986b-3a2526d5ade6.gif)

**Comment by p3iurhgmc98h** [comment]
Are you using NoFall?

**Comment by BenCat07** [comment]
> ## Description
> 
> When i land using BoatFly, if i flew too high, i take fall damages when i touch the ground and move.
> It doesn't happen on local games, only on server, even on a local server.

Means the change is not networked to server

**Comment by BenCat07** [comment]
Possibly either due to fallDistance not being updated by the server, or the server overriding the nofall packets

**Comment by BenCat07** [comment]
I've confirmed that fallDistance stays 0 while in a boat.

**Comment by BenCat07** [comment]
A possible fix would be changing
```		if(player.fallDistance <= 2)
			return;```
to
```		if(player.fallDistance <= 2 && !player.hasVehicle())
			return;```

i am however unsure if that really is a good solution. It will however also remove fall damage in vehicels aswell

**Comment by NightcoreRYT** [comment]
Have you tried NoFall with it?

**Comment by joehillen** [comment]
Is gliding slowing the only way to fly **down**? I can't figure out which key to use.

**Comment by joehillen** [comment]
Also this still happens even with NoFall
