### ISSUE TITLE
Multi inv

### ISSUE THREAD

**Issue by z7087** [Wurst-Imperium/Wurst7#756]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
Use a button to hide inventory that is currently being displayed instead of closing it. Use another button to show a list of all hidden inventory to have them re-displayed.

## Screenshots / Videos (Optional)

**Comment by Cyclopropinon** [comment]
how can u get multiple inventories?
i dont get it what u want to list

**Comment by Cyclopropinon** [comment]
thats interesting
maybe just dont send closing-package would work
