### ISSUE TITLE
Hide ui and visible hacks during screenshot

### ISSUE THREAD

**Issue by EllieJaybee** [Wurst-Imperium/Wurst7#757]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
Make a toggle to hide ui objects such as the hack list/wurst logo, and on screen hacks such as chest esp/mob esp upon taking a screenshot so they don't appear in it

**Comment by Alexander01998** [comment]
I like this idea, but I'm currently working on something else. If anyone would like to open a PR for this feature, I'd be happy to review it and provide any assistance needed.

**Comment by Cyclopropinon** [comment]
like hiding it while having f3 on?

**Comment by EllieJaybee** [comment]
@Cyclopropinon No? You might want to give it a reread

**Comment by Cyclopropinon** [comment]
yea, but u have to do it for every screenshot, and then undo it
would be pretty nice if it could be automated

**Comment by EllieJaybee** [comment]
@BGOPC More than 2 things. Every ESP hacks, every xray hacks, every overlay hacks, and more. Doing that for more than once is painful.

**Comment by BGOPC** [comment]
> @BGOPC More than 2 things. Every ESP hacks, every xray hacks, every overlay hacks, and more. Doing that for more than once is painful.
 
Oh, Okay
Great idea
