### ISSUE TITLE
Chat doesn't print to log

### ISSUE THREAD

**Issue by No-Eul** [Wurst-Imperium/Wurst7#761]
## Description
Chat messages aren't printed in the log when I join a server.

## Steps To Reproduce
1. Join a Minecraft server
2. Send a chat message
3. If Wurst is not applied, chat messages are logged correctly with `[CHAT]` tag. However if applied, no chat will be logged. Disabling Wrust also doesn't.

**Comment by isjerryxiao** [comment]
possible patch: https://github.com/isjerryxiao/Wurst7/commit/63f113fa07a3b3d16ae9e9dc6a4b2b6c0de11be7
