### ISSUE TITLE
Anticheat Disabler

### ISSUE THREAD

**Issue by petruliviuadetu** [Wurst-Imperium/Wurst7#763]
Sorry if it is suggested by someone else , if it is not, wurst needs anticheat disabler

**Comment by Chris6ix** [comment]
How exactly do you think that should work?

Don't you think if it was possible to disable a server's Anti-Cheat, Wurst would already have that ability?

**Comment by petruliviuadetu** [comment]
Yeah but, idk that hack/cheat ... I use 1.19.2
@Chris6ix

**Comment by Chris6ix** [comment]
Disabling an anti cheat is just not possible, so I guess you can close this issue.

**Comment by ThebestkillerTBK** [comment]
🤡

**Comment by ccuser44** [comment]
This is most likely not possible

**Comment by Cyclopropinon** [comment]
@z7087 can u add link?

**Comment by Cyclopropinon** [comment]
well these couldnt be used for long, since wurst is open-source and anticheat-devs will probably try to patch these asap :(
