### ISSUE TITLE
Loading Settings not working (Linux)

### ISSUE THREAD

**Issue by BenCat07** [Wurst-Imperium/Wurst7#77]
## Description
You can save Settings properly, and loading says "Settings loaded", but loading settings does not load any of the things saved in the file

## Steps to reproduce
1. Save Settings
2. Check file in ~/.minecraft/wurst/settings
3. Discover that the contents are valid
4. Load settings
5. Discover that no hacks were enabled or disabled

Sidenotes: 
- I am using Manjaro Linux (A branch of Arch linux)
- Loading Binds Works just fine

## Versions
- Minecraft: 1.15.2
- Wurst version: Latest Source compiled for 1.15.2

## Crash report
not applicable

**Comment by Alexander01998** [comment]
> 5\. Discover that no hacks were enabled or disabled

Settings and enabled hacks are separate. Use `.enabledhax` to save & load hacks.

**Comment by BenCat07** [comment]
Oh i thought that just lists which are currently active

Thanks for telling me
