### ISSUE TITLE
Danger Heatmap

### ISSUE THREAD

**Issue by CSRONOML** [Wurst-Imperium/Wurst7#777]
## Description
I propose a “danger" heatmap that changes the color of the blocks in the floor, where blocks will become red tinted if there are other players that can reach that block quickly and green tinted otherwise. This can be done by calculating the flood fill distance for each other player to each block nearby the player, and the heatmap can be updated every half a second or something, the player using that feature could easily avoid dangerous areas in the map simply by following green blocks and avoiding red blocks.

**Comment by Cyclopropinon** [comment]
there could be a yellow tinted one for medium danger
