### ISSUE TITLE
Fabric API v0.75.0 Crash

### ISSUE THREAD

**Issue by K9Paradox** [Wurst-Imperium/Wurst7#778]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
On the newest Fabric api v0.75.0  for game version 1.19.3 , Wurst causes a crash on startup. 

## Crash Report
```
https://mclo.gs/VD0rcPj

```

**Comment by Blue-Gamer48** [comment]
i hav a fabric crash https://mclo.gs/sSYgm6x
