### ISSUE TITLE
YesCheat+ feature in latest Wurst?

### ISSUE THREAD

**Issue by ccsimplyspolit** [Wurst-Imperium/Wurst7#79]
we have 
https://www.wurstclient.net/wiki/Special_Features/YesCheat/
but where is that feature?

**Comment by Alexander01998** [comment]
YesCheat+ is only in Wurst 6.

Wurst 7 instead has TooManyHax and multiple different types of profiles, which provide a much more customizable alternative to YesCheat+.

**Comment by MattPlayGamez** [comment]
Where can we download those profiles?
