### ISSUE TITLE
freecam enhancement

### ISSUE THREAD

**Issue by tholvibt** [Wurst-Imperium/Wurst7#797]
i want to suggest something which will improve freecram

for me i cant use freecamera while i am crouch so it would be helpful if freecamera doesnt pull down when 
the player is crouching 

my settings for sneak is toggle left control

some anti cheat doesnot allow to use freecamera
i wish you will accept this suggestion

thank you for reading
faithfully tholvibt

**Comment by Cyclopropinon** [comment]
how can freecam be detected by anticheat?

**Comment by tholvibt** [comment]
in some server like jartex network it will pull back to player

**Comment by Cyclopropinon** [comment]
but how does it detect?
its literally just a cam and not a player
i think it doesnt even send packets, right?

**Comment by tholvibt** [comment]
yes. But when I use something pulls back I think it may be Anti cheat. But free cam will work smoothly in single player and server with no Anti cheats.

**Comment by Cyclopropinon** [comment]
but that didnt answer my question: how does the server detect freecam?

**Comment by bendy1234** [comment]
> but that didnt answer my question: how does the server detect freecam?

freecam freezes the player

**Comment by Cyclopropinon** [comment]
ok, and how does it pull back?

**Comment by bendy1234** [comment]
> ok, and how does it pull back?

I'm not sure about that, but the server might be sending packets to move the player

**Comment by impresson** [comment]
> ok, and how does it pull back?
> 

What happens is ur sending rotation packets(I think) to the server or snth similar and the anticheat goes nope and does a "original rotation" s2c packet which is why it teleports u back(this is a theory)

I hope this answers ur question

**Comment by impresson** [comment]
> so what about not sending any packages, and remove the "feature" that u get teleported back (unless u get damaged or so; toggleable)

Yeah basically it disables rotation packets whilst in freecam & therefore the server thinks we're looking the original way. Also think of it like the blink module.

**Comment by BartBanaan** [comment]
im pretty sure that the anticheat can detect your in freecam because all of your playerpackets get paused and the anticheat finds that sus

**Comment by Cyclopropinon** [comment]
afaik the player also sends some packets while afk, so wurst can pretend to be afk while I'm in freecam

**Comment by 6AngryFox9** [comment]
try disabling "autosprint" in all its forms, then you will no longer be teleported to your character during freecam
