### ISSUE TITLE
TUNNELER crash 

### ISSUE THREAD

**Issue by anthony5301** [Wurst-Imperium/Wurst7#807]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
Both 1.19.3 and 1.19.4 crashing
Tried a clean reinstall of minecraft and wurst
Only wurst and fabric api in mods folder

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. turn on TUNNELER
2. break some block then turn it off
3. turn on TUNNELER again
4. crash

## Screenshots / Videos (Optional)
[https://youtu.be/tUhIlkHxXSk]

## Crash Report
its too long to post in github

https://ctxt.io/2/AACQcornEQ
https://ctxt.io/2/AACQcmrzFg
https://ctxt.io/2/AACQdqcTEg
https://ctxt.io/2/AACQilP1EA
https://ctxt.io/2/AACQiqP9EQ

**Comment by Alexander01998** [comment]
Hi, thanks for reporting this bug. I tried to reproduce it on my end but I couldn't get it to crash. This looks similar to #433 (AutoFarm crashing on second activation). I'm going to try to fix this in the same way and see if that solves your problem too. Here's a test build that you can try and let me know if it works: [Wurst-Client-v7.33pre1-MC1.19.4.zip](https://github.com/Wurst-Imperium/Wurst7/files/11053685/Wurst-Client-v7.33pre1-MC1.19.4.zip)

**Comment by anthony5301** [comment]
The bug has been fixed! Thank you so much!

**Comment by Cyclopropinon** [comment]
so what was crashing it?
