### ISSUE TITLE
Keybind Enhancement

### ISSUE THREAD

**Issue by BartBanaan** [Wurst-Imperium/Wurst7#808]
-Improve Keybinds:
Add Mouse buttons to keybinds so that you can activate a cheat with for example a button on the side of your mouse. Many other hacked clients also have this
-Improve Keybinds:
Add a feature where you can change a keybind to only work while holding that key, for example:
that a hack is activated when holding “r” and that when you let go of "r" the hack disables itself.

**Comment by BartBanaan** [comment]
I'm pretty sure that to have "mousebinds" you just have to copy the keybind code and make it for a mouse (like a mouselistener is almost the same as a keylistener).

**Comment by Cyclopropinon** [comment]
maybe also add this for a joystick/controller
