### ISSUE TITLE
“NewChunks” hack in Wurst [Suggestion]

### ISSUE THREAD

**Issue by code1dot** [Wurst-Imperium/Wurst7#83]
A lot of other hack clients have a feature called “NewChunks” which allows the player to see which chunks have been newly loaded by the server. It would be awesome if this was implemented in Wurst. I have also not found any source code online that shows how it works. Maybe somebody could post a pull request adding the feature.

**Comment by ThisTestUser** [comment]
If a chunk is new, the chunk will be sent with SPacketChunkData.isFullChunk() set to false.

**Comment by Alexander01998** [comment]
> If a chunk is new, the chunk will be sent with SPacketChunkData.isFullChunk() set to false.

Thanks for the tip! 👍

**Comment by PhilConnor** [comment]
This is a must. Please implement :).

**Comment by code1dot** [comment]
I am going to try and make a pull request for the hack and will close this issue when finished

**Comment by code1dot** [comment]
Yeah, well anyway I have no clue how to do this. Can anybody like @ThisTestUser help me

**Comment by ThisTestUser** [comment]
Did this a while ago: https://github.com/ThisTestUser/Wurst7/tree/newchunks
I stole this from somewhere else though, so it probably won't be acceptable as a PR.

**Comment by code1dot** [comment]
Oh nice, this is just what I wanted. Thanks!

**Comment by code1dot** [comment]
Wait, @ThisTestUser I am getting an error that it is not finding MC.player.dimension.getRawId(). What do I need to import to fix that?

Thanks!

**Comment by code1dot** [comment]
And it does not work if I comment it out

**Comment by ThisTestUser** [comment]
The branch is for fabric 1.15.2. Are you using that version?

**Comment by code1dot** [comment]
No, I just added the code on to the latest version

**Comment by ThisTestUser** [comment]
The Fabric mappings probably changed in the latest version, so it probably got renamed to something else.

**Comment by code1dot** [comment]
I have looked through the yarn mappings and found nothing, so I am going to see if there is some info on it on the Fabric wiki

**Comment by code1dot** [comment]
I honestly have no idea what I am doing

**Comment by Jirubizu** [comment]
A lot of stuff got removed from Minecraft in 1.16.1 and things got moved to registers and other ways of storing data. If you need the dimension ID or what dimension you in, you can implement a mixin and create an interface that pretty much does the exact same that the previous Minecraft versions did

**Comment by Jirubizu** [comment]
Also @ThisTestUser was it forgehax?

**Comment by code1dot** [comment]
I just set it to 0 and it **seems** to work fine, but the new chunks seem kinda random and are not consistent. Sometimes they can glitch out if packets are delayed

**Comment by code1dot** [comment]
And @Jirubizu I don't think ForgeHax has a NewChunks hack

**Comment by Alexander01998** [comment]
Closing as NewChunks has been added in [Wurst 7.28](https://www.wurstclient.net/updates/wurst-7-28/).
