### ISSUE TITLE
Customizable Speed; packet mode extra elytra; AutoStrongHold;NoRender; Peek command; Nametags showing armour durability; Find Sign; AutoObsidian; ColorSigns; FastUse; AutoMount; FastSwim

### ISSUE THREAD

**Issue by BGOPC** [Wurst-Imperium/Wurst7#834]
## Description
The speed of the player while using the speed hack be customizable by Blocks/sec like flight etc
Packet mode for extra elytra making it not lose durability(Exists in future client)
AutoStrongHold: finds the location of strongholds by throwing an eye using triangulations, Other mods exist but are mostly incompatible
Peek command: shows inside of a Shulker box without opening it
Nametags shows the durability of items equipped, like .invsee but on top of the player name
find signs hack: search but for sign texts
AutoObsidian: auto block-in with obsidian
ColorSigns: Placing Colorful signs
FastUse: Eats and drinks faster
AutoMount: Mounts ridable entities.(Also llamas)
FastSwim: Makes you swim faster.
NoRender: Stops view obstructing and FPS loss caused by sprite, texture, and lighting updates.

I know there are so many but please consider adding them not like in the next update but at least like a few of them
## Screenshots / Videos (Optional)
Somewhat like the `future client` used in 2bt2

**Comment by Alexander01998** [comment]
Hey @BGOPC,

Thanks for the detailed list of suggestions! I appreciate the time and effort you've put into it. Just to let you know, we're currently holding a vote on Reddit to decide which features and changes will be included in the next update (Wurst 7.36).

If you haven't already, be sure to check it out and cast your vote for the features that matter most to you. Your input is valuable to the development of the Wurst Client, and it's always great to see the community participating in the decision-making process.

https://www.reddit.com/r/WurstClient/comments/13xaxbt/contest_mode_vote_for_new_featuressettingschanges/

**Comment by Cyclopropinon** [comment]
@Alexander01998 the link is invalid now, cuz ur reddit is private

**Comment by duggavo** [comment]
Customizable speed: Implemented with #838 .
Related: #836
Note: these PRs should be ready to be merged by @Alexander01998
