### ISSUE TITLE
~/.ssh/wurst_rsa

### ISSUE THREAD

**Issue by sportshead** [Wurst-Imperium/Wurst7#84]
Can I remove this file? It's annoying as SSH tries it first before my actual private keys, which slows down ssh auth

**Comment by Alexander01998** [comment]
That file is used by Wurst 6 to encrypt & decrypt your alt list.

If you delete this file, Wurst 6 will no longer be able to load your alt list file and will automatically replace it with a blank one. In other words, YOUR ALT LIST WILL BE DELETED.

If you don't have any alts saved in Wurst 6, you can delete it. Just be aware that it will be re-generated every time you launch Wurst 6.
