### ISSUE TITLE
Chat++

### ISSUE THREAD

**Issue by Cyclopropinon** [Wurst-Imperium/Wurst7#840]
## Description
Logs the Chat to file (seperate file for each server). Maybe add Timestamps.
Reload Chat history everytime u join server. (useful if your minecraft crashes and there was sth important in the chat.
also disable the chat history scroll limit

## helpful stuff
https://modrinth.com/mod/morechathistory
https://modrinth.com/mod/dcch (not working for me)

PS: for anyone asking, why i dont use these two mods: theyre not available for snapshots/dont work for me, also dcch deletes the messages when closing minecraft

**Comment by Alexander01998** [comment]
Hi @Cyclopropinon, just wanted to point out that Minecraft itself already logs the chat history to the `latest.log` file, with timestamps, even in snapshot versions. You can find this file in the `.minecraft/logs` folder. Hope that helps!

**Comment by Cyclopropinon** [comment]
oh thats interesting, i didnt know that. thanks!

still, disabling the scroll limit and adding chat history reload would be nice tho

**Comment by Godivctor** [comment]
it is possible to know hidden commands in chat text? like when you click the letters and it send the command as you

**Comment by Cyclopropinon** [comment]
yould be possible to implement, since its also sends it as a packet (within the text)

I see great potential in Chat++
