### ISSUE TITLE
Black GUI cant change/ dont know how to change

### ISSUE THREAD

**Issue by gollemoekes** [Wurst-Imperium/Wurst7#841]
I keep having this dark gui, i dont know how to change it i uninstalled wurst 4 times and it wont go back to normal anyone know how to fix it?

![image](https://github.com/Wurst-Imperium/Wurst7/assets/136977662/ae0e606a-9dfd-4993-aad8-09adb72df7ed)

**Comment by Cyclopropinon** [comment]
remove ur wurst folder when uninstalling
mods u use?

**Comment by Cyclopropinon** [comment]
![grafik](https://github.com/Wurst-Imperium/Wurst7/assets/119750500/5ba692d2-774c-49f3-b68b-0a556c395857)

**Comment by Alexander01998** [comment]
Hey @gollemoekes, sorry to hear that you're having trouble with the GUI. Can you tell me what your ClickGUI color settings are set to? Also, could you let me know which specific version of Minecraft and Wurst you're running? This will help me figure out what might be causing the issue. Thank you!

![screenshot of ClickGUI settings with the default colors](https://github.com/Wurst-Imperium/Wurst7/assets/10100202/bf3bb258-012f-4585-9334-11b89614a866)

**Comment by gollemoekes** [comment]
hello ty for trying to help me im running minecraft version 1.19.4 and wurst version 7.35.1 and heres my click gui settings
![image](https://github.com/Wurst-Imperium/Wurst7/assets/136977662/102c1bdd-6bdb-42a7-8c9f-3af0fd66fc7d)

**Comment by gollemoekes** [comment]
@Alexander01998

**Comment by Alexander01998** [comment]
Thanks for letting me know, @gollemoekes. Based on your ClickGUI settings, it looks like everything should be displaying normally. Do you happen to have any other mods installed that might be interfering with Wurst? Let me know, and we can try to troubleshoot from there.

**Comment by gollemoekes** [comment]
![image](https://github.com/Wurst-Imperium/Wurst7/assets/136977662/dc4cf293-17be-4ac2-af10-e0f361dd218a)
here are my mods @Alexander01998 which one should i remove

**Comment by Alexander01998** [comment]
It looks like you have quite a few mods installed, @gollemoekes. It might be difficult to determine which one is causing the issue. My recommendation would be to try disabling all mods except for Wurst and see if the issue persists. If the issue goes away, you can start adding your other mods back one at a time to see which one might be causing the problem.

**Comment by Cyclopropinon** [comment]
probably optifine, cuz it breaks almost every mod cuz the devs dont care about compatibility
