### ISSUE TITLE
Enabling AimAssist and then TriggerBot works, doing so backwards doesnt.

### ISSUE THREAD

**Issue by oIKR2** [Wurst-Imperium/Wurst7#855]
## Description
When you enable AimAssist and then TriggerBot it works, thats alright, as you can use it as a more legit version of KillAuraLegit, as KillAuraLegits attacks throught walls. But, when you try to enable TriggerBot and then AimAssist it doesn't work, but it'd be nice if it did.

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Enable AimAssist and then TriggerBot; It works.
2. Enable TriggerBot and then AimAsisst; It does not work.

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

https://[pastebin.com/raw/tCTXW7iN](https://pastebin.com/raw/tCTXW7iN (It too long)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by impresson** [comment]
lmao that's funny... 
Rip Triggerbot then Aimassist users.
