### ISSUE TITLE
Striped menu in Wurst

### ISSUE THREAD

**Issue by 4pajus** [Wurst-Imperium/Wurst7#859]
hi i download wurst 1.19.3 v7.35.1 and i have stripes in menus

![obrázek_2023-07-21_181107865](https://github.com/Wurst-Imperium/Wurst7/assets/91020954/f157fe32-7bf1-46a6-9c46-65bb9b261ede)

![obrázek_2023-07-21_181041932](https://github.com/Wurst-Imperium/Wurst7/assets/91020954/900bac53-c625-40e2-af9c-2d99b9880d47)

**Comment by Cyclopropinon** [comment]
crash report & modlist pls

**Comment by 4pajus** [comment]
it didnt crash and mod list is here 

![image](https://github.com/Wurst-Imperium/Wurst7/assets/91020954/238e8ebd-f759-4ad8-9fcf-8d3c5bf41fa4)
![image](https://github.com/Wurst-Imperium/Wurst7/assets/91020954/e2dfb0f1-e833-4105-b37f-c7dd4b3ecd5d)
![image](https://github.com/Wurst-Imperium/Wurst7/assets/91020954/5c6a5db2-26f4-44f3-b00e-0e5c5365741e)

i didnt use that ones that are turned off

**Comment by impresson** [comment]
looks kinda cool if you ask me

**Comment by Cyclopropinon** [comment]
lol
(tbh, it is)
