### ISSUE TITLE
Remove the steal and store buttons from inventories

### ISSUE THREAD

**Issue by EvilDarkSoul** [Wurst-Imperium/Wurst7#862]
Have a setting that allows you to disable the steal and store buttons in inventories

**Comment by Cyclopropinon** [comment]
https://wurstforum.net/d/90-can-we-disable-the-container-gui-buttons/2

**Comment by Alexander01998** [comment]
Hey there @EvilDarkSoul,

Good news! The feature you're requesting is already in the client. Simply head over to the [AutoSteal](https://wurst.wiki/autosteal) settings, and there you will be able to enable or disable the steal and store buttons.

Given that we already have this feature, I'll be closing this issue as completed. Feel free to reopen it if you feel your suggestion has not been addressed adequately.
