### ISSUE TITLE
How do I specify an account to use when building the source code?

### ISSUE THREAD

**Issue by NightcoreRYT** [Wurst-Imperium/Wurst7#87]
## Description
I'm just wondering, how do I specify an account to use when launching through eclipse?

## (Optional) screenshots / videos
If applicable, add screenshots or videos to help explain your problem.

## Versions
Please complete the following information:
- Minecraft version: 1.15.2
- Wurst version: Latest build + modifications

## Crash report
```
(crash report goes here)

```
Please note: A log file or a picture of the launcher's "something went wrong" screen are _not_ the same as crash report. If the game didn't crash, please hold down F3+C for 10 seconds to generate a crash report.

**Comment by Alexander01998** [comment]
I don't know, I just use Alt Manager instead.
