### ISSUE TITLE
vclip up/down integration with jesus hack

### ISSUE THREAD

**Issue by therealolie** [Wurst-Imperium/Wurst7#877]
when you use vclip up/down it automatically calculates where is the nearest avaliable ground to stand on

but currently, that could put you in lava and burn you

what im suggesting is that when you have the jesus hack on, vclip will treat lava/water as solid blocks

(this could also be a setting, instead of doing  this when jesus is on)

image:
![image](https://github.com/Wurst-Imperium/Wurst7/assets/46534106/50cb06b9-941c-4ced-a027-1edf4a481792)

**Comment by Alexander01998** [comment]
Hey @therealolie! Thanks for the bug report. I'm not sure when exactly this bug got fixed, but I just ran a test and found that the current implementation of `.vclip` does indeed teleport the user above liquids when Jesus is enabled. Therefore, I'm closing this issue as resolved.

https://github.com/Wurst-Imperium/Wurst7/assets/10100202/e38afebd-85e0-4a40-a20b-ba3f420ee4e2

**Comment by therealolie** [comment]
i reported this because vcliping trough lava always put me on fire, idk what was happening, will do some testing tomorrow
