### ISSUE TITLE
Please review the fixed Chinese translation in Crowdin and add the new translatable strings to crowdin

### ISSUE THREAD

**Issue by Clexus** [Wurst-Imperium/Wurst7#881]
I submitted some proper translations and there is no proofreader to admit my translations

**Comment by Alexander01998** [comment]
Hey @Clexus,

Thanks for your help with the Chinese translations and I'm sorry I haven't reviewed them yet.

At the moment, I'm quite busy with other parts of the project, but I will try my best to review them as soon as I can.
