### ISSUE TITLE
Automatically send chat messages

### ISSUE THREAD

**Issue by ren-yc** [Wurst-Imperium/Wurst7#883]
## Description
A function for automatically sending chat messages and adjusting the sending interval time.

This is very helpful for player store advertising in the server.

## Screenshots / Videos (Optional)
None.

**Comment by ren-yc** [comment]
We can also make a new function similar to timed triggering of a certain button, which will have a wider range of usage.

**Comment by 837951602** [comment]
Seems also useful to command something if you want to antiAFK but not move
