### ISSUE TITLE
Windows Client

### ISSUE THREAD

**Issue by crack00r** [Wurst-Imperium/Wurst7#885]
It would be cool if there is any "Windows Client" coming up, cause mayn people already switch fom Java to Windows Client.

![image](https://github.com/Wurst-Imperium/Wurst7/assets/6163329/8f099dbb-f727-423d-b2d3-673b2e071b2e)

**Comment by NornTech** [comment]
No they haven't, bedrock is trash

**Comment by Chris6ix** [comment]
Except for some specific things, Java is far superior to Bedrock. No one is switching from Java to Bedrock lmao.
