### ISSUE TITLE
Friends are highlighted in red, not blue on the radar

### ISSUE THREAD

**Issue by daniliammo** [Wurst-Imperium/Wurst7#895]
Friends are highlighted in red, not blue on the radar

![ScreenShot](https://github.com/Wurst-Imperium/Wurst7/assets/67186086/0727cd0e-7f77-4a9e-a928-71feefd4b7db)

**Comment by Alexander01998** [comment]
Hey @daniliammo,

Thanks for reaching out, but this issue has already been resolved with the [Wurst 7.36](https://www.wurstclient.net/updates/wurst-7-36/) update. I just ran a test on the latest version ([Wurst 7.38](https://www.wurstclient.net/updates/wurst-7-38/)) and can confirm that Radar shows friends in blue as expected.

It seems like you might be using an outdated version of Wurst, which would explain why you're running into this issue. I recommend updating to the latest version to have this fixed.

I hope this helps! Please let me know if you continue to have any trouble.
