### ISSUE TITLE
New Feature Proposal - Automatic Torch Placement

### ISSUE THREAD

**Issue by MineYuanlu** [Wurst-Imperium/Wurst7#897]
I have developed a new feature and I'm not sure if it would be helpful: Automatic Torch Placement.

The primary motivation behind creating this feature is to automate torch placement in mob spawning areas, which is particularly useful for survival mode.

Currently, I have created a demo that includes two settings: Placement Range and Detection Range. My program will automatically choose an appropriate location to place a torch based on these two ranges.

As this is a demo, I have only implemented torch placement for now, but in reality, it can work with any light source.

Here's how my program works:

1. It identifies all blocks within the detection range that may potentially spawn mobs (block light< 1).
2. Among these blocks, it finds a location that can illuminate the most number of blocks.
3. If the location is within the placement radius, it places a torch. Otherwise, it provides a notification.

![图片](https://github.com/Wurst-Imperium/Wurst7/assets/38997444/3912ac63-06c9-4398-ac77-fc4bea0eba48)
![图片](https://github.com/Wurst-Imperium/Wurst7/assets/38997444/88a96401-de99-4a80-96b4-b1ef547b8bf5)
![图片](https://github.com/Wurst-Imperium/Wurst7/assets/38997444/7762ebab-7dcf-4492-9ca6-9e05c58ee992)
![图片](https://github.com/Wurst-Imperium/Wurst7/assets/38997444/4db87e8f-6506-4e77-a64c-1f96f329e6a4)

**Comment by dingzhen-vape** [comment]
useful

**Comment by MineYuanlu** [comment]
> useful

#911
