### ISSUE TITLE
Wurst Java to DLL with process hacker

### ISSUE THREAD

**Issue by Cyrilsou** [Wurst-Imperium/Wurst7#898]
Before posting, please make sure that this hasn't already been suggested by someone else.

## Description
What does it do and how is it useful? Please assume that we have never heard of it before. Just mentioning a name won't work. If it's for an older version of Minecraft (like 1.8 or 1.12), please mention that too.

I want to play with wurst in blockfront. I have idee to put Wurst client to a DLL and put it in game instance to bypass anti cheat

It is possible ? How i do that ?

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the suggestion.

**Comment by Alexander01998** [comment]
Hi @Cyrilsou,

Thanks for the suggestion, but I'm afraid it's not possible or effective, considering how Minecraft is structured. Minecraft runs on Java, and it doesn't utilize DLL files for modifying the game. DLLs are specifically related to programs written in C, C++, etc., and they aren’t used in Java applications like Minecraft.

As for bypassing anti-cheats, changing how the cheat is loaded wouldn't make a significant difference. Minecraft anticheats typically work by looking for cheat-like behavior in the network traffic, not by looking at client-side EXE files (which again, Minecraft doesn't have).

I hope this clears things up.
