### ISSUE TITLE
X-ray does't work with OptiFine

### ISSUE THREAD

**Issue by Shuna322** [Wurst-Imperium/Wurst7#9]
Wurst-Client-v7.0pre8-MC1.14.4
Minecraft version: 1.14.4
Operating system: Win10
Optifine/Other mods: OptiFine_1.14.4_HD_U_F3, optifabric-0.5.2

fabric-api-0.3.2+build.226-1.14

Whats the issue:
XRay doesn't seems to work correctly with the new OptiFine version. If i press X no blocks dissapear, except beds. Adding blocks or removing them doesnt change that. Everthing stays solid.

**Comment by Alexander01998** [comment]
Fixed in v7.0pre10 (commit be320b80fb3cf400bbb8943a8a3352bf459c5a9d)
