### ISSUE TITLE
BaseFinder randomly highlighting 10k air blocks

### ISSUE THREAD

**Issue by SkyxD69** [Wurst-Imperium/Wurst7#903]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

Randomly shows found 1000+ blocks but its just air

### Repro steps

1.
2.
3.
<img width="1440" alt="Screenshot 2023-11-17 at 3 31 33 PM" src="https://github.com/Wurst-Imperium/Wurst7/assets/107539245/23d1af49-418f-4734-b214-d0fb165b8198">

### Wurst Client version

7.35.2

### Minecraft version

19.2

**Comment by Alexander01998** [comment]
Hi @SkyxD69,

Thanks for the bug report. I'd like some more information to better understand what might be happening. Can you please tell me what your "Natural Blocks" setting in BaseFinder is set to?

As a next step, try resetting the "Natural Blocks" setting to its default value and then restarting BaseFinder.

If that doesn't help, you might want to try adding `void_air` to the list and restarting again.

Let me know if any of these steps seem to resolve your issue.

Thanks!
