### ISSUE TITLE
Add HitboxExpander

### ISSUE THREAD

**Issue by mdenials** [Wurst-Imperium/Wurst7#905]
### Pre-suggestion checklist

- [ ] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [ ] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack.

### What type of player would find this improvement useful?

PVPers

### Description

HitboxExpander function, lists of code below
[EntityHitboxMixin.txt](https://github.com/Wurst-Imperium/Wurst7/files/13464371/EntityHitboxMixin.txt)
[HitboxExpanderHack.txt](https://github.com/Wurst-Imperium/Wurst7/files/13464372/HitboxExpanderHack.txt)
[HitboxListener.txt](https://github.com/Wurst-Imperium/Wurst7/files/13464373/HitboxListener.txt)

**Comment by Lukim99** [comment]
> This is just a sketch of the function, I do not know what it will look like when it is completed - it will take time to write a working version

great. I think it would be a really powerful feature if a working version were made
