### ISSUE TITLE
Vulkan Renderer incompatibility

### ISSUE THREAD

**Issue by Nitjsefnie** [Wurst-Imperium/Wurst7#909]
### Pre-reporting checklist

- [x] I have searched existing issues and didn't find any previous reports of this bug.
- [x] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [x] I have tried removing all other mods and the bug still happens.

### Description

With Vulkan Renderer mod installed, game crashes on joining a world

### Repro steps

Install Vulkan Renderer and Wurst. Try to join a world.

### Wurst Client version

7.39.1

### Minecraft version

1.20.1

### Crash report (if applicable)

```plaintext
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa2262c68d, pid=17276, tid=2060
#
# JRE version: OpenJDK Runtime Environment (17.0+35) (build 17+35-2724)
# Java VM: OpenJDK 64-Bit Server VM (17+35-2724, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00007ffa2262c68d
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Peter\Desktop\mmc-develop-win32\MultiMC\instances\1.20.1\.minecraft\hs_err_pid17276.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#


PasteBin to the .log file: https://www.pastebin.cz/en/p/FVPUPB4
```

**Comment by Alexander01998** [comment]
Hi @Nitjsefnie, thanks for reaching out!

Looking at [VulkanMod's Modrinth page](https://modrinth.com/mod/vulkanmod), it warns that the game will crash if there's any other mod present that renders things using OpenGL. Unfortunately, as the Wurst Client relies entirely on OpenGL for rendering, that means the two mods just aren't compatible.

If you're looking for ways to improve Minecraft's performance, I'd recommend using [Sodium](https://modrinth.com/mod/sodium) instead. It's a great performance mod, and it's compatible with the Wurst Client as well.

Hope this helps.

**Comment by Nitjsefnie** [comment]
Hello, I know about Sodium, however Vulkan offers better performance boost.
