### ISSUE TITLE
Correct movement for killauras

### ISSUE THREAD

**Issue by impresson** [Wurst-Imperium/Wurst7#912]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a different kind of feature.

### What type of player would find this improvement useful?

PVPers, Other (please explain in description)

### Description

Basically yk how wurst doesn't have some anticheat bypasses
its been a while since we got one.
How this works and what it is is that the killaura you use (prob just the normal one bc it might only work for the normal one.) would check to see if you could move like that in vanilla. Think of it like a target strafe (ADD STRAFE IM BEGGING U PLEASE) and then if it doesn't it tries to correct it by moving it in ways that wont trigger the anticheats. This is how most popular "utility" or hacked clients manage to bypass some ac.
also add a silent aim feature to ka that makes it so u can silently aim while using ka or just whenever u attack
idk how to describe it hopefully someone can clarify or smth.
ok bai bai :>

**Comment by impresson** [comment]
the fdpers would be so proud

**Comment by Alexander01998** [comment]
Hi @impresson,

Thanks for sharing your suggestion. However, I'd like to clear up a few misconceptions and explain why the proposed changes are not really applicable for Wurst's Killaura feature.

First and foremost, Killaura in the Wurst Client is already designed only to rotate the player in ways that are possible in vanilla Minecraft. It doesn't directly influence the player's movement; therefore, there's no place for a system that checks if the player could "move like that in vanilla". Misunderstandings like this could lead to suggestions that are not constructive or applicable to the actual functionality of Wurst.

Regarding your mention of "silent aim", Killaura already operates in that way, only rotating you on the server side without making it apparent to the client. This functionality is also [documented](https://wurst.wiki/killaura) in the Wurst Wiki. It's important to verify existing features before suggesting additions that may already be present.

Lastly, I want to address the mention of "strafe". Including suggestions for unrelated features in issues focused on a specific topic can muddle the discussion and is not the best practice for providing clear, actionable feedback.

For future suggestions, it would be ideal to bring up specific changes that could explicitly bypass certain anticheat checks; general calls for "more bypasses" are not particularly actionable without precise details.

I'm closing this issue for now. If you have concrete improvements or features with detailed explanations, feel free to open a new issue.
