### ISSUE TITLE
The Zoomify mod doesn't work with Wurst Client

### ISSUE THREAD

**Issue by Ryuo1** [Wurst-Imperium/Wurst7#922]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

The [Zoomify](https://modrinth.com/mod/zoomify) mod doesn't work when using Wurst mod.
The zoomify mod has a much better zoom in my opinon, with smooth zooming and greater range, so I would prefer to use that instead of Wurst's zoom.

How it looks when trying to use the zoomify mod with wurst: https://www.youtube.com/watch?v=kpeAOzAYVkU

### Repro steps

1. Adds Wurst client and Zoomify to the mods folder.
2. Set Zoomify's zoom key to `c` or any other keybind.
3. When trying to zoom using the Zoomify's zoom keybind, it doesn't work. If Zoomify and Wurst zoom use the same keybind, it doesn't work either. But when I unbind Zoomify zoom key, and set it to Wurst zoom instead, the zoom starts working.

### Wurst Client version

7.40

### Minecraft version

1.20.4

**Comment by notdido** [comment]
Happens to me too, was there a workaround that you found eventually?

**Comment by Ryuo1** [comment]
Not really. I haven't found any workarounds.

**Comment by SnoopyCodeX** [comment]
Same happens for me, It would be really nice if wurst zoom can be disabled somehow so that other zoom mods can be used

**Comment by nyks91** [comment]
Is there a solution for this situation?
