### ISSUE TITLE
Incompatibility with Sinytra Connector, caused by setVelocityFromFluid redirect mixin (AntiWaterPush)

### ISSUE THREAD

**Issue by finnnnnnnnnnnnnnnnn** [Wurst-Imperium/Wurst7#924]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

When attempting to use [Wurst](https://github.com/Wurst-Imperium/Wurst7/) with [Sinytra/Connector](https://github.com/Sinytra/Connector), an experimental mod that allows one to use Fabric mods on Forge, one gets the error

 > org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector setVelocityFromFluid(Lnet/minecraft/world/entity/Entity;Lnet/minecraft/world/phys/Vec3;)V in wurst.mixins.json:EntityMixin from mod wurst failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Wurst-Client-refmap.json

The setVelocityFromFluid function does not appear to be used anywhere in Wurst's code, and when I removed it from Wurst it builds and runs successfully, aside from a visual glitch in the starting menu.

I've reported this issue to Connector but I've been informed that they won't fix this due to not supporting hacks.

### Repro steps

 1. Install [Wurst Client](https://www.wurstclient.net/updates/wurst-7-39-1/?mc=1.20.1#downloads), [Connector](https://modrinth.com/mod/connector/version/1.0.0-beta.32+1.20.1), and [Forgified](https://modrinth.com/mod/forgified-fabric-api/version/0.91.0+1.10.4+1.20.1) (I've linked the specific versions I used)
 2. Launch Minecraft

### Wurst Client version

7.39.1

### Minecraft version

1.20.1

### Crash report (if applicable)

```plaintext
https://gist.github.com/some16/24c186d291de597c920d7e0af7c42576
```

**Comment by Alexander01998** [comment]
Hey @some16, thank you for the detailed bug report. It's much appreciated!

However, the `setVelocityFromFluid` mixin is a necessary part of the Wurst Client that makes the AntiWaterPush hack work. It is not something that can simply be removed without losing that functionality.

It might still be possible to tweak the mixin for better compatibility with mods like Sinytra Connector, but it's not immediately clear how to do this without breaking AntiWaterPush.

For now, I've gone ahead and edited the title of this issue to better reflect the situation at hand. Please avoid using phrases like "easily fixable" in future bug reports. It can unintentionally come across as quite dismissive of the complexity involved in mod/hack development - and bugs are rarely as straightforward as they seem at first.

**Comment by some16** [comment]
Sorry about that, I'll avoid doing that in the future.

**Comment by blammie** [comment]
❗
