### ISSUE TITLE
word seed hack

### ISSUE THREAD

**Issue by SJK9906** [Wurst-Imperium/Wurst7#934]
### Pre-suggestion checklist

- [ ] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [ ] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack., Changing the settings of existing features.

### What type of player would find this improvement useful?

Miners, Griefers, Redstoners, Anarchy/faction players

### Description

i suggest to add hack based on world seed:
- seed craker
- seed ray (a version of X-ray based on word seed, that can bypass all anti X-ray plug-ins)
- possibility to locate struture with word seed

other:
- packet eraser
- enanchment for fastbrake: addind fast brake based on haster to give possibility to don't brake a block after start to brak a bloock

**Comment by Alexander01998** [comment]
Hey @SJK9906,
Since we already have a lot of issues about this topic, let's just track it in #860 and not open any more of them.
Thank you!
