### ISSUE TITLE
Notebot support

### ISSUE THREAD

**Issue by flaryx32** [Wurst-Imperium/Wurst7#937]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [x] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new chat command.

### What type of player would find this improvement useful?

Redstoners

### Description

Support for notebot a bot that auto places auto tunes and auto play songs from nbs files

**Comment by feliscatusmeows** [comment]
Support for future .notebot files (https://github.com/bstar16/Phobos-1.9.0-BUILDABLE-SRC/blob/main/src/main/java/me/earth/phobos/features/modules/misc/NoteBot.java) and inertia/bleachhack .txt notebot files (https://github.com/BleachDev/BleachHack/blob/2a30d34be73aa62484bb1ede97a7f657044fe333/src/main/java/org/bleachhack/util/NotebotUtils.java#L132) which is tick:pitch:instrument in a txt file seperated by new lines. 
also the format for .nbs is at https://opennbs.org/nbs

**Comment by feliscatusmeows** [comment]
If making a notebot song stealer then recording to bleachhack/inertia format should be simpler as it's just `tick:pitch:instrument` for each note on a new line

**Comment by flaryx32** [comment]
Still relevant for me, I really wish this gets added!
