### ISSUE TITLE
Can not bypass a checker

### ISSUE THREAD

**Issue by huzpsb** [Wurst-Imperium/Wurst7#94]
## Description
There is a skript plugin called "anti-bypass".It can detect wurst.
## Steps to reproduce
1. Go to ['download this skript'](https://www.mcbbs.net/thread-850985-1-1.html)
2. Install it.
3. You can't be logged in to the server with it.

## (Optional) Suggestions
Could you please add a feature that allow us to disable commands(for a certain while)?

**Comment by ThisTestUser** [comment]
Just do .say <message>. For example, to say the phrase ".say 123", write ".say .say 123".

**Comment by huzpsb** [comment]
> Just do .say . For example, to say the phrase ".say 123", write ".say .say 123".

however,It's a xml-based validate.It means I can't see what I'm about to say :{

**Comment by Jirubizu** [comment]
huh?
what do you mean you cant see what your about to say?

if it requires you to enter something you can just follow the auto fill and before presseing enter CTRL+A then CTRL+X then write .say and then press CTRL+V

**Comment by huzpsb** [comment]
> huh?
> what do you mean you cant see what your about to say?
> 
> if it requires you to enter something you can just follow the auto fill and before presseing enter CTRL+A then CTRL+X then write .say and then press CTRL+V

It is based on json,you know,just like shouwing a link
You're required to click the link in the chat,instead of saying something

**Comment by Jirubizu** [comment]
> 
> 
> > huh?
> > what do you mean you cant see what your about to say?
> > if it requires you to enter something you can just follow the auto fill and before presseing enter CTRL+A then CTRL+X then write .say and then press CTRL+V
> 
> It is based on json,you know,just like shouwing a link
> You're required to click the link in the chat,instead of saying something

then just click the link, whats stopping you from clicking a link?

send the IP I wanna try

**Comment by huzpsb** [comment]
> > > huh?
> > > what do you mean you cant see what your about to say?
> > > if it requires you to enter something you can just follow the auto fill and before presseing enter CTRL+A then CTRL+X then write .say and then press CTRL+V
> > 
> > 
> > It is based on json,you know,just like shouwing a link
> > You're required to click the link in the chat,instead of saying something
> 
> then just click the link, whats stopping you from clicking a link?
> 
> send the IP I wanna try

Just an example, mchuya.com

**Comment by Alexander01998** [comment]
> Could you please add a feature that allow us to disable commands(for a certain while)?

You can temporarily disable Wurst, including the command processor, by using the "Disable Wurst" button on the statistics screen.

**Comment by ThisTestUser** [comment]
If you want to bypass the checker, press "Disable Wurst", join the server, and then click the link. You can re-enable afterwards.

**Comment by huzpsb** [comment]
> If you want to bypass the checker, press "Disable Wurst", join the server, and then click the link. You can re-enable afterwards.

(Only if I can do that quickly enough.You should know that the operator often make us click it without giving us more than 10 seconds...

**Comment by huzpsb** [comment]
Well,maybe I will modify that on my own :{

**Comment by huzpsb** [comment]
QaQ

**Comment by ThisTestUser** [comment]
You can disable Wurst before you login.
