### ISSUE TITLE
Multislot Restock

### ISSUE THREAD

**Issue by 837951602** [Wurst-Imperium/Wurst7#945]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Changing the settings of existing features.

### What type of player would find this improvement useful?

Builders

### Description

It looks quite useful if multiple slots are automatically restocked with different item.
I'm not up-to-date installation but I checked code this isn't done.
Absolutely possible to implement as worst case is 9 clones of Restock

**Comment by Cyclopropinon** [comment]
tbh i think this is a great idea
