### ISSUE TITLE
Fabritone block placement

### ISSUE THREAD

**Issue by 1abinitio1** [Wurst-Imperium/Wurst7#95]
## Description
When using fabritone, i noticed that it puts a green outline where it wants to place a block,
but then it fails, and gets stuck until it recalculates an takes a different path
(suspect this issue only happens if it had broken the same block before)
for example:
goes up a mountain, breaks a block so it can move to some place higher,
and then wants to place it back again to walk over it, this fails.

## Steps to reproduce
enable farbitone and make it go up a mountain or uneven terrain

## Versions
Please complete the following information:
- Minecraft version: 1.15.2
- Wurst version: 7.1.2

**Comment by p3iurhgmc98h** [comment]
I'm pretty sure this is a separate issue with Fabritone, and isn't related to Wurst.

**Comment by jhonnystene** [comment]
It's an issue with Fabritone, I have the same problem w/ Wurst disabled.
