### ISSUE TITLE
Search Bell Broken

### ISSUE THREAD

**Issue by coolnoob78** [Wurst-Imperium/Wurst7#952]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

If you search (block esp) for bell, floor mounted bells dont show up

### Repro steps

search for bell
bell doesnt apear

### Wurst Client version

latest

### Minecraft version

1.20.4

**Comment by Alexander01998** [comment]
Could not reproduce. All bells show up for me regardless of mounting.

![a Minecraft screenshot showing five bells with different mounting types all being highlighted by Wurst's Search hack](https://github.com/Wurst-Imperium/Wurst7/assets/10100202/701bf530-3eb6-4cea-b589-1fc500ac208e)

**Comment by coolnoob78** [comment]
You are using other mods

**Comment by Alexander01998** [comment]
Is this some kind of sick joke? You're just sending me on a wild goose chase for a bug that doesn't exist! Come back when you have an actual bug to report. >:(

![Another Minecraft screenshot showing five bells with different mounting types all being highlighted by Wurst's Search hack. No other hacks or mods are present.](https://github.com/Wurst-Imperium/Wurst7/assets/10100202/d23c5281-c581-49b9-a2bc-1c3a0cedbea8)
