### ISSUE TITLE
triggerbot cps

### ISSUE THREAD

**Issue by tadduplaysyt** [Wurst-Imperium/Wurst7#990]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a different kind of feature.

### What type of player would find this improvement useful?

PVPers

### Description

hi there im back again , soo i have to tell you that when we turn off triggerbot and hit someone our cps counts on the cps mod but when triggerbot is turn on cps doesnt count on cps mod soo i want to tell u that can u make a triggerbot with cps count for undetectable heres video 

https://github.com/Wurst-Imperium/Wurst7/assets/168188048/fd45a841-d304-4579-9d72-a9d0b123cc31

in this video u can see the keystrokes with trigger bot and without trigger bot pls fix it

**Comment by tadduplaysyt** [comment]
u can we when im clicking normally and when im clickking with triggerbot

**Comment by Alexander01998** [comment]
Got it! I have added a "Simulate mouse click" option that can be used to fool CPS mods into thinking you attacked manually.

Simulating mouse clicks can lead to some unexpected behavior and will prevent TriggerBot's "Swing hand" and "Attack while blocking" settings from working, but this should still be a useful feature for players who want maximum stealth. 🐱‍👤

![A side-by-side video of TriggerBot attacking with and without the "Simulate mouse clicks" option. The TipTapShow CPS mod is installed to show the difference.](https://github.com/Wurst-Imperium/Wurst7/assets/10100202/229da74c-9fb7-4fa4-9645-56511ac02929)

This new setting will be released in Wurst 7.42.
