### ISSUE TITLE
triggerbot is detected now

### ISSUE THREAD

**Issue by tadduplaysyt** [Wurst-Imperium/Wurst7#997]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

soo the triggerbot is detected i tried it with the three animation still getting kicked with every animation can u fix this 

### Repro steps

1

### Wurst Client version

7.42

### Minecraft version

1.20.1

**Comment by Alexander01998** [comment]
Hey @tadduplaysyt,

Thanks for the report! However, Minecraft by itself doesn't come with any anticheat systems that could detect hacks like TriggerBot. It sounds like you were actually kicked by a third-party anticheat plugin on the server you're playing on.

Could you provide more details about which specific anticheat plugin is detecting your TriggerBot? Different plugins can have different detection methods, so knowing which one it is will help me figure out what changes might be needed to make TriggerBot bypass again.

If you can provide that info, it'll be super helpful!

**Comment by tadduplaysyt** [comment]
yeah i can tell u it was detected by vulkan and it was also detected on gamertee.net this server

**Comment by Alexander01998** [comment]
Can confirm this will be fixed in Wurst 7.43. 👍
